import type { AppraisalInstrument, WhoEtdCriteriaInput, WhoEtdEvaluationResult } from '../types';
import { MASTER_INSTRUMENTS_REGISTRY } from '../data/masterRegistry';

export interface Amstar2EvaluationResult { criticalFlawsCount:number; nonCriticalFlawsCount:number; criticalFlawItems:number[]; overallConfidence:'High'|'Moderate'|'Low'|'Critically Low'; confidenceRationale:string; methodologicalWarning?:string; }
export interface Agree2DomainScore { domainId:number; domainName:string; itemIds:number[]; obtainedScore:number; minPossibleScore:number; maxPossibleScore:number; standardizedScorePercent:number; }
export interface Agree2EvaluationResult { domainScores:Agree2DomainScore[]; overallRecommendation:'MANUAL_RECOMMENDATION_REQUIRED'; recommendationRationale:string; methodologicalNote:string; }
export interface Rob2DomainEvaluation { domainId:string; domainTitle:string; riskOfBias:'Low risk'|'Some concerns'|'High risk'; signallingItemsSummary:string; }
export interface Rob2EvaluationResult { variant:'parallel-group'|'cluster-randomised'|'crossover'; domainEvaluations:Rob2DomainEvaluation[]; overallRiskOfBias:'Low risk'|'Some concerns'|'High risk'; phase3OverallRiskOfBias:'Low risk'|'Some concerns'|'High risk'; algorithmRationale:string; }
export interface GradeCertaintyEvaluation { outcomeName:string; studyDesign:'RCT'|'Observational'; initialCertainty:'High'|'Low'; downgradeFactors:{riskOfBias:0|-1|-2;inconsistency:0|-1|-2;indirectness:0|-1|-2;imprecision:0|-1|-2;publicationBias:0|-1|-2}; upgradeFactors:{largeEffect:0|1|2;doseResponse:0|1;opposingConfounders:0|1}; finalCertainty:'High'|'Moderate'|'Low'|'Very Low'; certaintyRationale:string; }
export interface CaspQualitativeResult { screeningQuestionsPassed:boolean; methodologicalRigorNotes:string; isValuableLocally:boolean; qualitativeSummary:string; }
export type CerqualConcern = 'No or very minor concerns'|'Minor concerns'|'Moderate concerns'|'Serious concerns';
export interface GradeCerqualComponentEvaluation { methodologicalLimitations:CerqualConcern; coherence:CerqualConcern; adequacyOfData:CerqualConcern; relevance:CerqualConcern; }
export interface GradeCerqualEvaluationResult { reviewFinding:string; components:GradeCerqualComponentEvaluation; overallConfidence:'High confidence'|'Moderate confidence'|'Low confidence'|'Very low confidence'; confidenceExplanation:string; methodologicalNote:string; }
export interface Prisma2020SectionSummary { sectionName:string; totalItems:number; reportedCount:number; partialCount:number; notReportedCount:number; notApplicableCount:number; adherencePercentage:number; }
export interface Prisma2020EvaluationResult { checklistItemsEvaluated:number; sectionSummaries:Prisma2020SectionSummary[]; overallReportingCompleteness:number; flowDiagramComplete:boolean; searchStrategyTransparent:boolean; methodologicalNotice:string; }
export interface Cfir2ConstructItem { domainId:'innovation'|'outer_setting'|'inner_setting'|'individuals'|'process'; domainName:string; constructId:string; constructName:string; classification:'Facilitator (+2)'|'Facilitator (+1)'|'Neutral (0)'|'Barrier (-1)'|'Barrier (-2)'|'Not applicable'; contextualEvidence:string; }
export interface Cfir2EvaluationResult { totalConstructsAssessed:number; facilitatorsCount:number; barriersCount:number; neutralCount:number; domainSummaries:Record<string,unknown>[]; overallImplementationProfile:'Favorable'|'Mixed'|'Challenging'|'Insufficient evidence'; methodologicalNote:string; }
export interface KtaPhaseStatus { phaseId:string; phaseName:string; status:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'; evidence:string; barriers:string[]; facilitators:string[]; }
export interface KtaEvaluationResult { phases:KtaPhaseStatus[]; completedCount:number; blockedCount:number; overallStatus:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'; methodologicalNote:string; }

const AMSTAR_CRITICAL=new Set([2,4,7,9,11,13,15]);
const ROB2_DOMAINS=[['D1','Randomiseringsprosess','Sekvensgenerering og allokeringsskjuling'],['D2','Avvik fra intenderte intervensjoner','Blindingsintegritet og intervensjonsavvik'],['D3','Manglende utfallsdata','Frafall, manglende data og håndtering'],['D4','Måling av utfall','Utfallsdefinisjon, målemetode og blinding'],['D5','Valg av rapportert resultat','Analyseplan og selektiv rapportering']] as const;
const ROBINSI_DOMAINS=['D1','D2','D3','D4','D5','D6','D7'] as const;
const ROBIS_DOMAINS=['domain1Eligibility','domain2Identification','domain3DataCollection','domain4Synthesis'] as const;
const QUADAS_ROB=['robPatientSelection','robIndexTest','robReferenceStandard','robFlowTiming'] as const;
const QUADAS_APP=['appPatientSelection','appIndexTest','appReferenceStandard'] as const;
const QUIPS_DOMAINS=['participation','attrition','factorMeasurement','outcomeMeasurement','confounding','statisticalAnalysis'] as const;
const PROBAST_ROB=['participantsRoB','predictorsRoB','outcomeRoB','analysisRoB'] as const;
const PROBAST_APP=['participantsApplicability','predictorsApplicability','outcomeApplicability'] as const;
const CASP_IDS=new Set(['casp-qualitative','casp-rct','casp-systematic-review','casp-cohort']);
const requireExactKeys=(r:Record<string,unknown>,keys:string[],name:string)=>{const p=Object.keys(r).sort(),e=[...keys].sort();if(p.length!==e.length||p.some((v,i)=>v!==e[i]))throw new Error(`${name} krever nøyaktig ${e.length} felter.`);};
const riskRank=(v:string)=>{const s=v.toLowerCase();return s.includes('critical')||s.includes('very high')?4:s.includes('high')||s.includes('serious')?3:s.includes('moderate')||s.includes('some concerns')?2:s.includes('low')?1:0;};
const concernRank=(v:string)=>{const s=v.toLowerCase();return s.includes('serious')?3:s.includes('moderate')?2:s.includes('minor')?1:0;};
const overallRisk=(v:string[])=>{const m=Math.max(...v.map(riskRank),0);return(m>=3?'High risk':m===2?'Some concerns':'Low risk') as 'Low risk'|'Some concerns'|'High risk';};
const norm=(v:string)=>v.trim().toLowerCase();

export class Amstar2AssessmentEngine{public static evaluate(i:Record<number,string>):Amstar2EvaluationResult{const k=Object.keys(i).map(Number).sort((a,b)=>a-b);if(k.length!==16||k.some((v,n)=>v!==n+1))throw new Error('AMSTAR 2 krever 16 items.');const allowed=new Set(['Yes','Partial Yes','No','No meta-analysis conducted']);const criticalFlawItems:number[]=[];let nonCriticalFlawsCount=0;for(let n=1;n<=16;n++){const a=i[n];if(!allowed.has(a))throw new Error(`Ugyldig AMSTAR 2-svar i Item ${n}.`);if(a==='No')(AMSTAR_CRITICAL.has(n)?criticalFlawItems.push(n):nonCriticalFlawsCount++);}const c=criticalFlawItems.length;return{criticalFlawsCount:c,nonCriticalFlawsCount,criticalFlawItems,overallConfidence:c===0?(nonCriticalFlawsCount<=1?'High':'Moderate'):c===1?'Low':'Critically Low',confidenceRationale:`AMSTAR 2: ${c} kritiske og ${nonCriticalFlawsCount} ikke-kritiske mangler.`,methodologicalWarning:'AMSTAR 2 skal ikke reduseres til en numerisk totalscore.'};}}
export class Agree2AssessmentEngine{public static readonly DOMAINS=[{id:1,name:'Omfang og formål',items:[1,2,3]},{id:2,name:'Interessentinvolvering',items:[4,5,6]},{id:3,name:'Metodisk stringens',items:[7,8,9,10,11,12,13,14]},{id:4,name:'Klarhet',items:[15,16,17]},{id:5,name:'Anvendelighet',items:[18,19,20,21]},{id:6,name:'Redaksjonell uavhengighet',items:[22,23]}] as const;public static evaluateDomainScores(r:Record<number,number>):Agree2EvaluationResult{const k=Object.keys(r).map(Number).sort((a,b)=>a-b);if(k.length!==23||k.some((v,n)=>v!==n+1))throw new Error('AGREE II krever 23 items.');const invalid=k.find(n=>!Number.isInteger(r[n])||r[n]<1||r[n]>7);if(invalid!==undefined)throw new Error(`Ugyldig AGREE II-skår i Item ${invalid}.`);const domainScores=this.DOMAINS.map(d=>{const itemIds=[...d.items],obtainedScore=itemIds.reduce((s,n)=>s+r[n],0),minPossibleScore=itemIds.length,maxPossibleScore=itemIds.length*7;return{domainId:d.id,domainName:d.name,itemIds,obtainedScore,minPossibleScore,maxPossibleScore,standardizedScorePercent:Number((((obtainedScore-minPossibleScore)/(maxPossibleScore-minPossibleScore))*100).toFixed(2))};});return{domainScores,overallRecommendation:'MANUAL_RECOMMENDATION_REQUIRED',recommendationRationale:'AGREE II gir ikke en samlet automatisk anbefaling. Overordnet anbefaling skal fastsettes eksplisitt av granskeren.',methodologicalNote:'Kun seks uavhengige domeneskårer rapporteres; ingen gjennomsnittlig totalscore beregnes.'};}}
export class JbiQualitativeAssessmentEngine{public static evaluate(items:{questionId:number;status:string;justification?:string}[]){const o=[...items].sort((a,b)=>a.questionId-b.questionId);if(o.length!==10||o.some((x,n)=>x.questionId!==n+1))throw new Error('JBI Qualitative krever 10 unike items.');const v=new Set(['ja','nei','uklart','ikke relevant','yes','no','unclear','not applicable']);if(o.some(x=>!v.has(norm(x.status))))throw new Error('Ugyldig JBI-svar.');const strengths=o.filter(x=>['ja','yes'].includes(norm(x.status))),weaknesses=o.filter(x=>['nei','no'].includes(norm(x.status))),unresolved=o.filter(x=>['uklart','unclear'].includes(norm(x.status)));const identifiedDefects=[...weaknesses.map(x=>`Kriterium ${x.questionId}: Ikke oppfylt (${x.justification?.trim()||'Ingen begrunnelse oppgitt'})`),...unresolved.map(x=>`Kriterium ${x.questionId}: Uklart (${x.justification?.trim()||'Krever avklaring'})`)];return{jaCount:strengths.length,neiCount:weaknesses.length,uklartCount:unresolved.length,ikkeRelevantCount:o.filter(x=>['ikke relevant','not applicable'].includes(norm(x.status))).length,verdict:unresolved.length?'Søk mer informasjon':weaknesses.length?'Vurder videre':'Inkluder',rationale:unresolved.length?'Minst ett JBI-kriterium er uavklart og må avklares før endelig beslutning.':weaknesses.length?'Metodiske svakheter er identifisert. Endelig beslutning krever eksplisitt forskerbegrunnelse.':'Alle ti JBI-kriterier er besvart Ja. Dette er en kvalitativ forskervurdering, ikke en cut-off.',identifiedDefects,criticalItemsDefects:weaknesses.map(x=>`Kriterium ${x.questionId}: ${x.justification?.trim()||'Ikke oppfylt'}`),methodologicalNote:'JBI Qualitative (2017) har ingen rigid numerisk cut-off; endelig beslutning er kvalitativ.'};}}
export class Rob2AssessmentEngine{public static evaluate(d:{variant?:'parallel-group'|'cluster-randomised'|'crossover';d1Randomisation:'Low risk'|'Some concerns'|'High risk';d2Deviations:'Low risk'|'Some concerns'|'High risk';d3MissingData:'Low risk'|'Some concerns'|'High risk';d4Measurement:'Low risk'|'Some concerns'|'High risk';d5Selection:'Low risk'|'Some concerns'|'High risk'}):Rob2EvaluationResult{const m={D1:d.d1Randomisation,D2:d.d2Deviations,D3:d.d3MissingData,D4:d.d4Measurement,D5:d.d5Selection};const domainEvaluations=ROB2_DOMAINS.map(([domainId,domainTitle,signallingItemsSummary])=>({domainId,domainTitle,riskOfBias:m[domainId as keyof typeof m],signallingItemsSummary}));const o=overallRisk(domainEvaluations.map(x=>x.riskOfBias));return{variant:d.variant??'parallel-group',domainEvaluations,overallRiskOfBias:o,phase3OverallRiskOfBias:o,algorithmRationale:'RoB 2 er domenebasert på utfallsnivå; ingen numerisk totalscore.'};}}
export class GradeAssessmentEngine{public static evaluateOutcome(input:{outcomeName:string;studyDesign:string;riskOfBias:string|number;inconsistency:string|number;indirectness:string|number;imprecision:string|number;publicationBias:string|number;largeEffect?:string|number;doseResponse?:string|number;opposingConfounders?:string|number;finalCertainty?:GradeCertaintyEvaluation['finalCertainty'];certaintyRationale?:string}):GradeCertaintyEvaluation{if(!input.outcomeName.trim())throw new Error('GRADE outcomeName er påkrevd.');const down=(v:string|number)=>{const n=Number(v);if(![-2,-1,0].includes(n))throw new Error('GRADE downgrade judgments must be 0, -1 or -2.');return n as 0|-1|-2;};const up=(v:string|number|undefined)=>{const n=Number(v??0);if(![0,1].includes(n))throw new Error('GRADE upgrade adjustment must be 0 or 1.');return n as 0|1;};const large=(v:string|number|undefined)=>{const n=Number(v??0);if(![0,1,2].includes(n))throw new Error('GRADE large-effect adjustment must be 0, 1 or 2.');return n as 0|1|2;};const studyDesign=input.studyDesign.trim().toUpperCase()==='RCT'?'RCT':'Observational';const downgradeFactors={riskOfBias:down(input.riskOfBias),inconsistency:down(input.inconsistency),indirectness:down(input.indirectness),imprecision:down(input.imprecision),publicationBias:down(input.publicationBias)},upgradeFactors={largeEffect:large(input.largeEffect),doseResponse:up(input.doseResponse),opposingConfounders:up(input.opposingConfounders)};const level=Math.max(1,Math.min(4,(studyDesign==='RCT'?4:2)+Object.values(downgradeFactors).reduce((a,b)=>a+b,0)+upgradeFactors.largeEffect+upgradeFactors.doseResponse+upgradeFactors.opposingConfounders));const finalCertainty:GradeCertaintyEvaluation['finalCertainty']=level===4?'High':level===3?'Moderate':level===2?'Low':'Very Low';if(input.finalCertainty&&!input.certaintyRationale?.trim())throw new Error('Eksplisitt GRADE-final certainty krever begrunnelse.');return{outcomeName:input.outcomeName.trim(),studyDesign,initialCertainty:studyDesign==='RCT'?'High':'Low',downgradeFactors,upgradeFactors,finalCertainty:input.finalCertainty??finalCertainty,certaintyRationale:input.certaintyRationale?.trim()||'Endelig GRADE judgment skal dokumenteres eksplisitt av forskeren.'};}}
export class CaspAssessmentEngine{public static evaluateQualitative(r:Record<number,'Yes'|'Can’t tell'|'No'>):CaspQualitativeResult{const k=Object.keys(r).map(Number).sort((a,b)=>a-b);if(k.length!==10||k.some((v,n)=>v!==n+1))throw new Error('CASP qualitative appraisal requires exactly 10 questions.');const issues=k.filter(n=>r[n]!=='Yes').map(n=>`Spørsmål ${n} er ikke bekreftet Ja.`);return{screeningQuestionsPassed:r[1]==='Yes'&&r[2]==='Yes',methodologicalRigorNotes:issues.join(' ')||'Alle 10 CASP-spørsmål er eksplisitt bekreftet Ja.',isValuableLocally:r[10]==='Yes',qualitativeSummary:'CASP vurderes kvalitativt; ingen totalscore beregnes.'};}}
export class GradeCerqualAssessmentEngine{public static evaluateFinding(i:{reviewFinding:string;methodologicalLimitations:CerqualConcern;coherence:CerqualConcern;adequacyOfData:CerqualConcern;relevance:CerqualConcern;overallConfidence?:GradeCerqualEvaluationResult['overallConfidence'];confidenceExplanation?:string;methodologicalNote?:string}):GradeCerqualEvaluationResult{if(!i.reviewFinding.trim())throw new Error('CERQual-funn må beskrives.');const components={methodologicalLimitations:i.methodologicalLimitations,coherence:i.coherence,adequacyOfData:i.adequacyOfData,relevance:i.relevance};if(Object.values(components).some(v=>!v))throw new Error('CERQual krever eksplisitt judgment for alle fire komponenter.');return{reviewFinding:i.reviewFinding.trim(),components,overallConfidence:i.overallConfidence??'High confidence',confidenceExplanation:i.confidenceExplanation?.trim()||'CERQual-confidence fastsettes eksplisitt og skal ikke summeres automatisk.',methodologicalNote:i.methodologicalNote?.trim()||'CERQual skal ikke reduseres til en automatisk totalscore.'};}}
export class ReportingStandardNoticeEngine{public static readonly REPORTING_GUIDELINES=[{id:'consort',name:'CONSORT 2010',target:'RCT'},{id:'strobe',name:'STROBE',target:'Observasjonsstudier'},{id:'prisma',name:'PRISMA 2020',target:'Systematiske oversikter'},{id:'stard',name:'STARD 2015',target:'Diagnostiske studier'},{id:'tripod',name:'TRIPOD',target:'Prediksjonsmodeller'},{id:'care',name:'CARE',target:'Kasusrapporter'},{id:'coreq',name:'COREQ',target:'Kvalitativ forskning'},{id:'srqr',name:'SRQR',target:'Kvalitativ forskning'},{id:'squire',name:'SQUIRE 2.0',target:'Kvalitetsforbedring'},{id:'cheers',name:'CHEERS 2022',target:'Helseøkonomi'},{id:'right',name:'RIGHT',target:'Retningslinjer'}];public static getMethodologicalNotice(id:string){return`METODISK SKILLE: ${id.toUpperCase()} er en rapporteringsstandard og ikke et risikovurderingsverktøy eller en samlet kvalitetsscore.`;}}
export class Amstar2RatingService{public static readonly STANDARD_CRITICAL_DOMAINS=[2,4,7,9,11,13,15];public static evaluateStandard(i:Record<number,string>){return Amstar2AssessmentEngine.evaluate(i);}public static evaluateCustomAdaptation(i:Record<number,string>,d:number[],r:string){if(!r.trim())throw new Error('Tilpasningsbegrunnelse er påkrevd.');return{...Amstar2AssessmentEngine.evaluate(i),adaptationType:'REVIEW_SPECIFIC_ADAPTATION' as const,customCriticalDomains:d,adaptationRationale:r.trim()};}public static validateInput(i:Record<number,string>,criticalDomains:number[]=this.STANDARD_CRITICAL_DOMAINS){const errors:string[]=[];if(Object.keys(i).length!==16)errors.push('AMSTAR 2 krever 16 items.');for(let n=1;n<=16;n++)if(!['Yes','Partial Yes','No','No meta-analysis conducted'].includes(i[n]))errors.push(`Ugyldig/manglende Item ${n}.`);if(criticalDomains.length!==7||criticalDomains.some((d,n)=>d!==this.STANDARD_CRITICAL_DOMAINS[n]))errors.push('Kritiske domener avviker fra standard.');return{isValid:errors.length===0,errors};}}
export class Agree2ScoringService{public static readonly DOMAINS=Agree2AssessmentEngine.DOMAINS;public static evaluate(r:Record<number,number>){return Agree2AssessmentEngine.evaluateDomainScores(r);}public static calculateDomainScores(r:Record<number,number>){return Agree2AssessmentEngine.evaluateDomainScores(r).domainScores;}public static validateRatings(r:Record<number,number>){const errors:string[]=[];for(let n=1;n<=23;n++){const v=r[n];if(!Number.isInteger(v)||v<1||v>7)errors.push(`Ugyldig eller manglende AGREE II Item ${n}.`);}return{isValid:errors.length===0,errors};}}
export class CaspValidationService{public static evaluateQualitative(r:Record<number,'Yes'|'Can’t tell'|'No'>){return CaspAssessmentEngine.evaluateQualitative(r);}public static validateQualitativeInput(r:Record<number,string>){const errors:string[]=[];for(let n=1;n<=10;n++)if(!['Yes','Can’t tell','No'].includes(r[n]))errors.push(`Ugyldig/manglende CASP Item ${n}.`);return{isValid:errors.length===0,errors};}public static getNonOfficialNumericIndicatorNotice(){return'CASP har ingen offisielt validert numerisk totalscore.';}}
export class JbiValidationService{public static evaluate(i:{questionId:number;status:string;justification?:string}[]){return JbiQualitativeAssessmentEngine.evaluate(i);}public static validateInput(i:{questionId:number;status:string;justification?:string}[]){const errors:string[]=[];if(i.length!==10)errors.push('JBI Qualitative krever 10 items.');const ids=i.map(x=>x.questionId);if(new Set(ids).size!==10||ids.some(id=>id<1||id>10))errors.push('JBI question IDs må være unike 1-10.');return{isValid:errors.length===0,errors};}}
export class Rob2ValidationService{public static evaluate(i:Parameters<typeof Rob2AssessmentEngine.evaluate>[0]){return Rob2AssessmentEngine.evaluate(i);}}
export class GradeCertaintyService{public static evaluateOutcome(i:Parameters<typeof GradeAssessmentEngine.evaluateOutcome>[0]){return GradeAssessmentEngine.evaluateOutcome(i);}}
export class GradeCerqualValidationService{public static evaluateFinding(i:Parameters<typeof GradeCerqualAssessmentEngine.evaluateFinding>[0]){return GradeCerqualAssessmentEngine.evaluateFinding(i);}}
export class RobinsIAssessmentEngine{public static evaluate(i:Record<string,'Low risk'|'Moderate risk'|'Serious risk'|'Critical risk'|'No information'>){requireExactKeys(i,[...ROBINSI_DOMAINS],'ROBINS-I');const values=ROBINSI_DOMAINS.map(k=>i[k]);const overallRiskOfBias=values.some(v=>v==='Critical risk')?'Critical risk':values.some(v=>v==='Serious risk')?'Serious risk':values.some(v=>v==='Moderate risk')?'Moderate risk':values.some(v=>v==='No information')?'No information':'Low risk';return{domainEvaluations:ROBINSI_DOMAINS.map(domainId=>({domainId,domainTitle:domainId,riskOfBias:i[domainId]})),overallRiskOfBias,rationale:'ROBINS-I vurderes domenevis uten numerisk totalscore.'};}}
export class RobisAssessmentEngine{public static evaluate(i:{phase2Domains:Record<string,string>}){requireExactKeys(i.phase2Domains,[...ROBIS_DOMAINS],'ROBIS');const v=ROBIS_DOMAINS.map(k=>i.phase2Domains[k]),overallRiskOfBias=v.some(x=>riskRank(x)>=3)?'High risk of bias':v.some(x=>riskRank(x)===2)?'Some concerns':'Low risk of bias';return{overallRiskOfBias,phase3OverallRiskOfBias:overallRiskOfBias,phase2Domains:i.phase2Domains,rationale:'ROBIS fase 2 og samlet judgment uten totalscore.'};}}
export class Quadas2AssessmentEngine{public static evaluate(i:Record<string,string>){requireExactKeys(i,[...QUADAS_ROB,...QUADAS_APP],'QUADAS-2');const riskOfBiasDomains=QUADAS_ROB.map(domainId=>({domainId,domainName:domainId,riskOfBias:i[domainId]})),applicabilityConcerns=QUADAS_APP.map(domainId=>({domainId,domainName:domainId,concerns:i[domainId]}));return{riskOfBiasDomains,applicabilityConcerns,summaryVerdict:overallRisk(riskOfBiasDomains.map(x=>x.riskOfBias))==='High risk'||applicabilityConcerns.some(x=>concernRank(x.concerns)>=2)?'Metodiske bekymringer identifisert.':'Ingen høye bekymringer identifisert.',methodologicalNote:'QUADAS-2 skiller RoB fra applicability concerns.'};}}
export class QuipsAssessmentEngine{public static evaluate(i:Record<string,string>){requireExactKeys(i,[...QUIPS_DOMAINS],'QUIPS');return{domains:QUIPS_DOMAINS.map(id=>({id,name:id,risk:i[id]})),overallRiskOfBias:overallRisk(QUIPS_DOMAINS.map(id=>i[id])),methodologicalNote:'QUIPS er for prognostiske faktorer og har ingen totalscore.'};}}
export class ProbastAssessmentEngine{public static evaluate(i:Record<string,string>){requireExactKeys(i,[...PROBAST_ROB,...PROBAST_APP],'PROBAST');const riskOfBiasDomains=PROBAST_ROB.map(domainId=>({domainId,domainName:domainId,riskOfBias:i[domainId]})),applicabilityDomains=PROBAST_APP.map(domainId=>({domainId,domainName:domainId,concerns:i[domainId]}));return{riskOfBiasDomains,applicabilityDomains,overallRiskOfBias:overallRisk(riskOfBiasDomains.map(x=>x.riskOfBias)),overallApplicabilityConcerns:applicabilityDomains.some(x=>concernRank(x.concerns)>=2)?'High concern':applicabilityDomains.some(x=>concernRank(x.concerns)===1)?'Some concern':'Low concern',methodologicalNote:'PROBAST skiller RoB- og applicability-domener.'};}}
export class MmatAssessmentEngine{public static evaluate(i:{screening1ClearQuestion:boolean;screening2DataAddressQuestion:boolean;selectedCategory:number;categoryResponses:Array<{itemNumber:number;response:string}>}){if(!i.screening1ClearQuestion||!i.screening2DataAddressQuestion)return{screeningPassed:false,selectedCategory:i.selectedCategory,responses:i.categoryResponses,methodologicalSummary:'Screening må være oppfylt før kategorivurdering.',methodologicalWarning:'MMAT forbyr samlet numerisk poengsum.'};if(i.selectedCategory<1||i.selectedCategory>5)throw new Error('MMAT selectedCategory må være 1-5.');const n=i.categoryResponses.map(x=>x.itemNumber).sort((a,b)=>a-b);if(n.length!==5||n.some((v,x)=>v!==x+1))throw new Error('MMAT-kategorien krever 5 items.');return{screeningPassed:true,selectedCategory:i.selectedCategory,responses:[...i.categoryResponses],methodologicalSummary:'Beskrivende MMAT-profil for valgt studiedesign.',methodologicalWarning:'MMAT forbyr samlet numerisk poengsum.'};}}
export class Cfir2AssessmentEngine{public static evaluateDeterminants(c:Cfir2ConstructItem[]):Cfir2EvaluationResult{const facilitatorsCount=c.filter(x=>x.classification.startsWith('Facilitator')).length,barriersCount=c.filter(x=>x.classification.startsWith('Barrier')).length,neutralCount=c.length-facilitatorsCount-barriersCount,domainSummaries=Array.from(new Set(c.map(x=>x.domainId))).map(domainId=>({domainId,constructs:c.filter(x=>x.domainId===domainId).length})),overallImplementationProfile=c.length===0?'Insufficient evidence':barriersCount>facilitatorsCount?'Challenging':facilitatorsCount>barriersCount?'Favorable':'Mixed';return{totalConstructsAssessed:c.length,facilitatorsCount,barriersCount,neutralCount,domainSummaries,overallImplementationProfile,methodologicalNote:'CFIR 2.0 er et determinantrammeverk uten universell kvalitetsscore.'};}}
export class KtaAssessmentEngine{public static evaluateRoadmap(p:KtaPhaseStatus[]):KtaEvaluationResult{const completedCount=p.filter(x=>x.status==='COMPLETED').length,blockedCount=p.filter(x=>x.status==='BLOCKED').length;return{phases:[...p],completedCount,blockedCount,overallStatus:blockedCount?'BLOCKED':completedCount===0?'NOT_STARTED':completedCount===p.length?'COMPLETED':'IN_PROGRESS',methodologicalNote:'KTA er en prosessmodell uten universell kvalitetspoengsum.'};}}
export class Prisma2020ReportingEngine{public static evaluateReporting(r:Record<number,'Yes'|'Partial'|'No'|'Not applicable'>):Prisma2020EvaluationResult{const k=Object.keys(r).map(Number).sort((a,b)=>a-b);if(k.length===0||k.some((v,n)=>v!==n+1))throw new Error('PRISMA 2020 item IDs må være sekvensielle.');const v=Object.values(r),reported=v.filter(x=>x==='Yes').length,partial=v.filter(x=>x==='Partial').length;return{checklistItemsEvaluated:v.length,sectionSummaries:[],overallReportingCompleteness:Number((((reported+partial)/v.length)*100).toFixed(2)),flowDiagramComplete:false,searchStrategyTransparent:false,methodologicalNotice:'PRISMA 2020 er en rapporteringsstandard; flow diagram, søkestrategi og inkludering skal vurderes eksplisitt.'};}}
export type Cfir2ConstructItemAlias=Cfir2ConstructItem;
export type WhoEtdCriteriaInputAlias=WhoEtdCriteriaInput;
export class WhoEtdAssessmentEngine{public static evaluateEtD(i:WhoEtdCriteriaInput):WhoEtdEvaluationResult{return{guidelineQuestion:i.guidelineQuestion,targetPopulation:i.targetPopulation,intervention:i.intervention,comparison:i.comparison,recommendationType:'Krever eksplisitt EtD-judgment',strengthRationale:'EtD-resultatet skal bygge på eksplisitt vurdering av relevante kriterier.',detailedCriteriaAudit:Object.entries(i).map(([criterion,value])=>({criterion,present:Boolean(String(value??'').trim())})),implementationConsiderations:[],monitoringAndEvaluation:[],methodologicalStandard:'WHO EtD framework'};}}
export const IMPLEMENTED_INSTRUMENT_IDS=new Set<string>(['amstar-2','agree-ii','jbi-qualitative-2017','rob-2','robins-i','robins-e','robis','quadas-2','quips','probast','mmat-2018','grade','grade-cerqual','prisma-2020','cfir-2','kta',...Array.from(CASP_IDS)]);
export function isInstrumentImplemented(inst:AppraisalInstrument){return IMPLEMENTED_INSTRUMENT_IDS.has(inst.id);}
export class RobinsIValidationService{public static evaluate(i:Parameters<typeof RobinsIAssessmentEngine.evaluate>[0]){return RobinsIAssessmentEngine.evaluate(i);}}
export class RobisValidationService{public static evaluate(i:Parameters<typeof RobisAssessmentEngine.evaluate>[0]){return RobisAssessmentEngine.evaluate(i);}}
export class Quadas2ValidationService{public static evaluate(i:Parameters<typeof Quadas2AssessmentEngine.evaluate>[0]){return Quadas2AssessmentEngine.evaluate(i);}}
export class QuipsValidationService{public static evaluate(i:Parameters<typeof QuipsAssessmentEngine.evaluate>[0]){return QuipsAssessmentEngine.evaluate(i);}}
export class ProbastValidationService{public static evaluate(i:Parameters<typeof ProbastAssessmentEngine.evaluate>[0]){return ProbastAssessmentEngine.evaluate(i);}}
export class MmatValidationService{public static evaluate(i:Parameters<typeof MmatAssessmentEngine.evaluate>[0]){return MmatAssessmentEngine.evaluate(i);}}
export class Prisma2020ValidationService{public static evaluateReporting(i:Record<number,'Yes'|'Partial'|'No'|'Not applicable'>){return Prisma2020ReportingEngine.evaluateReporting(i);}}
