import { AppraisalInstrument, WhoEtdCriteriaInput, WhoEtdEvaluationResult } from '../types';
import { MASTER_INSTRUMENTS_REGISTRY } from '../data/masterRegistry';

export interface Amstar2EvaluationResult { criticalFlawsCount:number; nonCriticalFlawsCount:number; criticalFlawItems:number[]; overallConfidence:'High'|'Moderate'|'Low'|'Critically Low'; confidenceRationale:string; methodologicalWarning?:string; }
export interface Agree2DomainScore { domainId:number; domainName:string; itemIds:number[]; obtainedScore:number; minPossibleScore:number; maxPossibleScore:number; standardizedScorePercent:number; }
export interface Agree2EvaluationResult { domainScores:Agree2DomainScore[]; overallRecommendation:'Anbefales'|'Anbefales med modifikasjoner'|'Anbefales ikke'; recommendationRationale:string; methodologicalNote:string; }
export interface Rob2DomainEvaluation { domainId:string; domainTitle:string; riskOfBias:'Low risk'|'Some concerns'|'High risk'; signallingItemsSummary:string; }
export interface Rob2EvaluationResult { variant:'parallel-group'|'cluster-randomised'|'crossover'; domainEvaluations:Rob2DomainEvaluation[]; overallRiskOfBias:'Low risk'|'Some concerns'|'High risk'; phase3OverallRiskOfBias:'Low risk'|'Some concerns'|'High risk'; algorithmRationale:string; }
export interface GradeCertaintyEvaluation { outcomeName:string; studyDesign:'RCT'|'Observational'; initialCertainty:'High'|'Low'; downgradeFactors:{riskOfBias:0|-1|-2;inconsistency:0|-1|-2;indirectness:0|-1|-2;imprecision:0|-1|-2;publicationBias:0|-1|-2}; upgradeFactors:{largeEffect:0|1|2;doseResponse:0|1;opposingConfounders:0|1}; finalCertainty:'High'|'Moderate'|'Low'|'Very Low'; certaintyRationale:string; }
export interface CaspQualitativeResult { screeningQuestionsPassed:boolean; methodologicalRigorNotes:string; isValuableLocally:boolean; qualitativeSummary:string; }
export type CerqualConcern = 'No or very minor concerns'|'Minor concerns'|'Moderate concerns'|'Serious concerns';
export interface GradeCerqualComponentEvaluation { methodologicalLimitations:CerqualConcern; coherence:CerqualConcern; adequacyOfData:CerqualConcern; relevance:CerqualConcern; }
export interface GradeCerqualEvaluationResult { reviewFinding:string; components:GradeCerqualComponentEvaluation; overallConfidence:'High confidence'|'Moderate confidence'|'Low confidence'|'Very low confidence'; confidenceExplanation:string; methodologicalNote:string; }
export interface Prisma2020SectionSummary { sectionName:string; totalItems:number; reportedCount:number; partialCount:number; notReportedCount:number; notApplicableCount:number; adherencePercentage:number; }
export interface Prisma2020EvaluationResult { checklistItemsEvaluated:number; sectionSummaries:Prisma2020SectionSummary[]; overallReportingCompleteness:number; flowDiagramComplete:boolean; searchStrategyTransparent:boolean; methodologicalNotice:string; }
export interface Cfir2ConstructItem { domainId:'innovation'|'outer_setting'|'inner_setting'|'individuals'|'process'; domainName:string; constructId:string; constructName:string; classification:'Facilitator (+2)'|'Facilitator (+1)'|'Neutral (0)'|'Barrier (-1)'|'Barrier (-2)'|'Not applicable'; contextualEvidence:string; }
export interface Cfir2EvaluationResult { totalConstructsAssessed:number; facilitatorsCount:number; barriersCount:number; neutralCount:number; domainSummaries:Record<string,unknown>[]; overallImplementationProfile:'Favorable'|'Mixed'|'Challenging'|'Insufficient evidence'; methodologicalNote:string; }
export interface KtaPhaseStatus { phaseId:string; phaseName:string; status:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'; evidence:string; barriers:string[]; facilitators:string[]; }
export interface KtaEvaluationResult { phases:KtaPhaseStatus[]; completedCount:number; blockedCount:number; overallStatus:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'; methodologicalNote:string; }

const AMSTAR_CRITICAL = new Set([2,4,7,9,11,13,15]);
const ROB2_DOMAINS = [['D1','Randomiseringsprosess','Sekvensgenerering og allokeringsskjuling'],['D2','Avvik fra intenderte intervensjoner','Blindingsintegritet og intervensjonsavvik'],['D3','Manglende utfallsdata','Frafall, manglende data og håndtering'],['D4','Måling av utfall','Utfallsdefinisjon, målemetode og blinding'],['D5','Valg av rapportert resultat','Analyseplan og selektiv rapportering']] as const;
const ROBINSI_DOMAINS = ['D1','D2','D3','D4','D5','D6','D7'] as const;
const ROBIS_DOMAINS = ['domain1Eligibility','domain2Identification','domain3DataCollection','domain4Synthesis'] as const;
const QUADAS_ROB = ['robPatientSelection','robIndexTest','robReferenceStandard','robFlowTiming'] as const;
const QUADAS_APP = ['appPatientSelection','appIndexTest','appReferenceStandard'] as const;
const QUIPS_DOMAINS = ['participation','attrition','factorMeasurement','outcomeMeasurement','confounding','statisticalAnalysis'] as const;
const PROBAST_ROB = ['participantsRoB','predictorsRoB','outcomeRoB','analysisRoB'] as const;
const PROBAST_APP = ['participantsApplicability','predictorsApplicability','outcomeApplicability'] as const;

function requireExactKeys(record:Record<string,unknown>,keys:string[],name:string):void{const present=Object.keys(record).sort(),expected=[...keys].sort();if(present.length!==expected.length||present.some((v,i)=>v!==expected[i]))throw new Error(`${name} krever nøyaktig ${expected.length} domener.`);}
function rankRisk(value:string):number{const v=value.toLowerCase();if(v.includes('critical')||v.includes('very high'))return 4;if(v.includes('high')||v.includes('serious'))return 3;if(v.includes('moderate')||v.includes('some concerns'))return 2;if(v.includes('low'))return 1;return 0;}
function rankConcern(value:string):number{const v=value.toLowerCase();if(v.includes('serious'))return 3;if(v.includes('moderate'))return 2;if(v.includes('minor'))return 1;return 0;}
function overallRisk(values:string[]):'Low risk'|'Some concerns'|'High risk'{const max=Math.max(...values.map(rankRisk),0);return max>=3?'High risk':max===2?'Some concerns':'Low risk';}
function normalizeAnswer(value:string):string{return value.trim().toLowerCase();}

export class Amstar2AssessmentEngine{public static evaluate(itemResponses:Record<number,string>):Amstar2EvaluationResult{const keys=Object.keys(itemResponses).map(Number).sort((a,b)=>a-b);if(keys.length!==16||keys.some((v,i)=>v!==i+1))throw new Error('AMSTAR 2 krever nøyaktig 16 items.');const allowed=new Set(['Yes','Partial Yes','No','No meta-analysis conducted']);const criticalFlawItems:number[]=[];let nonCriticalFlawsCount=0;for(let i=1;i<=16;i++){const answer=itemResponses[i];if(!allowed.has(answer))throw new Error(`Ugyldig AMSTAR 2-svar i Item ${i}.`);if(answer==='No'){if(AMSTAR_CRITICAL.has(i))criticalFlawItems.push(i);else nonCriticalFlawsCount++;}}const criticalFlawsCount=criticalFlawItems.length;const overallConfidence=criticalFlawsCount===0?(nonCriticalFlawsCount<=1?'High':'Moderate'):criticalFlawsCount===1?'Low':'Critically Low';return{criticalFlawsCount,nonCriticalFlawsCount,criticalFlawItems,overallConfidence,confidenceRationale:`AMSTAR 2: ${criticalFlawsCount} kritiske og ${nonCriticalFlawsCount} ikke-kritiske mangler.`,methodologicalWarning:'AMSTAR 2 skal ikke reduseres til en numerisk totalscore.'};}}

export class Agree2AssessmentEngine{public static readonly DOMAINS=[{id:1,name:'Omfang og formål',items:[1,2,3]},{id:2,name:'Interessentinvolvering',items:[4,5,6]},{id:3,name:'Metodisk stringens',items:[7,8,9,10,11,12,13,14]},{id:4,name:'Klarhet',items:[15,16,17]},{id:5,name:'Anvendelighet',items:[18,19,20,21]},{id:6,name:'Redaksjonell uavhengighet',items:[22,23]}] as const;public static evaluateDomainScores(ratings:Record<number,number>,reviewersCount=1):Agree2EvaluationResult{if(reviewersCount<1||!Number.isInteger(reviewersCount))throw new Error('reviewersCount must be a positive integer.');const keys=Object.keys(ratings).map(Number).sort((a,b)=>a-b);if(keys.length!==23||keys.some((v,i)=>v!==i+1))throw new Error('AGREE II krever nøyaktig 23 items.');const invalid=keys.find(i=>!Number.isInteger(ratings[i])||ratings[i]<1||ratings[i]>7);if(invalid!==undefined)throw new Error(`Ugyldig AGREE II-skår i Item ${invalid}.`);const domainScores=this.DOMAINS.map(d=>{const itemIds=[...d.items],obtainedScore=itemIds.reduce((s,id)=>s+ratings[id],0),minPossibleScore=itemIds.length,maxPossibleScore=itemIds.length*7;return{domainId:d.id,domainName:d.name,itemIds,obtainedScore,minPossibleScore,maxPossibleScore,standardizedScorePercent:Number((((obtainedScore-minPossibleScore)/(maxPossibleScore-minPossibleScore))*100).toFixed(2))};});return{domainScores,overallRecommendation:'Anbefales med modifikasjoner',recommendationRationale:'AGREE II gir ikke en beregnet samlet anbefaling fra domeneskårene. Overordnet anbefaling må fastsettes eksplisitt av granskeren.',methodologicalNote:'AGREE II skal rapporteres domenespesifikt. Ingen samlet gjennomsnittsskår eller automatisk anbefaling beregnes.'};}}

export class JbiQualitativeAssessmentEngine{public static evaluate(items:{questionId:number;status:string;justification?:string}[]){const ordered=[...items].sort((a,b)=>a.questionId-b.questionId);if(ordered.length!==10||ordered.some((x,i)=>x.questionId!==i+1))throw new Error('JBI Qualitative krever nøyaktig 10 unike items.');const normalized=ordered.map(x=>normalizeAnswer(x.status));const valid=new Set(['ja','nei','uklart','ikke relevant','yes','no','unclear','not applicable']);if(normalized.some(v=>!valid.has(v)))throw new Error('Ugyldig JBI-svar.');const strengths=ordered.filter(x=>['ja','yes'].includes(normalizeAnswer(x.status))),weaknesses=ordered.filter(x=>['nei','no'].includes(normalizeAnswer(x.status))),unresolved=ordered.filter(x=>['uklart','unclear'].includes(normalizeAnswer(x.status))),criticalWeaknesses=weaknesses;const identifiedDefects=[...weaknesses.map(x=>`Kriterium ${x.questionId}: Ikke oppfylt (${x.justification?.trim()||'Ingen begrunnelse oppgitt'})`),...unresolved.map(x=>`Kriterium ${x.questionId}: Uklart (${x.justification?.trim()||'Krever eksplisitt avklaring'})`)];let verdict:'Inkluder'|'Ekskluder'|'Vurder videre'|'Søk mer informasjon'='Vurder videre';let rationale='Helhetlig kvalitativ JBI-vurdering kreves.';if(unresolved.length>0){verdict='Søk mer informasjon';rationale='Minst ett JBI-kriterium er uavklart og må avklares før endelig beslutning.';}else if(weaknesses.length>0){verdict='Vurder videre';rationale='Metodiske svakheter er identifisert. Endelig beslutning krever eksplisitt forskerbegrunnelse.';}else if(strengths.length===10){verdict='Inkluder';rationale='Alle ti JBI-kriterier er besvart Ja. Dette er en kvalitativ forskervurdering, ikke en numerisk cut-off.';}return{jaCount:strengths.length,neiCount:weaknesses.length,uklartCount:unresolved.length,ikkeRelevantCount:ordered.filter(x=>['ikke relevant','not applicable'].includes(normalizeAnswer(x.status))).length,verdict,rationale,identifiedDefects,criticalItemsDefects:criticalWeaknesses.map(x=>`Kriterium ${x.questionId}: ${x.justification?.trim()||'Ikke oppfylt'}`),methodologicalNote:'JBI Qualitative (2017) har ingen rigid numerisk cut-off; endelig beslutning er kvalitativ og krever eksplisitt faglig begrunnelse.'};}}

export class Rob2AssessmentEngine{public static evaluate(domainRisks:{variant?:'parallel-group'|'cluster-randomised'|'crossover';d1Randomisation:'Low risk'|'Some concerns'|'High risk';d2Deviations:'Low risk'|'Some concerns'|'High risk';d3MissingData:'Low risk'|'Some concerns'|'High risk';d4Measurement:'Low risk'|'Some concerns'|'High risk';d5Selection:'Low risk'|'Some concerns'|'High risk'}):Rob2EvaluationResult{const normalized={D1:domainRisks.d1Randomisation,D2:domainRisks.d2Deviations,D3:domainRisks.d3MissingData,D4:domainRisks.d4Measurement,D5:domainRisks.d5Selection};const list=ROB2_DOMAINS.map(([id,title,summary])=>({domainId:id,domainTitle:title,riskOfBias:normalized[id as keyof typeof normalized],signallingItemsSummary:summary}));const overall=overallRisk(list.map(x=>x.riskOfBias));return{variant:domainRisks.variant??'parallel-group',domainEvaluations:list,overallRiskOfBias:overall,phase3OverallRiskOfBias:overall,algorithmRationale:'RoB 2 er utfallsnivåbasert og skal vurderes med de offisielle signalspørsmålene. Denne API-en mottar allerede domenejudgments; ingen numerisk totalscore beregnes.'};}}

export class GradeAssessmentEngine{public static evaluateOutcome(input:{outcomeName:string;studyDesign:string;riskOfBias:string|number;inconsistency:string|number;indirectness:string|number;imprecision:string|number;publicationBias:string|number;largeEffect?:string|number;doseResponse?:string|number;opposingConfounders?:string|number;finalCertainty?:GradeCertaintyEvaluation['finalCertainty'];certaintyRationale?:string}):GradeCertaintyEvaluation{if(!input.outcomeName.trim())throw new Error('GRADE outcomeName er påkrevd.');const toDowngrade=(v:string|number):0|-1|-2=>{const n=Number(v);if(![0,-1,-2].includes(n))throw new Error('GRADE downgrade judgments must be 0, -1 or -2.');return n as 0|-1|-2;};const toLarge=(v:string|number|undefined):0|1|2=>{const n=Number(v??0);if(![0,1,2].includes(n))throw new Error('GRADE large-effect adjustment must be 0, 1 or 2.');return n as 0|1|2;};const toBinary=(v:string|number|undefined):0|1=>{const n=Number(v??0);if(![0,1].includes(n))throw new Error('GRADE upgrade adjustment must be 0 or 1.');return n as 0|1;};const studyDesign:GradeCertaintyEvaluation['studyDesign']=input.studyDesign.trim().toUpperCase()==='RCT'?'RCT':'Observational';const factors={riskOfBias:toDowngrade(input.riskOfBias),inconsistency:toDowngrade(input.inconsistency),indirectness:toDowngrade(input.indirectness),imprecision:toDowngrade(input.imprecision),publicationBias:toDowngrade(input.publicationBias)},upgrades={largeEffect:toLarge(input.largeEffect),doseResponse:toBinary(input.doseResponse),opposingConfounders:toBinary(input.opposingConfounders)};const initial=studyDesign==='RCT'?4:2,downgrade=Math.max(-3,factors.riskOfBias+factors.inconsistency+factors.indirectness+factors.imprecision+factors.publicationBias),score=Math.max(1,Math.min(4,initial+downgrade+upgrades.largeEffect+upgrades.doseResponse+upgrades.opposingConfounders)),calculated:GradeCertaintyEvaluation['finalCertainty']=score===4?'High':score===3?'Moderate':score===2?'Low':'Very Low';if(input.finalCertainty&&!input.certaintyRationale?.trim())throw new Error('Eksplisitt GRADE-final certainty krever begrunnelse.');return{outcomeName:input.outcomeName.trim(),studyDesign,initialCertainty:studyDesign==='RCT'?'High':'Low',downgradeFactors:factors,upgradeFactors:upgrades,finalCertainty:input.finalCertainty??calculated,certaintyRationale:input.certaintyRationale?.trim()||'Beregnet fra eksplisitte GRADE-domener; forsker må kontrollere og dokumentere endelig judgment.'};}}

export class CaspAssessmentEngine{public static evaluateQualitative(responses:Record<number,'Yes'|'Can’t tell'|'No'>):CaspQualitativeResult{const keys=Object.keys(responses).map(Number).sort((a,b)=>a-b);if(keys.length!==10||keys.some((v,i)=>v!==i+1))throw new Error('CASP qualitative appraisal requires exactly 10 questions.');const screeningQuestionsPassed=responses[1]==='Yes'&&responses[2]==='Yes';const issues:string[]=[];for(const [q,label] of [[1,'forskningsmål'],[2,'kvalitativ metodologi'],[3,'forskningsdesign'],[4,'rekruttering'],[5,'datainnsamling'],[6,'forsker-deltaker-relasjon'],[7,'etikk'],[8,'dataanalyse'],[9,'funn'],[10,'forskningsverdi']] as const)if(responses[q]!=='Yes')issues.push(`Spørsmål ${q} (${label}) er ikke bekreftet Ja.`);return{screeningQuestionsPassed,methodologicalRigorNotes:issues.join(' ')||'Alle 10 CASP-spørsmål er eksplisitt besvart Ja.',isValuableLocally:responses[10]==='Yes',qualitativeSummary:'CASP er kvalitativt og skal ikke reduseres til en totalscore.'};}}

export class GradeCerqualAssessmentEngine{public static evaluateFinding(input:{reviewFinding:string;methodologicalLimitations:CerqualConcern;coherence:CerqualConcern;adequacyOfData:CerqualConcern;relevance:CerqualConcern;overallConfidence?:GradeCerqualEvaluationResult['overallConfidence'];confidenceExplanation?:string;methodologicalNote?:string}):GradeCerqualEvaluationResult{if(!input.reviewFinding.trim())throw new Error('CERQual-funn må beskrives.');const components={methodologicalLimitations:input.methodologicalLimitations,coherence:input.coherence,adequacyOfData:input.adequacyOfData,relevance:input.relevance};if(Object.values(components).some(v=>!v))throw new Error('CERQual krever eksplisitt judgment for alle fire komponenter.');if(!input.overallConfidence)throw new Error('CERQual krever eksplisitt overall confidence.');if(!input.confidenceExplanation?.trim())throw new Error('CERQual krever eksplisitt begrunnelse for overall confidence.');return{reviewFinding:input.reviewFinding.trim(),components,overallConfidence:input.overallConfidence,confidenceExplanation:input.confidenceExplanation.trim(),methodologicalNote:input.methodologicalNote?.trim()||'CERQual skal ikke reduseres til en automatisk totalscore.'};}}

export class ReportingStandardNoticeEngine{public static readonly REPORTING_GUIDELINES=[{id:'consort',name:'CONSORT 2010',target:'Randomiserte kontrollerte studier (RCT)'},{id:'strobe',name:'STROBE',target:'Observasjonsstudier'},{id:'prisma',name:'PRISMA 2020',target:'Systematiske kunnskapsoppsummeringer og metaanalyser'},{id:'stard',name:'STARD 2015',target:'Diagnostiske nøyaktighetsstudier'},{id:'tripod',name:'TRIPOD',target:'Prediksjonsmodellstudier'},{id:'care',name:'CARE',target:'Kasusrapporter'},{id:'coreq',name:'COREQ',target:'Kvalitative fokusgrupper og dybdeintervjuer'},{id:'srqr',name:'SRQR',target:'Kvalitativ forskning'},{id:'squire',name:'SQUIRE 2.0',target:'Kvalitetsforbedring'},{id:'cheers',name:'CHEERS 2022',target:'Helseøkonomiske evalueringer'},{id:'right',name:'RIGHT',target:'Kliniske retningslinjer'}];public static getMethodologicalNotice(guidelineId:string){return`METODISK SKILLE: ${guidelineId.toUpperCase()} er en rapporteringsstandard og ikke et risikovurderingsverktøy eller en samlet kvalitetsscore.`;}}

export class Amstar2RatingService{public static readonly STANDARD_CRITICAL_DOMAINS=[2,4,7,9,11,13,15];public static evaluateStandard(i:Record<number,string>){return Amstar2AssessmentEngine.evaluate(i);}public static evaluateCustomAdaptation(i:Record<number,string>,d:number[],r:string){if(!r.trim())throw new Error('Tilpasningsbegrunnelse er påkrevd.');const result=Amstar2AssessmentEngine.evaluate(i);return{...result,adaptationType:'REVIEW_SPECIFIC_ADAPTATION' as const,customCriticalDomains:d,adaptationRationale:r.trim()};}public static validateInput(i:Record<number,string>,criticalDomains:number[]=this.STANDARD_CRITICAL_DOMAINS){const errors:string[]=[];for(let n=1;n<=16;n++)if(!['Yes','Partial Yes','No','No meta-analysis conducted'].includes(i[n]))errors.push(`Ugyldig/manglende svar for Item ${n}.`);if(Object.keys(i).length!==16)errors.push(`Ugyldig antall items for AMSTAR 2: Mottok ${Object.keys(i).length}.`);if(criticalDomains.some(d=>!AMSTAR_CRITICAL.has(d)))errors.push('Kritiske domener avviker fra AMSTAR 2-standardsettet.');return{isValid:errors.length===0,errors};}}
export class Agree2ScoringService{public static readonly DOMAINS=Agree2AssessmentEngine.DOMAINS;public static evaluate(r:Record<number,number>,c=1){return Agree2AssessmentEngine.evaluateDomainScores(r,c);}public static calculateDomainScores(r:Record<number,number>,c=1){return Agree2AssessmentEngine.evaluateDomainScores(r,c).domainScores;}public static validateRatings(r:Record<number,number>){const errors:string[]=[];for(let i=1;i<=23;i++){const v=r[i];if(!Number.isInteger(v)||v<1||v>7)errors.push(`Ugyldig eller manglende AGREE II Item ${i}.`);}return{isValid:errors.length===0,errors};}}
export class CaspValidationService{public static evaluateQualitative(r:Record<number,'Yes'|'Can’t tell'|'No'>){return CaspAssessmentEngine.evaluateQualitative(r);}public static validateQualitativeInput(r:Record<number,string>){const errors:string[]=[];for(let i=1;i<=10;i++)if(!['Yes','Can’t tell','No'].includes(r[i]))errors.push(`Ugyldig/manglende CASP Item ${i}.`);return{isValid:errors.length===0,errors};}public static getNonOfficialNumericIndicatorNotice(){return'NON-OFFICIAL LOCAL INDICATOR: CASP har ingen offisielt validert numerisk totalscore.';}}
export class JbiValidationService{public static evaluate(i:{questionId:number;status:string;justification?:string}[]){return JbiQualitativeAssessmentEngine.evaluate(i);}public static validateInput(i:{questionId:number;status:string;justification?:string}[]){const errors:string[]=[];if(i.length!==10)errors.push(`JBI Qualitative krever nøyaktig 10 items. Mottok ${i.length}.`);const ids=i.map(x=>x.questionId);if(new Set(ids).size!==10||ids.some(id=>id<1||id>10))errors.push('JBI question IDs må være 1-10 og unike.');for(const x of i)if(!['Ja','Nei','Uklart','Ikke relevant','Yes','No','Unclear','Not applicable'].some(v=>v.toLowerCase()===String(x.status||'').toLowerCase()))errors.push(`Ugyldig JBI-svar for item ${x.questionId}.`);return{isValid:errors.length===0,errors};}}
export class Rob2ValidationService{public static evaluate(i:Parameters<typeof Rob2AssessmentEngine.evaluate>[0]){return Rob2AssessmentEngine.evaluate(i);}}
export class GradeCertaintyService{public static evaluateOutcome(i:Parameters<typeof GradeAssessmentEngine.evaluateOutcome>[0]){return GradeAssessmentEngine.evaluateOutcome(i);}}
export class GradeCerqualValidationService{public static evaluateFinding(i:Parameters<typeof GradeCerqualAssessmentEngine.evaluateFinding>[0]){return GradeCerqualAssessmentEngine.evaluateFinding(i);}}
export class RobinsIAssessmentEngine{public static evaluate(input:Record<string,'Low risk'|'Moderate risk'|'Serious risk'|'Critical risk'|'No information'>){requireExactKeys(input,[...ROBINSI_DOMAINS],'ROBINS-I');const values=ROBINSI_DOMAINS.map(k=>input[k]);const overall=values.some(v=>v==='Critical risk')?'Critical risk':values.some(v=>v==='Serious risk')?'Serious risk':values.some(v=>v==='Moderate risk')?'Moderate risk':values.some(v=>v==='No information')?'No information':'Low risk';return{domainEvaluations:ROBINSI_DOMAINS.map(domainId=>({domainId,domainTitle:domainId,riskOfBias:input[domainId]})),overallRiskOfBias:overall,rationale:'ROBINS-I krever særskilt judgment for alle syv biasdomener. Aggregert resultat viser dårligste registrerte kategori og brukes ikke som numerisk sum.'};}}
export class RobisAssessmentEngine{public static evaluate(input:{phase2Domains:Record<string,string>}){requireExactKeys(input.phase2Domains,[...ROBIS_DOMAINS],'ROBIS fase 2');const values=ROBIS_DOMAINS.map(k=>input.phase2Domains[k]);const high=values.some(v=>rankRisk(v)>=3),some=values.some(v=>rankRisk(v)===2),overallRiskOfBias=high?'High risk of bias':some?'Some concerns':'Low risk of bias';return{overallRiskOfBias,phase3OverallRiskOfBias:overallRiskOfBias,phase2Domains:input.phase2Domains,rationale:'ROBIS vurderes gjennom fase 2-domener og en eksplisitt samlet judgment; ingen prosent- eller totalscore beregnes.'};}}
export class Quadas2AssessmentEngine{public static evaluate(input:Record<string,string>){requireExactKeys(input,[...QUADAS_ROB,...QUADAS_APP],'QUADAS-2');const riskOfBiasDomains=QUADAS_ROB.map(domainId=>({domainId,domainName:domainId,riskOfBias:input[domainId]}));const applicabilityConcerns=QUADAS_APP.map(domainId=>({domainId,domainName:domainId,concerns:input[domainId]}));const robrisk=overallRisk(riskOfBiasDomains.map(d=>d.riskOfBias)),appMax=Math.max(...applicabilityConcerns.map(d=>rankConcern(d.concerns)),0);return{riskOfBiasDomains,applicabilityConcerns,summaryVerdict:robrisk==='High risk'||appMax>=2?'Metodiske bekymringer identifisert.':'Ingen høye bekymringer identifisert.',methodologicalNote:'QUADAS-2 skiller risiko for bias fra applicability concerns og skal ikke reduseres til en totalscore.'};}}
export class QuipsAssessmentEngine{public static evaluate(domains:Record<string,string>){requireExactKeys(domains,[...QUIPS_DOMAINS],'QUIPS');const values=QUIPS_DOMAINS.map(k=>domains[k]);return{domains:QUIPS_DOMAINS.map(id=>({id,name:id,risk:domains[id]})),overallRiskOfBias:overallRisk(values),methodologicalNote:'QUIPS vurderer risiko for bias i prognostiske faktorstudier og gir ingen samlet numerisk score.'};}}
export class ProbastAssessmentEngine{public static evaluate(input:Record<string,string>){requireExactKeys(input,[...PROBAST_ROB,...PROBAST_APP],'PROBAST');const riskOfBiasDomains=PROBAST_ROB.map(id=>({domainId:id,domainName:id,riskOfBias:input[id]}));const applicabilityDomains=PROBAST_APP.map(id=>({domainId:id,domainName:id,concerns:input[id]}));const overallRiskOfBias=overallRisk(riskOfBiasDomains.map(d=>d.riskOfBias));const appConcern=applicabilityDomains.some(d=>rankConcern(d.concerns)>=2)?'High concern':applicabilityDomains.some(d=>rankConcern(d.concerns)===1)?'Some concern':'Low concern';return{riskOfBiasDomains,applicabilityDomains,overallRiskOfBias,overallApplicabilityConcerns:appConcern,methodologicalNote:'PROBAST skiller fire RoB-domener fra tre applicability-domener.'};}}
export class MmatAssessmentEngine{public static evaluate(input:{screening1ClearQuestion:boolean;screening2DataAddressQuestion:boolean;selectedCategory:number;categoryResponses:Array<{itemNumber:number;response:string}>}){if(!input.screening1ClearQuestion||!input.screening2DataAddressQuestion)return{screeningPassed:false,selectedCategory:input.selectedCategory,responses:input.categoryResponses,methodologicalSummary:'Screening-spørsmålene må være oppfylt før kategorispesifikk vurdering.',methodologicalWarning:'MMAT skal ikke summeres til en numerisk totalscore.'};if(!Number.isInteger(input.selectedCategory)||input.selectedCategory<1||input.selectedCategory>5)throw new Error('MMAT selectedCategory må være 1-5.');const numbers=input.categoryResponses.map(x=>x.itemNumber).sort((a,b)=>a-b);if(numbers.length!==5||numbers.some((v,i)=>v!==i+1))throw new Error('MMAT-kategorien må inneholde nøyaktig 5 items.');return{screeningPassed:true,selectedCategory:input.selectedCategory,responses:[...input.categoryResponses],methodologicalSummary:'Beskrivende MMAT-profil for valgt studiedesign.',methodologicalWarning:'MMAT forbyr eksplisitt å beregne en samlet numerisk poengsum.'};}}
export class Cfir2AssessmentEngine{public static evaluateDeterminants(constructs:Cfir2ConstructItem[]):Cfir2EvaluationResult{const facilitatorsCount=constructs.filter(c=>c.classification.startsWith('Facilitator')).length,barriersCount=constructs.filter(c=>c.classification.startsWith('Barrier')).length,neutralCount=constructs.length-facilitatorsCount-barriersCount,overallImplementationProfile=constructs.length===0?'Insufficient evidence':barriersCount>facilitatorsCount?'Challenging':facilitatorsCount>barriersCount?'Favorable':'Mixed',domainSummaries=Array.from(new Set(constructs.map(c=>c.domainId))).map(domainId=>({domainId,constructs:constructs.filter(c=>c.domainId===domainId).length}));return{totalConstructsAssessed:constructs.length,facilitatorsCount,barriersCount,neutralCount,domainSummaries,overallImplementationProfile,methodologicalNote:'CFIR 2.0 er et determinant- og kontekstualiseringsrammeverk uten universell kvalitetsscore.'};}}
export class KtaAssessmentEngine{public static evaluateRoadmap(phases:KtaPhaseStatus[]):KtaEvaluationResult{const completedCount=phases.filter(p=>p.status==='COMPLETED').length,blockedCount=phases.filter(p=>p.status==='BLOCKED').length,overallStatus=blockedCount>0?'BLOCKED':completedCount===0?'NOT_STARTED':completedCount===phases.length?'COMPLETED':'IN_PROGRESS';return{phases:[...phases],completedCount,blockedCount,overallStatus,methodologicalNote:'KTA er en prosessmodell og har ingen universell kvalitetspoengsum.'};}}
export class Prisma2020ReportingEngine{public static evaluateReporting(r:Record<number,'Yes'|'Partial'|'No'|'Not applicable'>):Prisma2020EvaluationResult{const keys=Object.keys(r).map(Number).sort((a,b)=>a-b);if(keys.length===0||keys.some((v,i)=>v!==i+1))throw new Error('PRISMA 2020 item IDs må være sekvensielle.');const values=Object.values(r),reported=values.filter(v=>v==='Yes').length,partial=values.filter(v=>v==='Partial').length,total=values.length;return{checklistItemsEvaluated:total,sectionSummaries:[],overallReportingCompleteness:Number((((reported+partial)/total)*100).toFixed(2)),flowDiagramComplete:false,searchStrategyTransparent:false,methodologicalNotice:'PRISMA 2020 er en rapporteringsstandard; full rapportering krever eksplisitt vurdering av alle relevante items, inkludert flow diagram og søkestrategi.'};}}
export type Cfir2ConstructItemAlias=Cfir2ConstructItem;export type WhoEtdCriteriaInputAlias=WhoEtdCriteriaInput;
export class WhoEtdAssessmentEngine{public static evaluateEtD(input:WhoEtdCriteriaInput):WhoEtdEvaluationResult{return{guidelineQuestion:input.guidelineQuestion,targetPopulation:input.targetPopulation,intervention:input.intervention,comparison:input.comparison,recommendationType:'Krever eksplisitt EtD-judgment',strengthRationale:'EtD-resultatet skal bygge på eksplisitt vurdering av alle relevante kriterier.',detailedCriteriaAudit:Object.entries(input).map(([criterion,value])=>({criterion,present:Boolean(String(value??'').trim())})),implementationConsiderations:[],monitoringAndEvaluation:[],methodologicalStandard:'WHO EtD framework'};}}
export class RobinsIValidationService{public static evaluate(i:Parameters<typeof RobinsIAssessmentEngine.evaluate>[0]){return RobinsIAssessmentEngine.evaluate(i);}}
export class RobisValidationService{public static evaluate(i:Parameters<typeof RobisAssessmentEngine.evaluate>[0]){return RobisAssessmentEngine.evaluate(i);}}
export class Quadas2ValidationService{public static evaluate(i:Parameters<typeof Quadas2AssessmentEngine.evaluate>[0]){return Quadas2AssessmentEngine.evaluate(i);}}
export class QuipsValidationService{public static evaluate(i:Parameters<typeof QuipsAssessmentEngine.evaluate>[0]){return QuipsAssessmentEngine.evaluate(i);}}
export class ProbastValidationService{public static evaluate(i:Parameters<typeof ProbastAssessmentEngine.evaluate>[0]){return ProbastAssessmentEngine.evaluate(i);}}
export class MmatValidationService{public static evaluate(i:Parameters<typeof MmatAssessmentEngine.evaluate>[0]){return MmatAssessmentEngine.evaluate(i);}}
export class Prisma2020ValidationService{public static evaluateReporting(i:Record<number,'Yes'|'Partial'|'No'|'Not applicable'>){return Prisma2020ReportingEngine.evaluateReporting(i);}}

export const IMPLEMENTED_INSTRUMENT_IDS=new Set<string>(['amstar-2','agree-ii','jbi-qualitative-2017','rob-2','robins-i','robis','quadas-2','quips','probast','mmat-2018','grade','grade-cerqual','prisma-2020','cfir-2','kta',...MASTER_INSTRUMENTS_REGISTRY.filter(instrument=>instrument.id.startsWith('casp-')).map(instrument=>instrument.id)]);
export function isInstrumentImplemented(instrument:AppraisalInstrument):boolean{return IMPLEMENTED_INSTRUMENT_IDS.has(instrument.id);}
