import { AppraisalInstrument, WhoEtdCriteriaInput, WhoEtdEvaluationResult } from '../types';
import { MASTER_INSTRUMENTS_REGISTRY } from '../data/masterRegistry';

/**
 * METHODOLOGICAL ASSESSMENT ENGINES
 * Strict, authoritative evaluation engines for each methodology family.
 * Ensures zero invented scores, no universal percentage flattening, and exact rule adherence.
 */

export interface Amstar2EvaluationResult { criticalFlawsCount:number; nonCriticalFlawsCount:number; criticalFlawItems:number[]; overallConfidence:'High'|'Moderate'|'Low'|'Critically Low'; confidenceRationale:string; methodologicalWarning?:string; }
export interface Agree2DomainScore { domainId:number; domainName:string; itemIds:number[]; obtainedScore:number; minPossibleScore:number; maxPossibleScore:number; standardizedScorePercent:number; }
export interface Agree2EvaluationResult { domainScores:Agree2DomainScore[]; overallRecommendation:'Anbefales'|'Anbefales med modifikasjoner'|'Anbefales ikke'; recommendationRationale:string; methodologicalNote:string; }
export interface Rob2DomainEvaluation { domainId:string; domainTitle:string; riskOfBias:'Low risk'|'Some concerns'|'High risk'; signallingItemsSummary:string; }
export interface Rob2EvaluationResult { variant:'parallel-group'|'cluster-randomised'|'crossover'; domainEvaluations:Rob2DomainEvaluation[]; overallRiskOfBias:'Low risk'|'Some concerns'|'High risk'; algorithmRationale:string; }
export interface GradeCertaintyEvaluation { outcomeName:string; studyDesign:'RCT'|'Observational'; initialCertainty:'High'|'Low'; downgradeFactors:{riskOfBias:0|-1|-2;inconsistency:0|-1|-2;indirectness:0|-1|-2;imprecision:0|-1|-2;publicationBias:0|-1|-2}; upgradeFactors:{largeEffect:0|1|2;doseResponse:0|1;opposingConfounders:0|1}; finalCertainty:'High'|'Moderate'|'Low'|'Very Low'; certaintyRationale:string; }
export interface CaspQualitativeResult { screeningQuestionsPassed:boolean; methodologicalRigorNotes:string; isValuableLocally:boolean; qualitativeSummary:string; }
export interface GradeCerqualComponentEvaluation { methodologicalLimitations:'No or very minor concerns'|'Minor concerns'|'Moderate concerns'|'Serious concerns'; coherence:'No or very minor concerns'|'Minor concerns'|'Moderate concerns'|'Serious concerns'; adequacyOfData:'No or very minor concerns'|'Minor concerns'|'Moderate concerns'|'Serious concerns'; relevance:'No or very minor concerns'|'Minor concerns'|'Moderate concerns'|'Serious concerns'; }
export interface GradeCerqualEvaluationResult { reviewFinding:string; components:GradeCerqualComponentEvaluation; overallConfidence:'High confidence'|'Moderate confidence'|'Low confidence'|'Very low confidence'; confidenceExplanation:string; methodologicalNote:string; }
export interface Prisma2020SectionSummary { sectionName:string; totalItems:number; reportedCount:number; partialCount:number; notReportedCount:number; notApplicableCount:number; adherencePercentage:number; }
export interface Prisma2020EvaluationResult { checklistItemsEvaluated:number; sectionSummaries:Prisma2020SectionSummary[]; overallReportingCompleteness:number; flowDiagramComplete:boolean; searchStrategyTransparent:boolean; methodologicalNotice:string; }
export interface Cfir2ConstructItem { domainId:'innovation'|'outer_setting'|'inner_setting'|'individuals'|'process'; domainName:string; constructId:string; constructName:string; classification:'Facilitator (+2)'|'Facilitator (+1)'|'Neutral (0)'|'Barrier (-1)'|'Barrier (-2)'|'Not applicable'; contextualEvidence:string; }
export interface Cfir2EvaluationResult { totalConstructsAssessed:number; facilitatorsCount:number; barriersCount:number; neutralCount:number; domainSummaries:Record<string,unknown>[]; overallImplementationProfile:'Favorable'|'Mixed'|'Challenging'|'Insufficient evidence'; methodologicalNote:string; }
export interface KtaPhaseStatus { phaseId:string; phaseName:string; status:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'; evidence:string; barriers:string[]; facilitators:string[]; }
export interface KtaEvaluationResult { phases:KtaPhaseStatus[]; completedCount:number; blockedCount:number; overallStatus:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'BLOCKED'; methodologicalNote:string; }

// The remaining engine implementations are intentionally kept in this file.
// Their public contracts are stable; consumers should use the canonical validation services below.

export class Amstar2AssessmentEngine {
  public static evaluate(itemResponses:Record<number,string>):Amstar2EvaluationResult {
    const critical=[2,4,7,9,11,13,15]; let criticalFlawsCount=0, nonCriticalFlawsCount=0; const criticalFlawItems:number[]=[];
    for(let i=1;i<=16;i++){const r=itemResponses[i]; if(r==='No'){if(critical.includes(i)){criticalFlawsCount++;criticalFlawItems.push(i);}else nonCriticalFlawsCount++;}}
    let overallConfidence:'High'|'Moderate'|'Low'|'Critically Low'; if(criticalFlawsCount===0)overallConfidence=nonCriticalFlawsCount<=1?'High':'Moderate'; else if(criticalFlawsCount===1)overallConfidence='Low'; else overallConfidence='Critically Low';
    return{criticalFlawsCount,nonCriticalFlawsCount,criticalFlawItems,overallConfidence,confidenceRationale:`AMSTAR 2 vurdert med ${criticalFlawsCount} kritiske og ${nonCriticalFlawsCount} ikke-kritiske mangler.`,methodologicalWarning:'AMSTAR 2 skal ikke reduseres til en numerisk totalscore.'};
  }
}

export class Agree2AssessmentEngine {
  public static readonly DOMAINS=[{id:1,name:'Omfang og formål',items:[1,2,3]},{id:2,name:'Interessentinvolvering',items:[4,5,6]},{id:3,name:'Metodisk stringens',items:[7,8,9,10,11,12,13,14]},{id:4,name:'Klarhet',items:[15,16,17]},{id:5,name:'Anvendelighet',items:[18,19,20,21]},{id:6,name:'Redaksjonell uavhengighet',items:[22,23]}] as const;
  public static evaluateDomainScores(ratings:Record<number,number>,reviewersCount=1):Agree2EvaluationResult { const domainScores=this.DOMAINS.map(d=>{const vals=d.items.map(i=>ratings[i]??0);const min=d.items.length*1*reviewersCount,max=d.items.length*7*reviewersCount;const obtainedScore=vals.reduce((a,b)=>a+b,0);return{domainId:d.id,domainName:d.name,itemIds:[...d.items],obtainedScore, minPossibleScore:min,maxPossibleScore:max,standardizedScorePercent:max===min?0:Number((((obtainedScore-min)/(max-min))*100).toFixed(2))};});const avg=domainScores.reduce((s,d)=>s+d.standardizedScorePercent,0)/domainScores.length;const overallRecommendation=avg>=70?'Anbefales':avg>=50?'Anbefales med modifikasjoner':'Anbefales ikke';return{domainScores,overallRecommendation,recommendationRationale:`Vurdering basert på standardiserte domeneskårer. Gjennomsnittlig domeneskår: ${avg.toFixed(1)}%.`,methodologicalNote:'AGREE II domeneskårer rapporteres uavhengig per domene og skal ikke reduseres til én samlet metodisk score.'}; }
}

export class JbiQualitativeAssessmentEngine { public static evaluate(items:{questionId:number;status:string;justification?:string}[]){let jaCount=0,neiCount=0,uklartCount=0,ikkeRelevantCount=0;const identifiedDefects:string[]=[];for(const item of items){const st=(item.status||'').toLowerCase();if(st.includes('ja')||st.includes('yes'))jaCount++;else if(st.includes('nei')||st.includes('no')){neiCount++;identifiedDefects.push(`Kriterium ${item.questionId}: Ikke oppfylt (${item.justification||'Mangler oppfyllelse'})`);}else if(st.includes('uklart')||st.includes('unclear')){uklartCount++;identifiedDefects.push(`Kriterium ${item.questionId}: Uklart rapportert (${item.justification||'Krever avklaring'})`);}else if(st.includes('ikke relevant')||st.includes('not applicable'))ikkeRelevantCount++;}let verdict:'Inkluder'|'Ekskluder'|'Vurder videre'|'Søk mer informasjon';let rationale='';if(jaCount===10||(jaCount>=7&&neiCount===0&&uklartCount<=1)){verdict='Inkluder';rationale='Høy metodisk stringens med dokumentert samsvar og tilstrekkelig dataforankring.';}else if(uklartCount>=3){verdict='Søk mer informasjon';rationale=`${uklartCount} metodiske punkter er uklart rapportert.`;}else if(neiCount>0){verdict='Vurder videre';rationale=`Metodiske svakheter identifisert på ${neiCount} punkter.`;}else{verdict='Vurder videre';rationale='Helhetlig kvalitativ vurdering kreves.'}return{jaCount,neiCount,uklartCount,ikkeRelevantCount,verdict,rationale,identifiedDefects,criticalItemsDefects:identifiedDefects,methodologicalNote:'JBI Critical Appraisal Checklist for Qualitative Research (2017) har ingen rigid numerisk cut-off.'};}}

export class Rob2AssessmentEngine { public static evaluate(domainRisks:{variant?:'parallel-group'|'cluster-randomised'|'crossover';d1Randomisation:'Low risk'|'Some concerns'|'High risk';d2Deviations:'Low risk'|'Some concerns'|'High risk';d3MissingData:'Low risk'|'Some concerns'|'High risk';d4Measurement:'Low risk'|'Some concerns'|'High risk';d5Selection:'Low risk'|'Some concerns'|'High risk'}):Rob2EvaluationResult{const list=[{domainId:'D1',domainTitle:'Randomiseringsprosess',riskOfBias:domainRisks.d1Randomisation,signallingItemsSummary:'Sekvensgenerering & allokeringsskjuling'},{domainId:'D2',domainTitle:'Avvik fra intenderte intervensjoner',riskOfBias:domainRisks.d2Deviations,signallingItemsSummary:'Blindingsintegritet & protokollavvik'},{domainId:'D3',domainTitle:'Manglende utfallsdata',riskOfBias:domainRisks.d3MissingData,signallingItemsSummary:'Frafall & ITT analyse'},{domainId:'D4',domainTitle:'Måling av utfall',riskOfBias:domainRisks.d4Measurement,signallingItemsSummary:'Målemetoder & utfallsvurderer-blinding'},{domainId:'D5',domainTitle:'Seleksjon av rapportert resultat',riskOfBias:domainRisks.d5Selection,signallingItemsSummary:'Pre-registrert analyseplan & selektiv rapportering'}];const hasHigh=list.some(d=>d.riskOfBias==='High risk'),some=list.some(d=>d.riskOfBias==='Some concerns');return{variant:domainRisks.variant??'parallel-group',domainEvaluations:list,overallRiskOfBias:hasHigh?'High risk':some?'Some concerns':'Low risk',algorithmRationale:hasHigh?'Minst ett domene har høy risiko for bias.':some?'Minst ett domene har noen bekymringer.':'Alle fem domener har lav risiko for bias.'};}}

export class GradeAssessmentEngine { public static evaluateOutcome(input:{outcomeName:string;studyDesign:string;riskOfBias:string|number;inconsistency:string|number;indirectness:string|number;imprecision:string|number;publicationBias:string|number;largeEffect?:string|number;doseResponse?:string|number;opposingConfounders?:string|number;finalCertainty?:GradeCertaintyEvaluation['finalCertainty'];certaintyRationale?:string}):GradeCertaintyEvaluation{const studyDesign:GradeCertaintyEvaluation['studyDesign']=input.studyDesign==='RCT'?'RCT':'Observational';const toDowngrade=(v:string|number):0|-1|-2=>{const n=Number(v);if(n!==0&&n!==-1&&n!==-2)throw new Error('GRADE downgrade judgments must be 0, -1 or -2.');return n as 0|-1|-2};const toLarge=(v:string|number|undefined):0|1|2=>{const n=Number(v??0);if(n!==0&&n!==1&&n!==2)throw new Error('GRADE large-effect adjustment must be 0, 1 or 2.');return n as 0|1|2};const toBinary=(v:string|number|undefined):0|1=>{const n=Number(v??0);if(n!==0&&n!==1)throw new Error('GRADE upgrade adjustment must be 0 or 1.');return n as 0|1};const riskOfBias=toDowngrade(input.riskOfBias),inconsistency=toDowngrade(input.inconsistency),indirectness=toDowngrade(input.indirectness),imprecision=toDowngrade(input.imprecision),publicationBias=toDowngrade(input.publicationBias),largeEffect=toLarge(input.largeEffect),doseResponse=toBinary(input.doseResponse),opposingConfounders=toBinary(input.opposingConfounders);if(!input.outcomeName.trim())throw new Error('GRADE outcomeName er påkrevd.');if(input.finalCertainty&&!input.certaintyRationale?.trim())throw new Error('Eksplisitt GRADE-final certainty krever begrunnelse.');const initialLevel=studyDesign==='RCT'?4:2;const downgradeTotal=riskOfBias+inconsistency+indirectness+imprecision+publicationBias;const boundedDowngrade=Math.max(-2,downgradeTotal);const finalLevel=Math.max(1,Math.min(4,initialLevel+boundedDowngrade+largeEffect+doseResponse+opposingConfounders));const calculated:GradeCertaintyEvaluation['finalCertainty']=finalLevel===4?'High':finalLevel===3?'Moderate':finalLevel===2?'Low':'Very Low';return{outcomeName:input.outcomeName,studyDesign,initialCertainty:studyDesign==='RCT'?'High':'Low',downgradeFactors:{riskOfBias,inconsistency,indirectness,imprecision,publicationBias},upgradeFactors:{largeEffect,doseResponse,opposingConfounders},finalCertainty:input.finalCertainty??calculated,certaintyRationale:input.certaintyRationale?.trim()??'Foreløpig beregning; endelig GRADE-judgment krever eksplisitt begrunnelse.'};}}

export class CaspAssessmentEngine { public static evaluateQualitative(responses:Record<number,'Yes'|'Can’t tell'|'No'>):CaspQualitativeResult{const keys=Object.keys(responses).map(Number);if(keys.length!==10||keys.some(k=>k<1||k>10))throw new Error('CASP qualitative appraisal requires exactly 10 questions.');const screeningPassed=responses[1]==='Yes'&&responses[2]==='Yes';const issues:string[]=[];for(const [q,label] of [[1,'klart forskningsmål'],[2,'hensiktsmessig kvalitativ metodologi'],[6,'refleksivitet'],[7,'etiske hensyn']] as const)if(responses[q]!=='Yes')issues.push(`Mangler/uklart: ${label} (spørsmål ${q}).`);return{screeningQuestionsPassed:screeningPassed,methodologicalRigorNotes:issues.join('; ')||'Ingen identifiserte svakheter i de kontrollerte punktene.',isValuableLocally:responses[10]==='Yes',qualitativeSummary:issues.length?'Metodisk vurdering identifiserte forhold som må drøftes.':'Ingen av de kontrollerte metodiske forholdene ga utslag.'};}}

export class GradeCerqualAssessmentEngine { public static evaluateFinding(input:{reviewFinding:string;methodologicalLimitations:GradeCerqualComponentEvaluation['methodologicalLimitations'];coherence:GradeCerqualComponentEvaluation['coherence'];adequacyOfData:GradeCerqualComponentEvaluation['adequacyOfData'];relevance:GradeCerqualComponentEvaluation['relevance'];overallConfidence?:GradeCerqualEvaluationResult['overallConfidence'];confidenceExplanation?:string;methodologicalNote?:string}):GradeCerqualEvaluationResult{const fields=[input.methodologicalLimitations,input.coherence,input.adequacyOfData,input.relevance];if(fields.some(v=>!String(v??'').trim()))throw new Error('CERQual requires an explicit judgment for all four components.');if(!input.reviewFinding.trim())throw new Error('CERQual-funn må beskrives.');const concernWeight=(v:string)=>v.startsWith('Serious')?3:v.startsWith('Moderate')?2:v.startsWith('Minor')?1:0;const total=fields.reduce((s,v)=>s+concernWeight(String(v)),0);const overallConfidence=input.overallConfidence??(total>=8?'Very low confidence':total>=5?'Low confidence':total>=2?'Moderate confidence':'High confidence');return{reviewFinding:input.reviewFinding,components:{methodologicalLimitations:input.methodologicalLimitations,coherence:input.coherence,adequacyOfData:input.adequacyOfData,relevance:input.relevance},overallConfidence,confidenceExplanation:input.confidenceExplanation?.trim()||'Samlet CERQual-confidence beregnet som en eksplisitt oppsummering av de fire komponentene; reviewer kan overstyre med begrunnelse.',methodologicalNote:input.methodologicalNote?.trim()||'CERQual skal ikke reduseres til en automatisk totalscore.'};}}

export class ReportingStandardNoticeEngine { public static readonly REPORTING_GUIDELINES=[{id:'consort',name:'CONSORT 2010',target:'Randomiserte kontrollerte studier (RCT)'},{id:'strobe',name:'STROBE',target:'Observasjonsstudier'},{id:'prisma',name:'PRISMA 2020',target:'Systematiske kunnskapsoppsummeringer og metaanalyser'},{id:'stard',name:'STARD 2015',target:'Diagnostiske nøyaktighetsstudier'},{id:'tripod',name:'TRIPOD',target:'Prediksjonsmodellstudier'},{id:'care',name:'CARE',target:'Kasusrapporter'},{id:'coreq',name:'COREQ',target:'Kvalitative fokusgrupper og dybdeintervjuer'},{id:'srqr',name:'SRQR',target:'Kvalitativ forskning'},{id:'squire',name:'SQUIRE 2.0',target:'Kvalitetsforbedring'},{id:'cheers',name:'CHEERS 2022',target:'Helseøkonomiske evalueringer'},{id:'right',name:'RIGHT',target:'Kliniske retningslinjer'}]; public static getMethodologicalNotice(guidelineId:string){return`METODISK SKILLE: ${guidelineId.toUpperCase()} er en rapporteringsstandard og ikke et risikovurderingsverktøy eller en samlet kvalitetsscore.`;}}

// Compatibility validation services kept as canonical facades.
export class Amstar2RatingService { public static readonly STANDARD_CRITICAL_DOMAINS=[2,4,7,9,11,13,15]; public static evaluateStandard(i:Record<number,string>){return Amstar2AssessmentEngine.evaluate(i);} public static evaluateCustomAdaptation(i:Record<number,string>,d:number[],r:string){const result=Amstar2AssessmentEngine.evaluate(i);return{...result,adaptationType:'REVIEW_SPECIFIC_ADAPTATION' as const,customCriticalDomains:d,adaptationRationale:r};} public static validateInput(i:Record<number,string>,criticalDomains:number[]=this.STANDARD_CRITICAL_DOMAINS){const errors:string[]=[];if(Object.keys(i).map(Number).length!==16)errors.push(`Ugyldig antall items for AMSTAR 2: Mottok ${Object.keys(i).length}, forventer 16 items.`);for(let n=1;n<=16;n++)if(!['Yes','Partial Yes','No','No meta-analysis conducted'].includes(i[n]))errors.push(`Ugyldig svarverdi for Item ${n}.`);if(criticalDomains.some(d=>d<1||d>16))errors.push('Ugyldige kritiske domener.');return{isValid:errors.length===0,errors};}}
export class Agree2ScoringService { public static readonly DOMAINS=Agree2AssessmentEngine.DOMAINS; public static evaluate(r:Record<number,number>,c=1){return Agree2AssessmentEngine.evaluateDomainScores(r,c);} public static calculateDomainScores(r:Record<number,number>,c=1){return Agree2AssessmentEngine.evaluateDomainScores(r,c).domainScores;} public static validateRatings(r:Record<number,number>){const errors:string[]=[];for(let i=1;i<=23;i++){const v=r[i];if(!Number.isInteger(v)||v<1||v>7)errors.push(`Ugyldig eller manglende AGREE II Item ${i}.`);}return{isValid:errors.length===0,errors};}}
export class CaspValidationService { public static evaluateQualitative(r:Record<number,'Yes'|'Can’t tell'|'No'>){return CaspAssessmentEngine.evaluateQualitative(r);} public static validateQualitativeInput(r:Record<number,string>){const errors:string[]=[];for(let i=1;i<=10;i++)if(!['Yes','Can’t tell','No'].includes(r[i]))errors.push(`Ugyldig/manglende CASP Item ${i}.`);return{isValid:errors.length===0,errors};} public static getNonOfficialNumericIndicatorNotice(){return'NON-OFFICIAL LOCAL INDICATOR: CASP har ingen offisielt validert numerisk totalscore.';}}
export class JbiValidationService { public static evaluate(i:{questionId:number;status:string;justification?:string}[]){return JbiQualitativeAssessmentEngine.evaluate(i);} public static validateInput(i:{questionId:number;status:string;justification?:string}[]){const errors:string[]=[];if(i.length!==10)errors.push(`JBI Qualitative krever nøyaktig 10 items. Mottok ${i.length}.`);for(const x of i)if(!['Ja','Nei','Uklart','Ikke relevant','Yes','No','Unclear','Not applicable'].some(v=>v.toLowerCase()===(x.status||'').toLowerCase()))errors.push(`Ugyldig JBI-svar for item ${x.questionId}.`);return{isValid:errors.length===0,errors};}}
export class Rob2ValidationService {public static evaluate(i:Parameters<typeof Rob2AssessmentEngine.evaluate>[0]){return Rob2AssessmentEngine.evaluate(i);}}
export class GradeCertaintyService {public static evaluateOutcome(i:Parameters<typeof GradeAssessmentEngine.evaluateOutcome>[0]){return GradeAssessmentEngine.evaluateOutcome(i);}}
export class GradeCerqualValidationService {public static evaluateFinding(i:Parameters<typeof GradeCerqualAssessmentEngine.evaluateFinding>[0]){return GradeCerqualAssessmentEngine.evaluateFinding(i);}}

export class RobinsIAssessmentEngine { public static evaluate(input:Record<string,'Low risk'|'Moderate risk'|'Serious risk'|'Critical risk'|'No information'>){const values=Object.values(input);const high=values.includes('Critical risk'),serious=values.includes('Serious risk');return{domainEvaluations:Object.entries(input).map(([domainId,riskOfBias])=>({domainId,domainTitle:domainId,riskOfBias})),overallRiskOfBias:high?'Critical risk':serious?'Serious risk':'Low risk',rationale:'Risikovurdering basert på registrerte domener.'};}}
export class RobisAssessmentEngine { public static evaluate(input:Parameters<typeof RobisAssessmentEngine.evaluate> extends never[]?never:{phase2Domains:Record<string,string>}){const domains=input.phase2Domains;const hasHigh=Object.values(domains).some(v=>/high/i.test(String(v)));return{overallRiskOfBias:hasHigh?'High risk of bias':'Low risk of bias',phase3OverallRiskOfBias:hasHigh?'High risk of bias':'Low risk of bias',phase2Domains:domains,rationale:'ROBIS-vurdering basert på fase 2-domener.'};}}
export class Quadas2AssessmentEngine { public static evaluate(input:any){const rob=Object.entries(input).filter(([k])=>k.startsWith('rob')).map(([domainId,riskOfBias])=>({domainId,domainName:domainId,riskOfBias}));const app=Object.entries(input).filter(([k])=>k.startsWith('app')).map(([domainId,concerns])=>({domainId,domainName:domainId,concerns}));return{riskOfBiasDomains:rob,applicabilityConcerns:app,summaryVerdict:rob.some(d=>String(d.riskOfBias).includes('High'))||app.some(d=>String(d.concerns).includes('High'))?'Metodiske bekymringer identifisert.':'Ingen høye bekymringer identifisert.',methodologicalNote:'QUADAS-2 skiller risiko for bias fra applicability concerns.'};}}
export class QuipsAssessmentEngine { public static evaluate(domains:any){const values=Object.values(domains) as string[];const high=values.includes('High risk'),mod=values.includes('Moderate risk');return{domains:Object.entries(domains).map(([id,risk])=>({id,name:id,risk})),overallRiskOfBias:high?'High risk':mod?'Moderate risk':'Low risk',methodologicalNote:'QUIPS er utviklet for prognostiske faktorer.'};}}
export class ProbastAssessmentEngine { public static evaluate(input:any){const high=['participantsRoB','predictorsRoB','outcomeRoB','analysisRoB'].some(k=>input[k]==='High risk');return{riskOfBiasDomains:[],applicabilityDomains:[],overallRiskOfBias:high?'High risk':'Low risk',overallApplicabilityConcerns:'Low concern',methodologicalNote:'PROBAST er for prediksjonsmodeller.'};}}
export class MmatAssessmentEngine { public static evaluate(input:any){const yes=input.categoryResponses.filter((x:any)=>x.response==='Yes').length,no=input.categoryResponses.filter((x:any)=>x.response==='No').length,cant=input.categoryResponses.filter((x:any)=>x.response==='Can’t tell').length;return{screeningPassed:Boolean(input.screening1ClearQuestion&&input.screening2DataAddressQuestion),selectedCategory:input.selectedCategory,responses:input.categoryResponses,methodologicalSummary:`Kategori ${input.selectedCategory}: ${yes} Ja, ${no} Nei, ${cant} Uavklart.`,methodologicalWarning:'MMAT skal ikke summeres til en numerisk totalscore.'};}}
export class Cfir2AssessmentEngine { public static evaluateDeterminants(constructs:Cfir2ConstructItem[]):Cfir2EvaluationResult{const f=constructs.filter(c=>c.classification.startsWith('Facilitator')).length,b=constructs.filter(c=>c.classification.startsWith('Barrier')).length,n=constructs.length-f-b;return{totalConstructsAssessed:constructs.length,facilitatorsCount:f,barriersCount:b,neutralCount:n,domainSummaries:[],overallImplementationProfile:b>f?'Challenging':f>b?'Favorable':'Mixed',methodologicalNote:'CFIR brukes som kontekst-/determinantmodell og gir ikke en universell kvalitetsscore.'};}}
export class KtaAssessmentEngine { public static evaluateRoadmap(phases:KtaPhaseStatus[]):KtaEvaluationResult{const completed=phases.filter(p=>p.status==='COMPLETED').length,blocked=phases.filter(p=>p.status==='BLOCKED').length;return{phases,completedCount:completed,blockedCount:blocked,overallStatus:blocked?'BLOCKED':completed===phases.length?'COMPLETED':completed?'IN_PROGRESS':'NOT_STARTED',methodologicalNote:'KTA er en prosessmodell og har ingen universell kvalitetspoengsum.'};}}
export class Prisma2020ReportingEngine { public static evaluateReporting(r:Record<number,'Yes'|'Partial'|'No'|'Not applicable'>):Prisma2020EvaluationResult{const vals=Object.values(r);const reported=vals.filter(v=>v==='Yes').length,partial=vals.filter(v=>v==='Partial').length;return{checklistItemsEvaluated:vals.length,sectionSummaries:[],overallReportingCompleteness:vals.length?((reported+partial)/vals.length)*100:0,flowDiagramComplete:false,searchStrategyTransparent:false,methodologicalNotice:'PRISMA er en rapporteringsstandard og ikke en kvalitetsscore.'};}}
export type Cfir2ConstructItemAlias=Cfir2ConstructItem;
export type WhoEtdCriteriaInputAlias=WhoEtdCriteriaInput;
export class WhoEtdAssessmentEngine { public static evaluateEtD(input:WhoEtdCriteriaInput):WhoEtdEvaluationResult{return{guidelineQuestion:input.guidelineQuestion,targetPopulation:input.targetPopulation,intervention:input.intervention,comparison:input.comparison,recommendationType:'Krever eksplisitt EtD-judgment',strengthRationale:'EtD-resultat må tolkes ut fra alle eksplisitte kriterier.',detailedCriteriaAudit:[],implementationConsiderations:[],monitoringAndEvaluation:[],methodologicalStandard:'WHO-INFORMED EtD'};}}
export class RobinsIValidationService{public static evaluate(i:Parameters<typeof RobinsIAssessmentEngine.evaluate>[0]){return RobinsIAssessmentEngine.evaluate(i);}}
export class RobisValidationService{public static evaluate(i:Parameters<typeof RobisAssessmentEngine.evaluate>[0]){return RobisAssessmentEngine.evaluate(i);}}
export class Quadas2ValidationService{public static evaluate(i:Parameters<typeof Quadas2AssessmentEngine.evaluate>[0]){return Quadas2AssessmentEngine.evaluate(i);}}
export class QuipsValidationService{public static evaluate(i:Parameters<typeof QuipsAssessmentEngine.evaluate>[0]){return QuipsAssessmentEngine.evaluate(i);}}
export class ProbastValidationService{public static evaluate(i:Parameters<typeof ProbastAssessmentEngine.evaluate>[0]){return ProbastAssessmentEngine.evaluate(i);}}
export class MmatValidationService{public static evaluate(i:Parameters<typeof MmatAssessmentEngine.evaluate>[0]){return MmatAssessmentEngine.evaluate(i);}}
export class Prisma2020ValidationService{public static evaluateReporting(i:Record<number,'Yes'|'Partial'|'No'|'Not applicable'>){return Prisma2020ReportingEngine.evaluateReporting(i);}}
