import type { PrivacyInspectionResult, ResearchMetadataRecord } from '../shared/moduleContracts';
import { SOURCE_RECORD_SCHEMA_VERSION, createRecordId, type SourceRecord } from '../domain/sourceRecord';

export interface BuildSourceRecordInput { meta:ResearchMetadataRecord; privacyResult:PrivacyInspectionResult; lawText:string|null; toolVersion:string; recordId?:string; capturedAt?:string; }
function buildReferenceDraft(meta:ResearchMetadataRecord):SourceRecord['referenceDraft']{const hasMinimum=Boolean(meta.title&&meta.sourceUrl);const year=meta.publicationDate?.slice(0,4);const apa7=hasMinimum?[meta.authors?.filter(Boolean).join(', ')||'Ukjent forfatter',year?`(${year}).`:undefined,meta.title?`${meta.title}.`:undefined,meta.journal,meta.volume,meta.issue?`(${meta.issue})`:undefined,meta.firstPage&&meta.lastPage?`${meta.firstPage}-${meta.lastPage}`:meta.firstPage,meta.doi?`https://doi.org/${meta.doi.replace(/^https?:\/\/doi\.org\//i,'')}`:meta.sourceUrl].filter(Boolean).join(' '):null;return{apa7,status:hasMinimum?'complete':meta.title?'incomplete':'unverifiable',note:'Draft – detected metadata, not verified against source'};}
function buildDoi(meta:ResearchMetadataRecord):SourceRecord['identifiers']['doi']{const raw=meta.doi?.trim();if(!raw)return null;const normalized=raw.replace(/^doi:\s*/i,'').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').replace(/[.,;:)]+$/,'');const formatValid=/^10\.\d{4,9}\/[\-._;()/:A-Z0-9]+$/i.test(normalized);return{normalized,formatValid,raw,resolverUrl:`https://doi.org/${normalized}`};}
function buildMetadata(meta:ResearchMetadataRecord):SourceRecord['metadata']{const missingFields:string[]=[];if(!meta.title)missingFields.push('title');if(!meta.authors?.length)missingFields.push('authors');if(!meta.publicationDate)missingFields.push('publicationDate');if(!meta.journal)missingFields.push('journal');return{...meta,status:missingFields.length===0?'COMPLETE':meta.title?'INCOMPLETE':'UNVERIFIABLE',missingFields};}
function buildLegalReference(lawText:string|null):SourceRecord['legalReference']{const text=lawText?.trim();return text?{type:/forskrift/i.test(text)?'forskrift':'lov',officialId:'UNVERIFIED',shortTitle:'',paragraph:null,citation:text}:null;}
export function buildSourceRecord(input:BuildSourceRecordInput):SourceRecord{const capturedAt=input.capturedAt??new Date().toISOString();return{schemaVersion:SOURCE_RECORD_SCHEMA_VERSION,recordId:input.recordId??createRecordId(),source:{url:input.meta.sourceUrl,capturedAt},metadata:buildMetadata(input.meta),identifiers:{doi:buildDoi(input.meta)},referenceDraft:buildReferenceDraft(input.meta),legalReference:buildLegalReference(input.lawText),privacy:{...input.privacyResult,localOnly:true},provenance:{tool:'source-record-gateway',toolVersion:input.toolVersion,collectedLocally:true,externalRequestsMade:false,collectedAt:capturedAt}};}


