export interface HelpEntry{id:string;title:string;definition:string;ruleOfThumb:string;reference:string;steps:string[];}
export const HELP_REGISTRY:Record<string,HelpEntry>={
  PICO:{id:'PICO',title:'PICO',definition:'Population, Intervention, Comparison og Outcome strukturerer et presist klinisk forskningsspørsmål.',ruleOfThumb:'Hvert element bør være eksplisitt nok til å styre søk og inklusjonskriterier.',reference:'PRISMA 2020; Cochrane Handbook',steps:['Definer populasjon','Definer intervensjon og sammenligning','Definer relevante utfall']},
  'RoB 2':{id:'RoB 2',title:'RoB 2',definition:'Cochranes verktøy for risiko for bias i randomiserte studier.',ruleOfThumb:'Some concerns og High risk må begrunnes med signalling questions og relevante kilder.',reference:'Cochrane RoB 2 guidance',steps:['Vurder randomisering','Vurder avvik','Vurder manglende data','Vurder måling','Vurder selektiv rapportering']},
  GRADE:{id:'GRADE',title:'GRADE',definition:'Rammeverk for sikkerhet/tillit til evidens per utfall.',ruleOfThumb:'Nedgradering skal begrunnes per domene; automatikk er bare et forslag.',reference:'GRADE Working Group guidance',steps:['Startnivå','Vurder fem nedgraderingsdomener','Dokumenter begrunnelse','Fastsett endelig certainty']},
  Kappa:{id:'Kappa',title:'Cohen’s Kappa',definition:'Mål på enighet mellom to ratere korrigert for forventet tilfeldig enighet.',ruleOfThumb:'Kappa bør tolkes sammen med rå enighetsprosent og fordelingen av kategorier.',reference:'Cohen, 1960',steps:['Beregn observert enighet','Beregn forventet enighet','Beregn κ']},
  'I²':{id:'I²',title:'I²',definition:'Andel av variasjonen mellom estimater som kan tilskrives heterogenitet fremfor sampling error.',ruleOfThumb:'50 % brukes ofte som et grovt signal om moderat heterogenitet, men er ikke en universell grense.',reference:'Cochrane Handbook',steps:['Beregn Q','Beregn df','Beregn I²','Vurder klinisk og metodisk heterogenitet']},
  JBI:{id:'JBI',title:'JBI',definition:'Joanna Briggs Institutes kritiske vurderingsverktøy tilpasset studiedesign.',ruleOfThumb:'Bruk riktig JBI-sjekkliste for studiedesignet og dokumenter begrunnelser.',reference:'JBI Manual for Evidence Synthesis',steps:['Identifiser design','Velg riktig sjekkliste','Dokumenter hvert svar']},
};
export function getHelpEntry(id:string):HelpEntry{return HELP_REGISTRY[id]??{id,title:id,definition:'Ingen standardtekst er registrert.',ruleOfThumb:'Kontroller definisjonen mot primærkilden.',reference:'Primærkilde må oppgis.',steps:[]};}
