export interface HelpEntry{id:string;title:string;definition:string;ruleOfThumb:string;reference:string;steps:string[];}
export const HELP_REGISTRY:Record<string,HelpEntry>={
  PICO:{id:'PICO',title:'PICO',definition:'Population, Intervention, Comparison og Outcome strukturerer et presist klinisk forskningsspÃ¸rsmÃ¥l.',ruleOfThumb:'Hvert element bÃ¸r vÃ¦re eksplisitt nok til Ã¥ styre sÃ¸k og inklusjonskriterier.',reference:'PRISMA 2020; Cochrane Handbook',steps:['Definer populasjon','Definer intervensjon og sammenligning','Definer relevante utfall']},
  'RoB 2':{id:'RoB 2',title:'RoB 2',definition:'Cochranes verktÃ¸y for risiko for bias i randomiserte studier.',ruleOfThumb:'Some concerns og High risk mÃ¥ begrunnes med signalling questions og relevante kilder.',reference:'Cochrane RoB 2 guidance',steps:['Vurder randomisering','Vurder avvik','Vurder manglende data','Vurder mÃ¥ling','Vurder selektiv rapportering']},
  GRADE:{id:'GRADE',title:'GRADE',definition:'Rammeverk for sikkerhet/tillit til evidens per utfall.',ruleOfThumb:'Nedgradering skal begrunnes per domene; automatikk er bare et forslag.',reference:'GRADE Working Group guidance',steps:['StartnivÃ¥','Vurder fem nedgraderingsdomener','Dokumenter begrunnelse','Fastsett endelig certainty']},
  Kappa:{id:'Kappa',title:'Cohenâ€™s Kappa',definition:'MÃ¥l pÃ¥ enighet mellom to ratere korrigert for forventet tilfeldig enighet.',ruleOfThumb:'Kappa bÃ¸r tolkes sammen med rÃ¥ enighetsprosent og fordelingen av kategorier.',reference:'Cohen, 1960',steps:['Beregn observert enighet','Beregn forventet enighet','Beregn Îº']},
  'IÂ²':{id:'IÂ²',title:'IÂ²',definition:'Andel av variasjonen mellom estimater som kan tilskrives heterogenitet fremfor sampling error.',ruleOfThumb:'50 % brukes ofte som et grovt signal om moderat heterogenitet, men er ikke en universell grense.',reference:'Cochrane Handbook',steps:['Beregn Q','Beregn df','Beregn IÂ²','Vurder klinisk og metodisk heterogenitet']},
  JBI:{id:'JBI',title:'JBI',definition:'Joanna Briggs Institutes kritiske vurderingsverktÃ¸y tilpasset studiedesign.',ruleOfThumb:'Bruk riktig JBI-sjekkliste for studiedesignet og dokumenter begrunnelser.',reference:'JBI Manual for Evidence Synthesis',steps:['Identifiser design','Velg riktig sjekkliste','Dokumenter hvert svar']},
};
export function getHelpEntry(id:string):HelpEntry{return HELP_REGISTRY[id]??{id,title:id,definition:'Ingen standardtekst er registrert.',ruleOfThumb:'Kontroller definisjonen mot primÃ¦rkilden.',reference:'PrimÃ¦rkilde mÃ¥ oppgis.',steps:[]};}

