import type { ArticleAppraisal, JBIEvaluationItem } from '../types';
import { JbiQualitativeValidationService } from './jbiValidationService';
import { DocumentParserService } from './documentParserService';
import { generateUniqueId, generateArticleId, generateAuditId } from './idGenerator';
import JSZip from 'jszip';

export type SupportedImportFormat = 'ris' | 'bibtex' | 'json' | 'csv' | 'tsv' | 'pubmed' | 'document' | 'unknown';
export type SupportedExportFormat = 'json' | 'zip' | 'csv' | 'tsv' | 'excel' | 'word' | 'pdf' | 'ris' | 'bibtex' | 'markdown' | 'latex' | 'txt';
export interface ImportPreviewItem { id:string; title:string; authors:string; year:number; journal:string; doi:string; design:string; abstract?:string; items?:JBIEvaluationItem[]; verdict?:'Inkluder'|'Ekskluder'|'Vurder videre'|'Søk mer informasjon'; isDuplicate?:boolean; }
export interface ImportResult { format:SupportedImportFormat; formatName:string; totalParsed:number; newArticles:ArticleAppraisal[]; duplicatesCount:number; warnings:string[]; }
export interface ExportOptions { scope:'all'|'included_only'|'selected_only'; selectedArticleId?:string; includeJustifications:boolean; includeAuditTrail:boolean; includeEvidenceQuotes:boolean; projectName?:string; }

function instrumentNeutralDesign(design?:string|null):string { const normalized=design?.trim(); return normalized || 'Ukjent / uavklart – krever studiedesignklassifisering'; }
function normalizeMetadata(value?:string|null):string { return value?.trim() || 'Ikke oppgitt'; }

export class ImportExportService {
  public static detectFormat(content:string,fileName?:string):SupportedImportFormat{const t=content.trim(),n=(fileName||'').toLowerCase();if(n.endsWith('.ris'))return'ris';if(n.endsWith('.bib')||n.endsWith('.bibtex'))return'bibtex';if(n.endsWith('.json'))return'json';if(n.endsWith('.csv'))return'csv';if(n.endsWith('.tsv')||n.endsWith('.tab'))return'tsv';if(n.endsWith('.nbib')||n.endsWith('.medline'))return'pubmed';if(n.endsWith('.pdf')||n.endsWith('.docx')||n.endsWith('.txt')||n.endsWith('.md'))return'document';if(t.startsWith('{')||t.startsWith('[')){try{JSON.parse(t);return'json';}catch{}}if(/^TY\s{1,2}-\s+/m.test(t)||/^ER\s{1,2}-/m.test(t))return'ris';if(/@(article|book|inproceedings|misc|phdthesis|techreport)\s*\{/i.test(t))return'bibtex';if(/^(PMID|PMID-|TI\s{1,2}-|AU\s{1,2}-)/m.test(t))return'pubmed';const first=t.split('\n')[0]||'';if(first.includes('\t'))return'tsv';if(first.includes(';')||first.includes(',')){const h=first.toLowerCase();if(h.includes('title')||h.includes('tittel')||h.includes('author')||h.includes('doi')||h.includes('forfatter'))return'csv';}return'unknown';}

  public static async parseImport(content:string|ArrayBuffer,fileName:string,existingArticles:ArticleAppraisal[]=[]):Promise<ImportResult>{const existingDois=new Set(existingArticles.map(a=>a.doi.toLowerCase().trim()).filter(Boolean));const existingTitles=new Set(existingArticles.map(a=>a.title.toLowerCase().trim()).filter(Boolean));if(typeof content!=='string'){const parsed=await DocumentParserService.parseFile({name:fileName,size:content.byteLength,content});const a=this.createDefaultArticle({id:generateArticleId('art'),title:parsed.metadata.title,authors:parsed.metadata.authors,year:parsed.metadata.year,journal:parsed.metadata.journal,doi:parsed.metadata.doi,design:undefined,studyContext:parsed.metadata.abstract||undefined,sourceName:fileName});return{format:'document',formatName:'Forskningsdokument',totalParsed:1,newArticles:[a],duplicatesCount:(a.doi&&existingDois.has(a.doi.toLowerCase()))?1:0,warnings:parsed.isScannedOrImageOnly?['Dokumentet er skannet eller uten tilgjengelig tekstlag og krever manuell/OCR-gjennomgang.']:[]};}const f=this.detectFormat(content,fileName);let items:ImportPreviewItem[]=[];const warnings:string[]=[];switch(f){case'ris':items=this.parseRis(content);break;case'bibtex':items=this.parseBibtex(content);break;case'json':items=this.parseJson(content);break;case'csv':case'tsv':items=this.parseDelimited(content,f==='tsv'?'\t':(content.includes(';')?';':','));break;case'pubmed':items=this.parsePubmed(content);break;default:{const m=DocumentParserService.extractMetadata(content,fileName);items=[{id:generateArticleId('art'),title:m.title,authors:m.authors,year:m.year,journal:m.journal,doi:m.doi,design:m.studyDesignDetected,abstract:m.abstract}];warnings.push('Formatet ble gjenkjent som ustrukturert tekst. Metadata ble ekstrahert med heuristisk parser; studiedesign skal verifiseres.');}}let duplicatesCount=0;const finalArticles:ArticleAppraisal[]=[];for(const item of items){const dup=Boolean((item.doi&&existingDois.has(item.doi.toLowerCase().trim()))||(item.title&&existingTitles.has(item.title.toLowerCase().trim())));if(dup)duplicatesCount++;finalArticles.push(this.createDefaultArticle({id:item.id||generateArticleId('art'),title:item.title||'Uten tittel',authors:item.authors||'Ukjent forfatter',year:item.year||undefined,journal:item.journal||'Tidsskrift / Kilde',doi:item.doi||'',design:instrumentNeutralDesign(item.design),studyContext:item.abstract||undefined,sourceName:`${fileName} (${f.toUpperCase()})`,verdict:item.verdict,items:item.items}));}const names:Record<SupportedImportFormat,string>={ris:'RIS (EndNote, Zotero, Covidence, Rayyan)',bibtex:'BibTeX',json:'JSON',csv:'CSV',tsv:'TSV',pubmed:'PubMed/MEDLINE',document:'Forskningsdokument',unknown:'Ukjent'};return{format:f,formatName:names[f],totalParsed:items.length,newArticles:finalArticles,duplicatesCount,warnings};}

  public static parseRis(text:string):ImportPreviewItem[]{const blocks=text.replace(/^\uFEFF/,'').split(/(?=^TY\s{1,2}-\s+)/m).filter(b=>/^TY\s{1,2}-\s+/m.test(b));return blocks.map((entry,i)=>{let title='',journal='',doi='',abstract='',year:number|undefined;const authors:string[]=[];for(const line of entry.split(/\r?\n/)){const m=line.match(/^([A-Z0-9]{2})\s{1,2}-\s*(.*)$/);if(!m)continue;const [tag,val]=[m[1],m[2].trim()];if(tag==='TI'||tag==='T1')title=val;else if(tag==='AU'||tag==='A1'||tag==='A2')authors.push(val);else if(tag==='PY'||tag==='Y1'||tag==='DA'){const y=val.match(/\b(19\d{2}|20\d{2})\b/);if(y)year=Number(y[1]);}else if(['JO','JF','JA','T2','J2'].includes(tag))journal=val;else if(tag==='DO'||tag==='DI')doi=val.replace(/^https?:\/\/doi\.org\//i,'').trim();else if(tag==='AB'||tag==='N2')abstract=val;}return{ id:generateUniqueId('ris'),title:title||`Artikkel #${i+1}`,authors:authors.length?authors.join('; '):'Ukjent forfatter',year:year??new Date().getFullYear(),journal:journal||'Tidsskrift / Kilde',doi,design:'',abstract};}).filter(i=>i.title||i.authors||i.doi);}
  public static parseBibtex(text:string):ImportPreviewItem[]{const out:ImportPreviewItem[]=[];const re=/@([a-zA-Z]+)\s*\{\s*([^,]+),([\s\S]*?)(?=\n@[a-zA-Z]+\s*\{|\s*$)/g;let m:RegExpExecArray|null;let i=0;while((m=re.exec(text))){i++;const b=m[3],get=(f:string)=>{const q=b.match(new RegExp(`${f}\\s*=\\s*[{"]([\\s\\S]*?)[}"]`,'i'));return q?q[1].replace(/\s+/g,' ').trim():''};const title=get('title')||get('booktitle'),author=get('author')||get('editor'),year=Number(get('year'))||new Date().getFullYear(),journal=get('journal')||get('publisher')||get('school'),doi=get('doi').replace(/^https?:\/\/doi\.org\//i,'');if(title||author||doi)out.push({id:generateUniqueId('bib'),title:title||`BibTeX #${i}`,authors:author.replace(/\s+and\s+/g,'; ')||'Ukjent forfatter',year,journal:journal||'Vitenskapelig publikasjon',doi,design:instrumentNeutralDesign(undefined),abstract:get('abstract')||get('note')});}return out;}
  public static parseJson(text:string):ImportPreviewItem[]{const parsed=JSON.parse(text) as unknown;const list=Array.isArray(parsed)?parsed:(parsed&&typeof parsed==='object'&&'articles' in parsed&&Array.isArray((parsed as Record<string,unknown>).articles)?(parsed as Record<string,unknown>).articles:[]);return(list as Record<string,unknown>[]).map((x,i)=>({id:typeof x.id==='string'?x.id:generateUniqueId('json'),title:typeof x.title==='string'?x.title:`Oppføring #${i+1}`,authors:typeof x.authors==='string'?x.authors:'Ukjent forfatter',year:typeof x.year==='number'?x.year:new Date().getFullYear(),journal:typeof x.journal==='string'?x.journal:'Tidsskrift / Kilde',doi:typeof x.doi==='string'?x.doi:'',design:typeof x.design==='string'?x.design:'',abstract:typeof x.abstract==='string'?x.abstract:undefined}));}
  private static parseDelimited(text:string,delimiter:string):ImportPreviewItem[]{const rows=text.split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const header=rows[0].split(delimiter).map(x=>x.trim().toLowerCase());const getIndex=(names:string[])=>header.findIndex(h=>names.includes(h));const ti=getIndex(['title','tittel']),au=getIndex(['authors','author','forfatter']),ye=getIndex(['year','år','date']),jo=getIndex(['journal','tidsskrift','source']),doIdx=getIndex(['doi','url','link']),de=getIndex(['design','metod','type']);return rows.slice(1).map((row,i)=>{const c=row.split(delimiter).map(x=>x.trim().replace(/^"|"$/g,''));const y=ye>=0?Number(c[ye]):NaN;return{id:generateUniqueId('delim'),title:ti>=0?c[ti]||`Oppføring #${i+1}`:`Oppføring #${i+1}`,authors:au>=0?c[au]||'Ukjent forfatter':'Ukjent forfatter',year:Number.isFinite(y)&&y?y:new Date().getFullYear(),journal:jo>=0?c[jo]||'Tidsskrift / Kilde':'Tidsskrift / Kilde',doi:doIdx>=0?(c[doIdx]||'').replace(/^https?:\/\/doi\.org\//i,''):'',design:de>=0?instrumentNeutralDesign(c[de]):instrumentNeutralDesign(undefined),};});}
  public static parsePubmed(text:string):ImportPreviewItem[]{return text.split(/(?=^PMID-?\s+)/m).filter(Boolean).map((entry,i)=>{let title='',journal='',doi='',abstract='';let year=new Date().getFullYear();const authors:string[]=[];for(const line of entry.split(/\r?\n/)){const m=line.match(/^([A-Z]{2,4})\s*-\s*(.*)$/);if(!m)continue;const t=m[1],v=m[2].trim();if(t==='TI')title=v;else if(t==='AU'||t==='FAU')authors.push(v);else if(t==='DP'){const y=v.match(/\b(19\d{2}|20\d{2})\b/);if(y)year=Number(y[1]);}else if(t==='JT'||t==='TA')journal=v;else if(t==='AID'&&/\[doi\]/i.test(v))doi=v.replace(/\s*\[doi\].*/i,'');else if(t==='AB')abstract=v;}return{id:generateUniqueId('pubmed'),title:title||`PubMed #${i+1}`,authors:authors.join('; ')||'Ukjent forfatter',year,journal:journal||'Tidsskrift / Kilde',doi,design:'',abstract};});}
  public static createDefaultArticle(params:{id?:string;title:string;authors:string;year?:number;journal?:string;doi?:string;design?:string;studyContext?:string;sourceName?:string;verdict?:ArticleAppraisal['overallVerdict'];items?:JBIEvaluationItem[]}):ArticleAppraisal{return{ id:params.id||generateArticleId('art'),instrumentId:undefined,instrumentVersion:undefined,lifecycleStatus:'DRAFT',title:params.title,authors:params.authors,shortCitation:`${params.authors} (${params.year??'u.å.'})`,year:params.year??new Date().getFullYear(),doi:params.doi||'',doiUrl:params.doi?`https://doi.org/${params.doi}`:'',sourceUrl:'',sourceName:params.sourceName||'Import',journal:params.journal||'',volumeIssue:'',pages:'',studyContext:params.studyContext||'',design:instrumentNeutralDesign(params.design),dataCollection:params.design?.trim() ? normalizeMetadata(undefined) : 'Ikke oppgitt',participants:params.design?.trim() ? normalizeMetadata(undefined) : 'Ikke oppgitt',analyticMethod:params.design?.trim() ? normalizeMetadata(undefined) : 'Ikke oppgitt',summaryScore:{ja:0,uklart:0,nei:0,ikkeRelevant:0,total:0},overallVerdict:params.verdict||'Vurder videre',verdictNote:'Ikke forhåndsvurdert. Human metodisk verifikasjon kreves før appraisal.',keyStrength:'Ikke forhåndsvurdert',mainLimitation:'Studiedesign og fulltekst må kontrolleres',apaReference:`${params.authors} (${params.year??'u.å.'}). ${params.title}.`,items:params.items||[],auditTrail:[]};}
}
