import type { ArticleAppraisal, JBIEvaluationItem } from '../types';
import { DocumentParserService } from './documentParserService';
import { generateUniqueId, generateArticleId } from './idGenerator';
import JSZip from 'jszip';

export type SupportedImportFormat='ris'|'bibtex'|'json'|'csv'|'tsv'|'pubmed'|'document'|'unknown';
export type SupportedExportFormat='json'|'zip'|'csv'|'tsv'|'excel'|'word'|'pdf'|'ris'|'bibtex'|'markdown'|'latex'|'txt';
export interface ImportPreviewItem{id:string;title:string;authors:string;year:number;journal:string;doi:string;design:string;abstract?:string;items?:JBIEvaluationItem[];verdict?:ArticleAppraisal['overallVerdict'];isDuplicate?:boolean;}
export interface ImportResult{format:SupportedImportFormat;formatName:string;totalParsed:number;newArticles:ArticleAppraisal[];duplicatesCount:number;warnings:string[];}
export interface ExportOptions{scope:'all'|'included_only'|'selected_only';selectedArticleId?:string;includeJustifications:boolean;includeAuditTrail:boolean;includeEvidenceQuotes:boolean;projectName?:string;}
const normalize=(v?:string|null)=>v?.trim()||'';
const csvEscape=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;

export class ImportExportService{
  public static detectFormat(content:string,fileName?:string):SupportedImportFormat{const t=content.trim(),n=(fileName??'').toLowerCase();if(/\.ris$/.test(n))return'ris';if(/\.(bib|bibtex)$/.test(n))return'bibtex';if(/\.json$/.test(n))return'json';if(/\.csv$/.test(n))return'csv';if(/\.(tsv|tab)$/.test(n))return'tsv';if(/\.(nbib|medline)$/.test(n))return'pubmed';if(/\.(pdf|docx|txt|md|rtf)$/.test(n))return'document';if(t.startsWith('{')||t.startsWith('[')){try{JSON.parse(t);return'json';}catch{}}if(/^TY\s{1,2}-\s+/m.test(t))return'ris';if(/@(article|book|inproceedings|misc|phdthesis|techreport)\s*\{/i.test(t))return'bibtex';if(/^(PMID|PMID-|TI\s{1,2}-|AU\s{1,2}-)/m.test(t))return'pubmed';const first=t.split(/\r?\n/,1)[0]??'';if(first.includes('\t'))return'tsv';if(/[;,]/.test(first))return'csv';return'unknown';}

  public static async parseImport(content:string|ArrayBuffer,fileName:string,existingArticles:ArticleAppraisal[]=[]):Promise<ImportResult>{
    const existingDois=new Set(existingArticles.map(a=>normalize(a.doi).toLowerCase()).filter(Boolean));
    const existingTitles=new Set(existingArticles.map(a=>normalize(a.title).toLowerCase()).filter(Boolean));
    if(typeof content!=='string'){
      const parsed=await DocumentParserService.parseFile({name:fileName,size:content.byteLength,content});
      const article=this.createDefaultArticle({id:generateArticleId('art'),title:parsed.metadata.title,authors:parsed.metadata.authors,year:parsed.metadata.year,journal:parsed.metadata.journal,doi:parsed.metadata.doi,design:parsed.metadata.studyDesignDetected,studyContext:parsed.metadata.abstract,sourceName:fileName});
      const duplicate=Boolean(normalize(article.doi)&&existingDois.has(normalize(article.doi).toLowerCase()))||Boolean(normalize(article.title)&&existingTitles.has(normalize(article.title).toLowerCase()));
      return{format:'document',formatName:'Forskningsdokument',totalParsed:1,newArticles:[article],duplicatesCount:duplicate?1:0,warnings:parsed.isScannedOrImageOnly?['Dokumentet mangler tilgjengelig tekstlag og krever manuell/OCR-gjennomgang.']:[]};
    }
    const format=this.detectFormat(content,fileName);let items:ImportPreviewItem[]=[];const warnings:string[]=[];
    switch(format){case'ris':items=this.parseRis(content);break;case'bibtex':items=this.parseBibtex(content);break;case'json':items=this.parseJson(content);break;case'csv':items=this.parseDelimited(content,',');break;case'tsv':items=this.parseDelimited(content,'\t');break;case'pubmed':items=this.parsePubmed(content);break;default:{const m=DocumentParserService.extractMetadata(content,fileName);items=[{id:generateArticleId('art'),title:m.title,authors:m.authors,year:m.year,journal:m.journal,doi:m.doi,design:m.studyDesignDetected,abstract:m.abstract}];warnings.push('Ustrukturert tekst importert med heuristisk metadataekstraksjon; studiedesign må verifiseres.');}}
    let duplicatesCount=0;const newArticles=items.map(item=>{const dup=Boolean(normalize(item.doi)&&existingDois.has(normalize(item.doi).toLowerCase()))||Boolean(normalize(item.title)&&existingTitles.has(normalize(item.title).toLowerCase()));if(dup)duplicatesCount++;return this.createDefaultArticle({id:item.id||generateArticleId('art'),title:item.title||'Uten tittel',authors:item.authors||'Ukjent forfatter',year:item.year,journal:item.journal,doi:item.doi,design:item.design,studyContext:item.abstract,sourceName:`${fileName} (${format.toUpperCase()})`,verdict:item.verdict,items:item.items});});
    const names:Record<SupportedImportFormat,string>={ris:'RIS',bibtex:'BibTeX',json:'JSON',csv:'CSV',tsv:'TSV',pubmed:'PubMed/MEDLINE',document:'Forskningsdokument',unknown:'Ukjent'};return{format,formatName:names[format],totalParsed:newArticles.length,newArticles,duplicatesCount,warnings};
  }

  public static parseRis(text:string):ImportPreviewItem[]{const blocks=text.replace(/^\uFEFF/,'').split(/(?=^TY\s{1,2}-\s+)/m).filter(b=>/^TY\s{1,2}-\s+/m.test(b));return blocks.map((entry,i)=>{let title='',journal='',doi='',abstract='';let year=new Date().getFullYear();const authors:string[]=[];for(const line of entry.split(/\r?\n/)){const m=line.match(/^([A-Z0-9]{2})\s{1,2}-\s*(.*)$/);if(!m)continue;const tag=m[1],value=m[2].trim();if(tag==='TI'||tag==='T1')title=value;else if(tag==='AU'||tag==='A1'||tag==='A2')authors.push(value);else if(['PY','Y1','DA'].includes(tag)){const y=value.match(/\b(19\d{2}|20\d{2})\b/);if(y)year=Number(y[1]);}else if(['JO','JF','JA','T2','J2'].includes(tag))journal=value;else if(['DO','DI'].includes(tag))doi=value.replace(/^https?:\/\/doi\.org\//i,'').trim();else if(['AB','N2'].includes(tag))abstract=value;}return{id:generateUniqueId('ris'),title:title||`Artikkel #${i+1}`,authors:authors.join('; ')||'Ukjent forfatter',year,journal:journal||'Tidsskrift / Kilde',doi,design:'',abstract};});}
  public static parseBibtex(text:string):ImportPreviewItem[]{const out:ImportPreviewItem[]=[];const re=/@([a-zA-Z]+)\s*\{\s*[^,]+,([\s\S]*?)(?=\n@[a-zA-Z]+\s*\{|\s*$)/g;let match:RegExpExecArray|null;let index=0;while((match=re.exec(text))){index++;const body=match[2],get=(key:string)=>{const m=body.match(new RegExp(`${key}\\s*=\\s*[{"]([\\s\\S]*?)[}"]`,`i`));return m?m[1].replace(/\s+/g,' ').trim():'';},title=get('title')||get('booktitle'),author=get('author')||get('editor'),year=Number(get('year'))||new Date().getFullYear(),journal=get('journal')||get('publisher')||get('school'),doi=get('doi').replace(/^https?:\/\/doi\.org\//i,'');if(title||author||doi)out.push({id:generateUniqueId('bib'),title:title||`BibTeX #${index}`,authors:author.replace(/\s+and\s+/g,'; ')||'Ukjent forfatter',year,journal:journal||'Vitenskapelig publikasjon',doi,design:'',abstract:get('abstract')||get('note')});}return out;}
  public static parseJson(text:string):ImportPreviewItem[]{const parsed=JSON.parse(text) as unknown;const values=Array.isArray(parsed)?parsed:(parsed&&typeof parsed==='object'&&Array.isArray((parsed as Record<string,unknown>).articles)?(parsed as Record<string,unknown>).articles:[]);return(values as Record<string,unknown>[]).map((x,i)=>({id:typeof x.id==='string'?x.id:generateUniqueId('json'),title:typeof x.title==='string'?x.title:`Oppføring #${i+1}`,authors:typeof x.authors==='string'?x.authors:'Ukjent forfatter',year:typeof x.year==='number'?x.year:new Date().getFullYear(),journal:typeof x.journal==='string'?x.journal:'Tidsskrift / Kilde',doi:typeof x.doi==='string'?x.doi:'',design:typeof x.design==='string'?x.design:'',abstract:typeof x.abstract==='string'?x.abstract:undefined}));}
  private static parseDelimited(text:string,delimiter:string):ImportPreviewItem[]{const rows=text.split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const header=this.parseDelimitedLine(rows[0],delimiter).map(x=>x.trim().toLowerCase());const index=(names:string[])=>header.findIndex(h=>names.includes(h));const ti=index(['title','tittel']),au=index(['authors','author','forfatter']),ye=index(['year','år','date']),jo=index(['journal','tidsskrift','source']),doi=index(['doi','doi/url','url','link']),de=index(['design','studydesign','metod','type']);return rows.slice(1).map((row,i)=>{const cells=this.parseDelimitedLine(row,delimiter),yearValue=ye>=0?Number(cells[ye]):NaN;return{id:generateUniqueId('delim'),title:ti>=0?cells[ti]||`Oppføring #${i+1}`:`Oppføring #${i+1}`,authors:au>=0?cells[au]||'Ukjent forfatter':'Ukjent forfatter',year:Number.isFinite(yearValue)&&yearValue>0?yearValue:new Date().getFullYear(),journal:jo>=0?cells[jo]||'Tidsskrift / Kilde':'Tidsskrift / Kilde',doi:doi>=0?normalize(cells[doi]).replace(/^https?:\/\/doi\.org\//i,''):'',design:de>=0?cells[de]||'':''};});}
  private static parseDelimitedLine(line:string,delimiter:string):string[]{const out:string[]=[];let field='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(ch===delimiter&&!quoted){out.push(field);field='';}else field+=ch;}out.push(field);return out.map(v=>v.trim());}
  public static parsePubmed(text:string):ImportPreviewItem[]{return text.split(/(?=^PMID-?\s+)/m).filter(Boolean).map((entry,i)=>{let title='',journal='',doi='',abstract='';let year=new Date().getFullYear();const authors:string[]=[];for(const line of entry.split(/\r?\n/)){const m=line.match(/^([A-Z]{2,4})\s*-\s*(.*)$/);if(!m)continue;const tag=m[1],value=m[2].trim();if(tag==='TI')title=value;else if(tag==='AU'||tag==='FAU')authors.push(value);else if(tag==='DP'){const y=value.match(/\b(19\d{2}|20\d{2})\b/);if(y)year=Number(y[1]);}else if(tag==='JT'||tag==='TA')journal=value;else if(tag==='AID'&&/\[doi\]/i.test(value))doi=value.replace(/\s*\[doi\].*/i,'');else if(tag==='AB')abstract=value;}return{id:generateUniqueId('pubmed'),title:title||`PubMed #${i+1}`,authors:authors.join('; ')||'Ukjent forfatter',year,journal:journal||'Tidsskrift / Kilde',doi,design:'',abstract};});}

  public static createDefaultArticle(params:{id?:string;title:string;authors:string;year?:number;journal?:string;doi?:string;design?:string;studyContext?:string;sourceName?:string;verdict?:ArticleAppraisal['overallVerdict'];items?:JBIEvaluationItem[]}):ArticleAppraisal{const authors=normalize(params.authors)||'Ukjent forfatter';const title=normalize(params.title)||'Uten tittel';const year=params.year&&Number.isFinite(params.year)?params.year:new Date().getFullYear();const doi=normalize(params.doi).replace(/^https?:\/\/doi\.org\//i,'');const design=normalize(params.design);return{id:params.id||generateArticleId('art'),instrumentId:undefined,instrumentVersion:undefined,lifecycleStatus:'DRAFT',title,authors,shortCitation:`${authors.split(';')[0]?.trim()||authors} (${year})`,year,journal:normalize(params.journal),doi,doiUrl:doi?`https://doi.org/${doi}`:'',sourceUrl:'',sourceName:params.sourceName||'Import',studyContext:params.studyContext||'',design,dataCollection:'Ikke oppgitt',participants:'Ikke oppgitt',analyticMethod:'Ikke oppgitt',summaryScore:{ja:0,uklart:0,nei:0,ikkeRelevant:0,total:0},overallVerdict:params.verdict||'Vurder videre',verdictNote:'Ikke forhåndsvurdert. Human metodisk verifikasjon kreves før appraisal.',keyStrength:'Ikke forhåndsvurdert',mainLimitation:'Studiedesign og fulltekst må kontrolleres',apaReference:`${authors} (${year}). ${title}.`,items:params.items||[],auditTrail:[]};}
}
export function createCsvExport(rows:Record<string,unknown>[],columns:string[]):string{return[columns.map(csvEscape).join(','),...rows.map(row=>columns.map(c=>csvEscape(row[c])).join(','))].join('\n');}
export async function createZipBundle(files:Record<string,string>):Promise<Blob>{const zip=new JSZip();for(const [name,content] of Object.entries(files))zip.file(name,content);return zip.generateAsync({type:'blob'});}
