import type { IMRaDAnalysisResult, IMRaDSectionAnalysis, IMRaDSectionKey } from '../types';

type SectionRule = { key: IMRaDSectionKey; label: string; headings: RegExp[]; keywords: RegExp[]; required: boolean; };
const RULES: SectionRule[] = [
  { key:'introduction', label:'Introduction', headings:[/^\s*(?:1[.)\s-]*)?(?:introduction|background|bakgrunn|innledning)\s*$/i,/^\s*(?:aim|objectives|purpose|formÃ¥l|hensikt)\s*$/i], keywords:[/\bintroduction\b/i,/\bbackground\b/i,/\baim\b/i,/\bobjectives?\b/i,/\bpurpose\b/i,/\bformÃ¥l\b/i,/\bproblemstilling\b/i], required:true },
  { key:'methods', label:'Methods', headings:[/^\s*(?:2[.)\s-]*)?(?:methods?|methodology|materials and methods|metode|metodologi|materiale og metode)\s*$/i,/^\s*(?:study design|research design|studiedesign)\s*$/i], keywords:[/\bmethods?\b/i,/\bmethodology\b/i,/\bstudy design\b/i,/\bparticipants?\b/i,/\bsample\b/i,/\bdata collection\b/i,/\bdata analysis\b/i,/\bmetode\b/i], required:true },
  { key:'results', label:'Results', headings:[/^\s*(?:3[.)\s-]*)?(?:results?|findings?|resultater|funn)\s*$/i], keywords:[/\bresults?\b/i,/\bfindings?\b/i,/\bresultater\b/i,/\bfunn\b/i,/\bprimary outcome\b/i,/\bsecondary outcome\b/i], required:true },
  { key:'discussion', label:'Discussion', headings:[/^\s*(?:4[.)\s-]*)?(?:discussion|interpretation|drÃ¸fting|diskusjon)\s*$/i,/^\s*(?:strengths and limitations|limitations|styrker og begrensninger|begrensninger)\s*$/i], keywords:[/\bdiscussion\b/i,/\binterpretation\b/i,/\blimitations?\b/i,/\bstrengths?\b/i,/\bimplications?\b/i,/\bdiskusjon\b/i,/\bdrÃ¸fting\b/i], required:true }
];
function normalise(text:string):string{return text.replace(/\u00a0/g,' ').replace(/\r\n/g,'\n').trim();}
function scoreSection(content:string,rule:SectionRule):number{const value=normalise(content);if(!value)return 0;const keywordHits=rule.keywords.reduce((s,p)=>s+(p.test(value)?1:0),0);const headingHits=rule.headings.reduce((s,p)=>s+(p.test(value)?1:0),0);const lengthSignal=Math.min(1,value.length/1200);return Math.min(1,0.45*Math.min(1,keywordHits/3)+0.35*Math.min(1,headingHits)+0.2*lengthSignal);}
function extractByHeadings(text:string):Record<IMRaDSectionKey,string>{const lines=normalise(text).split('\n');const sections:Partial<Record<IMRaDSectionKey,string[]>>={};let current:IMRaDSectionKey|undefined;for(const line of lines){const match=RULES.find(rule=>rule.headings.some(pattern=>pattern.test(line.trim())));if(match){current=match.key;sections[current]=sections[current]??[];continue;}if(current)sections[current]!.push(line);}return{introduction:sections.introduction?.join('\n').trim()??'',methods:sections.methods?.join('\n').trim()??'',results:sections.results?.join('\n').trim()??'',discussion:sections.discussion?.join('\n').trim()??''};}
export class IMRaDAnalysisService{public static analyze(text:string,fileName='research-document'):IMRaDAnalysisResult{const clean=normalise(text);const headingSections=extractByHeadings(clean);const analyses:IMRaDSectionAnalysis[]=RULES.map(rule=>{const content=headingSections[rule.key];const hasContent=content.length>=80;const confidence=hasContent?scoreSection(content,rule):0;const explicitHeading=clean.split('\n').some(line=>rule.headings.some(pattern=>pattern.test(line.trim())));return{key:rule.key,label:rule.label,detected:hasContent,explicitHeading,confidence:Number(confidence.toFixed(3)),characterCount:content.length,wordCount:content?content.split(/\s+/).filter(Boolean).length:0,evidencePreview:content.slice(0,500),status:hasContent&&explicitHeading?'DETECTED':'MISSING'};});const detected=analyses.filter(x=>x.detected).length;const explicit=analyses.filter(x=>x.explicitHeading).length;const missing=analyses.filter(x=>!x.detected).map(x=>x.label);return{fileName,standard:'IMRaD',standardDescription:'Introduction, Methods, Results and Discussion',analyzedAt:new Date().toISOString(),complete:detected===4,explicitComplete:explicit===4,detectedSectionCount:detected,explicitHeadingCount:explicit,confidence:Number((analyses.reduce((s,x)=>s+x.confidence,0)/analyses.length).toFixed(3)),sections:analyses,missingSections:missing,limitations:['Automatisk seksjonsgjenkjenning er en strukturanalyse og er ikke en metodisk kvalitetsvurdering.','En seksjon som ikke finnes i tekstuttrekket skal ikke tolkes som at artikkelen mangler seksjonen.','IMRaD passer ikke nÃ¸dvendigvis uendret for alle studiedesign; strukturkrav mÃ¥ vurderes mot artikkeltype og rapporteringsstandard.'],methodologicalNotice:'IMRaD-analysen skal brukes sammen med relevant rapporteringsstandard og kritisk appraisal-instrument. Den genererer ikke kvalitetspoeng eller et metodisk ja/nei-verdict.'};}}


