import { AppraisalInstrument } from '../types';
import { MASTER_INSTRUMENTS_REGISTRY } from '../data/masterRegistry';
import { isInstrumentImplemented } from './assessmentEngines';

export type VerificationStatusType = 'VERIFIED' | 'PARTIALLY_VERIFIED' | 'UNVERIFIED';
export interface OfficialRequirementCheck { id:string; name:string; category:'SOURCE'|'VERSION'|'METHOD_FUNCTION'|'SCORING_INTEGRITY'|'DESIGN_GATE'|'LICENSE'|'ENGINE'; status:'MET'|'PARTIAL'|'UNMET'; officialStandard:string; localImplementation:string; details:string; }
export interface MethodAuditItem { instrumentId:string; instrumentName:string; shortName:string; version:string; edition:string; year:number; publisher:string; governingBody:string; officialSource:string; primaryPublication:string; doi?:string; sourceProvenanceStatus:'PASS'|'FAIL'; versionStatus:'PASS'|'FAIL'; scoringIntegrityStatus:'PASS'|'FAIL'; studyDesignGatingStatus:'PASS'|'FAIL'; licenseAuditStatus:'PASS'|'FAIL'; engineImplementationStatus:'PASS'|'FAIL'; overallStatus:VerificationStatusType; compliancePercentage:number; passedChecksCount:number; totalChecksCount:number; requirementChecks:OfficialRequirementCheck[]; notes:string[]; }
export interface ComprehensiveAuditReport { timestamp:string; totalInstruments:number; verifiedCount:number; partiallyVerifiedCount:number; unverifiedCount:number; overallSystemAudit:'PASS'|'FAIL'; instrumentAudits:MethodAuditItem[]; auditsSummary:{sourceAudit:'PASS'|'FAIL';versionAudit:'PASS'|'FAIL';scoringAudit:'PASS'|'FAIL';studyDesignAudit:'PASS'|'FAIL';aiSafetyAudit:'PASS'|'FAIL';evidenceTraceabilityAudit:'PASS'|'FAIL';auditTrailAudit:'PASS'|'FAIL';exportIntegrityAudit:'PASS'|'FAIL'}; }

export class MethodIntegrityService {
  public static verifyInstrument(inst:AppraisalInstrument):MethodAuditItem {
    const checks:OfficialRequirementCheck[]=[]; const notes:string[]=[];
    const sourceMet=Boolean(inst.officialSource?.trim())&&Boolean(inst.primaryPublication?.trim())&&Boolean(inst.publisher?.trim())&&(inst.authorityLevel==='original-source'||inst.authorityLevel==='official-manual'||inst.authorityLevel==='gold-standard');
    checks.push({id:'REQ-SOURCE-PROVENANCE',name:'Offisiell kildeopprinnelse',category:'SOURCE',status:sourceMet?'MET':'UNMET',officialStandard:'Primærkilde/autorativ manual og tydelig utgiver.',localImplementation:`${inst.publisher} | ${inst.primaryPublication}`,details:sourceMet?'Kildeinformasjon finnes.':'Kildeinformasjon er ufullstendig.'});
    const versionMet=Boolean(inst.version?.trim())&&Number.isInteger(inst.year)&&inst.year>=2000&&Boolean(inst.edition?.trim());
    checks.push({id:'REQ-VERSION-LOCK',name:'Versjonslås',category:'VERSION',status:versionMet?'MET':'UNMET',officialStandard:'Eksplisitt versjon, år og utgave.',localImplementation:`${inst.version} (${inst.year}) | ${inst.edition}`,details:versionMet?'Versjon er eksplisitt registrert.':'Versjonsinformasjon er ufullstendig.'});
    const functionMet=Boolean(inst.methodologicalFunction)&&Boolean(inst.unitOfAnalysis?.trim())&&Boolean(inst.academicOutputFormat?.trim())&&Array.isArray(inst.prohibitedAcademicPractices);
    checks.push({id:'REQ-METHOD-FUNCTION',name:'Metodisk funksjon',category:'METHOD_FUNCTION',status:functionMet?'MET':'UNMET',officialStandard:'Instrumentets formål, analyseenhet og metodiske avgrensning må være eksplisitt.',localImplementation:`${inst.methodologicalFunction} | ${inst.unitOfAnalysis}`,details:functionMet?'Funksjonskontrakten er spesifisert.':'Funksjonskontrakten er ufullstendig.'});
    let scoringStatus:'MET'|'PARTIAL'|'UNMET'='MET'; let scoringDetails='Generisk instrumentmetadata er kontrollert.';
    if(inst.id==='amstar-2' && (inst.itemCount!==16||inst.criticalDomains?.length!==7)) { scoringStatus='UNMET'; scoringDetails='AMSTAR 2 krever 16 items og 7 kritiske domener.'; }
    if(inst.id==='agree-ii' && (inst.itemCount!==23||inst.criticalDomains?.length!==6)) { scoringStatus='UNMET'; scoringDetails='AGREE II krever 23 items og 6 domener.'; }
    if(inst.id==='jbi-qualitative-2017' && (inst.itemCount!==10||inst.scoringModel!=='qualitative-judgement')) { scoringStatus='UNMET'; scoringDetails='JBI Qualitative krever 10 items og kvalitativ judgment.'; }
    checks.push({id:'REQ-SCORING-INTEGRITY',name:'Scoringsintegritet',category:'SCORING_INTEGRITY',status:scoringStatus,officialStandard:'Ingen uautorisert totalscore eller metodisk flattening.',localImplementation:`${inst.scoringModel} | ${inst.itemCount} items`,details:scoringDetails});
    const designMet=Array.isArray(inst.targetStudyDesign)&&inst.targetStudyDesign.length>0&&Boolean(inst.targetPopulationOrContext?.trim());
    checks.push({id:'REQ-DESIGN-GATING',name:'Studiedesign-gating',category:'DESIGN_GATE',status:designMet?'MET':'UNMET',officialStandard:'Instrumentet skal ha eksplisitt målgruppe/studiedesign.',localImplementation:inst.targetStudyDesign.join(', '),details:designMet?'Gating-metadata finnes.':'Gating-metadata mangler.'});
    const licenseMet=Boolean(inst.licenseStatus?.trim())&&Boolean(inst.sourceAttribution?.trim())&&Boolean(inst.usagePermission?.trim());
    checks.push({id:'REQ-LICENSE-ATTRIBUTION',name:'Lisens og attribusjon',category:'LICENSE',status:licenseMet?'MET':'UNMET',officialStandard:'Lisens, bruk og attribusjon må være eksplisitt oppgitt.',localImplementation:`${inst.licenseStatus} | ${inst.sourceAttribution}`,details:licenseMet?'Lisensinformasjon finnes.':'Lisensinformasjon er ufullstendig.'});
    const engineMet=isInstrumentImplemented(inst); checks.push({id:'REQ-DETERMINISTIC-ENGINE',name:'Runtime-motor',category:'ENGINE',status:engineMet?'MET':'UNMET',officialStandard:'Instrumentet må være eksplisitt implementert i runtime-kode; registrering alene er ikke nok.',localImplementation:engineMet?'Registrert som implementert.':'Kun registrert; ingen eksplisitt runtime-kapasitet.',details:engineMet?'Implementasjonskapabilitet finnes.':'Instrumentet er ikke markert som runtime-implementert.'});
    const total=checks.length,met=checks.filter(c=>c.status==='MET').length,partial=checks.filter(c=>c.status==='PARTIAL').length,unmet=checks.filter(c=>c.status==='UNMET').length;
    const overallStatus:VerificationStatusType=unmet>0?'UNVERIFIED':partial>0?'PARTIALLY_VERIFIED':'VERIFIED';
    const compliancePercentage=Math.round(((met+partial*0.5)/total)*100);
    if(unmet>0)notes.push('Audit kan ikke erklære instrumentet verifisert når én eller flere obligatoriske kontroller feiler.');
    return {instrumentId:inst.id,instrumentName:inst.name,shortName:inst.shortName,version:inst.version,edition:inst.edition,year:inst.year,publisher:inst.publisher,governingBody:inst.governingBody,officialSource:inst.officialSource,primaryPublication:inst.primaryPublication,doi:inst.doi,sourceProvenanceStatus:checks[0].status==='MET'?'PASS':'FAIL',versionStatus:checks[1].status==='MET'?'PASS':'FAIL',scoringIntegrityStatus:checks[3].status==='MET'?'PASS':'FAIL',studyDesignGatingStatus:checks[4].status==='MET'?'PASS':'FAIL',licenseAuditStatus:checks[5].status==='MET'?'PASS':'FAIL',engineImplementationStatus:checks[6].status==='MET'?'PASS':'FAIL',overallStatus,compliancePercentage,passedChecksCount:met,totalChecksCount:total,requirementChecks:checks,notes};
  }
  public static runFullSystemAudit():ComprehensiveAuditReport {
    const instrumentAudits=MASTER_INSTRUMENTS_REGISTRY.map(inst=>this.verifyInstrument(inst));
    const all=(key:keyof MethodAuditItem)=>instrumentAudits.every(item=>item[key]==='PASS');
    const verifiedCount=instrumentAudits.filter(x=>x.overallStatus==='VERIFIED').length;
    const partiallyVerifiedCount=instrumentAudits.filter(x=>x.overallStatus==='PARTIALLY_VERIFIED').length;
    const unverifiedCount=instrumentAudits.filter(x=>x.overallStatus==='UNVERIFIED').length;
    return {timestamp:new Date().toISOString(),totalInstruments:instrumentAudits.length,verifiedCount,partiallyVerifiedCount,unverifiedCount,overallSystemAudit:unverifiedCount===0&&partiallyVerifiedCount===0?'PASS':'FAIL',instrumentAudits,auditsSummary:{sourceAudit:all('sourceProvenanceStatus')?'PASS':'FAIL',versionAudit:all('versionStatus')?'PASS':'FAIL',scoringAudit:all('scoringIntegrityStatus')?'PASS':'FAIL',studyDesignAudit:all('studyDesignGatingStatus')?'PASS':'FAIL',aiSafetyAudit:'FAIL',evidenceTraceabilityAudit:'FAIL',auditTrailAudit:'FAIL',exportIntegrityAudit:'FAIL'}};
  }
  public static generateMarkdownAuditReport(report:ComprehensiveAuditReport):string { let md=`# EVIDENCE APPRAISAL TOOL – METHODOLOGICAL QA & AUDIT REPORT\n\n`; md+=`**Audit Dato:** ${report.timestamp.split('T')[0]} | **Status:** ${report.overallSystemAudit}\n`; md+=`**Totalt instrumenter:** ${report.totalInstruments} (VERIFIED: ${report.verifiedCount}, PARTIAL: ${report.partiallyVerifiedCount}, UNVERIFIED: ${report.unverifiedCount})\n\n`; md+=`| Instrument | ID | Versjon | Kilde | Scoring | Motor | Status |\n|---|---|---|---|---|---|---|\n`; for(const item of report.instrumentAudits) md+=`| ${item.shortName} | \`${item.instrumentId}\` | ${item.version} | ${item.sourceProvenanceStatus} | ${item.scoringIntegrityStatus} | ${item.engineImplementationStatus} | **${item.overallStatus}** |\n`; return md; }
}
