import { createReferenceRecord, detectDuplicateCandidates, type ReferenceImportFormat, type ReferenceRecord } from './referenceHubService.ts';
export type { ReferenceImportFormat } from './referenceHubService.ts';
type ParsedReference = Partial<ReferenceRecord> & { sourceType?: string };
function field(fields:Record<string,string>,key:string){const value=fields[key];return value?.trim()||undefined;}
function mapAuthors(value?:string){return(value||'').split(/\s+and\s+/i).map(v=>v.trim()).filter(Boolean).join('; ');}
function normalizeAuthors(value:unknown){if(Array.isArray(value))return value.map(item=>typeof item==='string'?item.trim():'').filter(Boolean).join('; ');return String(value??'').trim();}
function normalizeKind(type?:string):ReferenceRecord['kind']{switch((type||'').toLowerCase().trim()){case'book':case'6':return'BOOK';case'report':case'report-type':return'REPORT';case'webpage':case'12':return'WEBPAGE';case'thesis':case'32':return'THESIS';case'article-journal':case'journal article':case'17':case'journal':case'jour':return'JOURNAL_ARTICLE';case'law':return'LAW';case'regulation':return'REGULATION';case'guideline':return'GUIDELINE';default:return'JOURNAL_ARTICLE';}}
function parseRis(input:string):ParsedReference[]{const normalized=input.replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n').trim();if(!normalized)return[];const blocks=normalized.split(/(?=^TY\s*-\s*)/m).filter(block=>/^TY\s*-\s*/im.test(block));return blocks.map(block=>{const fields:Record<string,string>={},authors:string[]=[];for(const line of block.split('\n')){const m=line.match(/^\s*([A-Z0-9]{2})\s*-\s?(.*)$/i);if(!m)continue;const tag=m[1].toUpperCase(),value=m[2].trim();if(tag==='AU'||tag==='A1')authors.push(value);else if(tag!=='ER')fields[tag]=value;}return{title:field(fields,'TI')||field(fields,'T1')||'',authors:authors.join('; '),journal:field(fields,'JO')||field(fields,'T2'),year:Number(field(fields,'PY'))||undefined,volume:field(fields,'VL'),issue:field(fields,'IS'),pages:field(fields,'SP')&&field(fields,'EP')?`${field(fields,'SP')}-${field(fields,'EP')}`:field(fields,'SP'),doi:field(fields,'DO'),issn:field(fields,'SN'),url:field(fields,'UR'),abstract:field(fields,'AB'),sourceType:field(fields,'TY')};});}
function parseBibtex(input:string):ParsedReference[]{return[...input.matchAll(/@([^{]+)\{([^,]+),([\s\S]*?)\n\}/g)].map(m=>{const values:Record<string,string>={};for(const i of m[3].matchAll(/([A-Za-z][\w-]*)\s*=\s*[\{\"]([\s\S]*?)[\}\"]\s*,?/g))values[i[1].toLowerCase()]=i[2].trim();return{id:m[2].trim(),title:values.title||'',authors:mapAuthors(values.author),journal:values.journal,year:Number(values.year)||undefined,volume:values.volume,issue:values.number,pages:values.pages,doi:values.doi,issn:values.issn,url:values.url,publisher:values.publisher,abstract:values.abstract,language:values.language,sourceType:m[1].trim().toLowerCase()};});}
function parseCslJson(input:string):ParsedReference[]{const raw=JSON.parse(input) as unknown;const list=Array.isArray(raw)?raw:[raw];return list.map(v=>{const i=v as Record<string,unknown>;const issued=i.issued as {'date-parts'?:number[][]}|undefined;return{id:typeof i.id==='string'?i.id:undefined,title:typeof i.title==='string'?i.title:'',authors:normalizeAuthors(Array.isArray(i.author)?i.author.map(a=>{const x=a as Record<string,unknown>;return[x.family,x.given].filter(Boolean).join(', ')}):[]),year:Number(issued?.['date-parts']?.[0]?.[0])||undefined,journal:typeof i['container-title']==='string'?i['container-title']:undefined,volume:typeof i.volume==='string'||typeof i.volume==='number'?i.volume:undefined,issue:typeof i.issue==='string'||typeof i.issue==='number'?i.issue:undefined,pages:typeof i.page==='string'?i.page:undefined,doi:typeof i.DOI==='string'?i.DOI:undefined,pmid:typeof i.PMID==='string'?i.PMID:typeof i.pmid==='string'?i.pmid:undefined,pmcid:typeof i.PMCID==='string'?i.PMCID:typeof i.pmcid==='string'?i.pmcid:undefined,isbn:typeof i.ISBN==='string'?i.ISBN:typeof i.isbn==='string'?i.isbn:undefined,issn:typeof i.ISSN==='string'?i.ISSN:typeof i.issn==='string'?i.issn:undefined,url:typeof i.URL==='string'?i.URL:undefined,publisher:typeof i.publisher==='string'?i.publisher:undefined,abstract:typeof i.abstract==='string'?i.abstract:undefined,language:typeof i.language==='string'?i.language:undefined,sourceType:typeof i.type==='string'?i.type:undefined};});}
function parseJson(input:string):ParsedReference[]{const raw=JSON.parse(input) as unknown;if(Array.isArray(raw))return raw as ParsedReference[];if(raw&&typeof raw==='object'&&'records'in raw&&Array.isArray((raw as Record<string,unknown>).records))return(raw as {records:ParsedReference[]}).records;return[raw as ParsedReference];}
function parseCsv(input:string):ParsedReference[]{const rows=input.split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const h=rows[0].split(',').map(v=>v.trim().toLowerCase());return rows.slice(1).map(line=>{const c=line.split(',').map(v=>v.trim().replace(/^"|"$/g,''));const get=(names:string[])=>{const i=h.findIndex(x=>names.includes(x));return i>=0?c[i]||undefined:undefined};return{title:get(['title','ti']),authors:get(['authors','author','au'])?.split(';').map(v=>v.trim()).filter(Boolean).join('; '),journal:get(['journal','jo']),year:Number(get(['year','py']))||undefined,volume:get(['volume','vl']),issue:get(['issue','is']),pages:get(['pages']),doi:get(['doi','do']),pmid:get(['pmid']),pmcid:get(['pmcid']),isbn:get(['isbn']),issn:get(['issn']),url:get(['url','ur']),abstract:get(['abstract','ab'])};});}
export function importReferences(input:string,format:ReferenceImportFormat){const warnings:string[]=[];const errors:string[]=[];try{if(!input.trim())throw new Error('Importfilen er tom.');const parsed=format==='RIS'?parseRis(input):format==='BIBTEX'?parseBibtex(input):format==='CSL_JSON'?parseCslJson(input):format==='ENDNOTE_XML'?[]:format==='CSV'?parseCsv(input):format==='JSON'?parseJson(input):(()=>{throw new Error(`Formatet ${format} krever metadataoppslag eller manuell registrering.`)})();const references=parsed.map((entry,index)=>{const{sourceType,...shared}=entry;return createReferenceRecord({...shared,id:entry.id||`import-${Date.now()}-${index}`,authors:normalizeAuthors(entry.authors),kind:normalizeKind(sourceType),importedFrom:[format]});});if(!parsed.length)warnings.push('Ingen bibliografiske poster ble funnet i importen.');references.forEach((r,i)=>{if(!r.title)warnings.push(`Referanse ${i+1} mangler tittel.`);if(!r.authors.trim())warnings.push(`Referanse ${i+1} mangler forfatter.`);if(r.verification!=='VALIDATED')warnings.push(`Referanse ${i+1} er ikke bibliografisk verifisert.`);});return{references,duplicateCandidates:detectDuplicateCandidates(references),warnings,errors};}catch(e){errors.push(e instanceof Error?e.message:'Importen kunne ikke tolkes.');return{references:[],duplicateCandidates:[],warnings,errors};}}

