import type { AppraisalSession } from '../types/workflow.contracts';
import type { PICO, ScreeningDecision, ReviewComparison, ReviewInstance, ResolvedAppraisal, DualReviewConfig, PRISMAFlow } from '../types/researchWorkflow';
import { AuditTrailService } from './auditTrailService.ts';
import type { Actor } from './sourceIntakeService';

export interface AppraisalWorkflowLookup {
  listByStudy(studyId: string): Array<{ instrumentId: string; session: AppraisalSession }>;
}

export interface AppraisalInstrumentResolver {
  getInstrumentOrNull(instrumentId: string): unknown;
}

export interface ScreeningToAppraisalResult { studyId:string; decision:ScreeningDecision; appraisalSession:AppraisalSession; instrumentId:string; auditEntryId?:string; }
export function inferInstrumentId(studyDesign:string):string { const d=studyDesign.trim().toLowerCase(); if(/(systematisk oversikt|systematic review|meta-analyse|meta analysis)/i.test(d))return'amstar-2'; if(/(retningslinje|guideline|clinical practice guideline)/i.test(d))return'agree-ii'; if(/(rct|randomisert|randomized)/i.test(d))return'casp-rct'; if(/(ikke-randomisert intervensjon|non-randomized intervention|quasi-experimental)/i.test(d))return'robins-i'; if(/(kvalitativ|qualitative)/i.test(d))return'casp-qualitative'; throw new Error(`Studiedesignet Â«${studyDesign||'ukjent'}Â» kan ikke kobles sikkert til et appraisal-instrument. Manuell metodisk avklaring kreves.`); }
export function createScreeningDecision(input:Omit<ScreeningDecision,'timestamp'>):ScreeningDecision{return{...input,timestamp:new Date().toISOString()};}
export function assertEligibleForAppraisal(args:{studyId:string;screening:{studyId:string;decision:string};reviewerId:string}):void{if(args.screening.studyId!==args.studyId)throw new Error('Screening og studie-ID samsvarer ikke.');if(args.screening.decision!=='include'&&args.screening.decision!=='INCLUDED')throw new Error('Kun inkluderte studier kan sendes til appraisal.');if(!args.reviewerId.trim())throw new Error('Reviewer ID er pÃ¥krevd.');}
export async function triggerAppraisalForIncludedStudy(args:{studyId:string;studyDesign:string;screening:ScreeningDecision;reviewerId:string;appraisalStore:AppraisalWorkflowLookup;instrumentResolver:AppraisalInstrumentResolver;audit?:AuditTrailService;actor?:Actor;}):Promise<ScreeningToAppraisalResult>{assertEligibleForAppraisal({studyId:args.studyId,screening:args.screening,reviewerId:args.reviewerId});const instrumentId=inferInstrumentId(args.studyDesign);const instrument=args.instrumentResolver.getInstrumentOrNull(instrumentId);if(!instrument)throw new Error(`Ingen appraisal-instrument funnet for design: ${args.studyDesign}`);const existing=args.appraisalStore.listByStudy(args.studyId).find(item=>item.instrumentId===instrumentId&&item.session.reviewerId===args.reviewerId&&!item.session.locked);if(existing)return{studyId:args.studyId,decision:args.screening,appraisalSession:existing.session,instrumentId};throw new Error('Studien mÃ¥ sendes gjennom canonical research-to-appraisal workflow fÃ¸r appraisal-session kan opprettes.');}
export function compareReviewInstances(first:ReviewInstance,second:ReviewInstance,threshold=0.3):ReviewComparison{if(first.studyId!==second.studyId||first.instrumentId!==second.instrumentId)throw new Error('Reviewerinstansene mÃ¥ gjelde samme studie og instrument.');if(first.reviewerId===second.reviewerId)throw new Error('Dual review krever to forskjellige reviewere.');if(!Number.isFinite(threshold)||threshold<0||threshold>1)throw new Error('Disagreement threshold mÃ¥ vÃ¦re mellom 0 og 1.');if(first.status!=='completed'||second.status!=='completed')throw new Error('Begge reviewerinstanser mÃ¥ vÃ¦re completed fÃ¸r sammenligning.');const itemIds=[...new Set([...Object.keys(first.responses),...Object.keys(second.responses)])];const items=itemIds.map(itemId=>({itemId,reviewer1Score:first.responses[itemId]??null,reviewer2Score:second.responses[itemId]??null,disagreement:first.responses[itemId]!==second.responses[itemId]}));const disagreements=items.filter(i=>i.disagreement).length;const overallDisagreement=itemIds.length?disagreements/itemIds.length:0;return{overallDisagreement,items,requiresArbitration:overallDisagreement>=threshold};}
export function resolveReviewComparison(args:{appraisalId:string;comparison:ReviewComparison;method:DualReviewConfig['arbitrationMethod'];resolvedBy:string;first:ReviewInstance;second:ReviewInstance;rationale?:string;}):ResolvedAppraisal{const consensusResponses:Record<string,string|number|boolean|null>={};const itemIds=[...new Set([...Object.keys(args.first.responses),...Object.keys(args.second.responses)])];for(const id of itemIds){const a=args.first.responses[id]??null,b=args.second.responses[id]??null;consensusResponses[id]=a===b?a:null;}if(!args.resolvedBy.trim())throw new Error('Adjudicator er pÃ¥krevd.');if(!args.appraisalId.trim())throw new Error('Adjudication krever appraisalId.');const disagreement=args.comparison.items.some(i=>i.disagreement);if(disagreement&&!args.rationale?.trim())throw new Error('Adjudication krever begrunnelse.');if((args.comparison.requiresArbitration||disagreement)&&args.method==='autoResolve')throw new Error('autoResolve er ikke tillatt ved appraisal-uenighet.');if(disagreement&&itemIds.some(id=>consensusResponses[id]===null))throw new Error('Alle konfliktitems mÃ¥ ha eksplisitt consensus-respons.');return{appraisalId:args.appraisalId,status:'resolved',resolutionMethod:args.method,resolvedBy:args.resolvedBy,resolvedAt:new Date().toISOString(),disagreements:args.comparison.items,consensusResponses,proposedResponses:{...consensusResponses}};}
export interface DeduplicationCandidate{studyId:string;matchedStudyId:string;key:'doi'|'pmid'|'title';value:string;}
export function findDuplicateStudies(records:Array<{studyId:string;doi?:string;pmid?:string;title?:string}>):DeduplicationCandidate[]{const seen=new Map<string,{studyId:string;key:'doi'|'pmid'|'title';value:string}>(),duplicates:DeduplicationCandidate[]=[];for(const r of records){const keys:Array<{key:'doi'|'pmid'|'title';value:string}>=[];if(r.doi?.trim())keys.push({key:'doi',value:r.doi.trim().toLowerCase()});if(r.pmid?.trim())keys.push({key:'pmid',value:r.pmid.trim()});if(r.title?.trim())keys.push({key:'title',value:r.title.trim().toLowerCase().replace(/\s+/g,' ')});for(const c of keys){const k=`${c.key}:${c.value}`,prev=seen.get(k);if(prev&&prev.studyId!==r.studyId)duplicates.push({studyId:r.studyId,matchedStudyId:prev.studyId,key:c.key,value:c.value});else seen.set(k,{studyId:r.studyId,...c});}}return duplicates;}
export interface DeduplicationDecision{recordId:string;canonicalStudyId:string;duplicateOfRecordId?:string;reason:'doi'|'pmid'|'title';reviewerId:string;timestamp:string;}
export function applyDeduplicationDecisions(records:Array<{studyId:string;doi?:string;pmid?:string;title?:string}>,decisions:DeduplicationDecision[]):{canonicalRecords:typeof records;unresolved:typeof records;duplicatesRemoved:number}{const duplicateIds=new Set(decisions.filter(d=>d.duplicateOfRecordId).map(d=>d.recordId));const canonicalIds=new Set(records.map(r=>r.studyId));if(decisions.some(d=>!canonicalIds.has(d.recordId)||!canonicalIds.has(d.canonicalStudyId)||(d.duplicateOfRecordId&&!canonicalIds.has(d.duplicateOfRecordId))))throw new Error('Deduplication contains references to unknown records.');const canonicalRecords=records.filter(r=>!duplicateIds.has(r.studyId));const resolvedIds=new Set(decisions.flatMap(d=>[d.recordId,d.canonicalStudyId]));return{canonicalRecords,unresolved:canonicalRecords.filter(r=>!resolvedIds.has(r.studyId)),duplicatesRemoved:duplicateIds.size};}
export function buildPrismaFlow(store:{screening:ScreeningDecision[];appraisalSessions:AppraisalSession[];duplicatesRemoved?:number}):PRISMAFlow{const screening=store.screening,included=screening.filter(i=>i.decision==='include'),excluded=screening.filter(i=>i.decision==='exclude');const eligibleIds=new Set(screening.filter(i=>i.eligibilityDecision==='include').map(i=>i.studyId));const assessedIds=new Set(store.appraisalSessions.map(s=>s.studyId));const includedIds=new Set(included.map(i=>i.studyId));const invalid=[...assessedIds].filter(id=>!includedIds.has(id)||!eligibleIds.has(id));if(invalid.length)throw new Error(`PRISMA integrity violation: excluded/unknown studies have appraisal sessions: ${invalid.join(', ')}`);const completedIds=new Set(store.appraisalSessions.filter(s=>s.locked).map(s=>s.studyId));const exclusionReasons=[...new Set(excluded.map(i=>i.reason?.trim()||'Ikke spesifisert'))].map(reason=>({reason,count:excluded.filter(i=>(i.reason?.trim()||'Ikke spesifisert')===reason).length}));return{identification:{recordsFromDatabases:screening.length,recordsFromOtherSources:0,totalIdentified:screening.length,duplicatesRemoved:store.duplicatesRemoved??0},screening:{recordsScreened:screening.length,recordsExcluded:excluded.length},eligibility:{fullTextsAssessed:screening.filter(i=>i.eligibilityDecision==='include'||i.eligibilityDecision==='exclude').length,fullTextsExcluded:exclusionReasons},included:{studiesFinalSynthesis:included.length,studiesQualityAssessment:completedIds.size}};}
export function buildPicoQuery(pico:PICO):string{return[pico.population?`(${pico.population})`:'',pico.intervention?`AND (${pico.intervention})`:'',pico.comparator?`AND (${pico.comparator})`:'',pico.outcome?`AND (${pico.outcome})`:'' ].filter(Boolean).join(' ').trim();}

