import type { AppraisalSession, ResearchAppraisalPayload, ResearchWorkflowContext, ScreeningDecision, ScreeningRecord, WorkflowState } from '../types/workflow.contracts';
import { decideAppraisalLaunch } from './universalAppraisalService';
import { EvidenceFoundation, type EvidenceModule } from './evidenceSystemFoundation';
import { ResearchEngineGateway, type ResearchEngineDocument } from './researchEngineGateway';
import { ResearchEvidenceBridge, type ResearchToAppraisalBundle } from './researchEvidenceBridge';
import type { DocumentClassificationResult } from '../types';
export type { AppraisalSession, ResearchAppraisalPayload, ResearchWorkflowContext, ScreeningDecision, ScreeningRecord, WorkflowState } from '../types/workflow.contracts';

function evidenceCounts(evidence:ResearchToAppraisalBundle['evidence']){return{evidenceCandidateCount:evidence.filter(i=>i.source==='AI_CANDIDATE').length,evidenceVerifiedCount:evidence.filter(i=>i.verifiedByResearcher&&i.source==='HUMAN_VERIFIED'&&Boolean(i.verifiedBy)&&Boolean(i.verifiedAt)).length,evidenceRejectedCount:evidence.filter(i=>i.source==='REJECTED').length};}
function createDocumentId(value:string){let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619);}return`doc-${(hash>>>0).toString(16)}`;}
export function createResearchWorkflow(document:ResearchEngineDocument,studyId=document.id,analysis?:ReturnType<typeof ResearchEngineGateway.analyzeText>):WorkflowState{const normalizedStudyId=studyId.trim();if(!normalizedStudyId)throw new Error('studyId is required.');const foundation=new EvidenceFoundation();const evidenceBundle=ResearchEvidenceBridge.buildBundle(document,undefined,normalizedStudyId);const counts=evidenceCounts(evidenceBundle.evidence);foundation.state.set(`research:${normalizedStudyId}`,evidenceBundle,'system','Research document attached','research');return{studyId:normalizedStudyId,studyDesign:document.metadata.studyDesignDetected?.trim()||'UNKNOWN',screening:[],appraisalSessions:[],events:foundation.state.events(),research:{document,evidenceBundle,analysis,classificationVerified:false,selectedInstrumentId:undefined,...counts}};}
export async function createResearchWorkflowFromFile(file:File|{name:string;size:number;type?:string;content:ArrayBuffer|string},studyId?:string){const document=await ResearchEngineGateway.parseDocument(file);return createResearchWorkflow(document,studyId??document.id);}
export function createResearchWorkflowFromText(text:string,fileName='document.txt',studyId?:string):WorkflowState{if(!text?.trim())throw new Error('Dokumenttekst kan ikke være tom.');const normalizedFileName=fileName.trim()||'document.txt';const analysis=ResearchEngineGateway.analyzeText(text,normalizedFileName);const words=text.trim().split(/\s+/).filter(Boolean);const document:ResearchEngineDocument={id:createDocumentId(`${normalizedFileName}:${text.length}:${text.slice(0,1000)}`),fileName:normalizedFileName,fileType:'txt',mimeType:'text/plain',extractedText:text,wordCount:words.length,estimatedPages:Math.max(1,Math.ceil(words.length/500)),metadata:{title:normalizedFileName.replace(/\.[^/.]+$/,''),authors:'',year:undefined,journal:'',doi:'',abstract:'',studyDesignDetected:'',recommendedInstrumentId:''},sections:[],scanned:false,ocrNeeded:false,candidateEvidence:analysis.candidateEvidence??[]};return createResearchWorkflow(document,studyId??document.id,analysis);}
export function updateResearchClassification(state:WorkflowState,classification:DocumentClassificationResult):WorkflowState{if(!state.research)throw new Error('Research document must be attached before classification is updated.');const evidenceBundle=ResearchEvidenceBridge.buildBundle(state.research.document as ResearchEngineDocument,classification,state.studyId);const counts=evidenceCounts(evidenceBundle.evidence);const verified=classification.confidenceStatus==='HUMAN_VERIFIED'&&classification.humanDecision?.status==='APPROVED';return{...state,studyDesign:classification.studyDesign?.trim()??'',research:{...state.research,evidenceBundle,classificationVerified:verified,selectedInstrumentId:classification.recommendedInstrumentId?.trim()&&classification.recommendedInstrumentId!=='UNKNOWN'?classification.recommendedInstrumentId.trim():undefined,...counts}};}
export function verifyResearchClassification(state:WorkflowState,reviewerId:string,approved:boolean):WorkflowState{const id=reviewerId.trim();if(!state.research)throw new Error('Research document must be attached before classification can be verified.');if(!state.research.evidenceBundle.classification)throw new Error('No classification is available for verification.');if(!id)throw new Error('Reviewer ID is required.');const current=state.research.evidenceBundle.classification;const now=new Date().toISOString();return updateResearchClassification(state,{...current,confidenceStatus:approved?'HUMAN_VERIFIED':'MANUAL_VERIFICATION_REQUIRED',statusBadgeText:approved?'Human verified':'Manual verification required',humanDecision:{...current.humanDecision,status:approved?'APPROVED':'REJECTED',verifiedAt:now,verifiedBy:id,rationale:approved?'Classification approved by researcher.':'Classification rejected by researcher.'}});}
export function verifyResearchEvidence(state:WorkflowState,evidenceId:string,verified:boolean,reviewerId:string):WorkflowState{const id=reviewerId.trim();if(!state.research)throw new Error('Research document is not attached.');if(!id)throw new Error('Reviewer ID is required.');const current=state.research.evidenceBundle.evidence.find(i=>i.id===evidenceId);if(!current)throw new Error(`Evidence finnes ikke: ${evidenceId}`);if(current.source==='REJECTED'&&verified)throw new Error('Avvist evidence må vurderes på nytt gjennom eksplisitt re-inntak før det kan verifiseres.');const evidenceBundle=ResearchEvidenceBridge.verifyEvidence(state.research.evidenceBundle as ResearchToAppraisalBundle,evidenceId,verified,id);return{...state,research:{...state.research,evidenceBundle,...evidenceCounts(evidenceBundle.evidence)}};}
export function verifyAllCandidateEvidence(state:WorkflowState,reviewerId:string):WorkflowState{if(!reviewerId.trim())throw new Error('Reviewer ID is required.');if(!state.research)throw new Error('Research document is not attached.');let next=state;for(const item of state.research.evidenceBundle.evidence)if(item.source==='AI_CANDIDATE')next=verifyResearchEvidence(next,item.id,true,reviewerId);return next;}
export function selectResearchInstrument(state:WorkflowState,instrumentId:string):WorkflowState{if(!state.research)throw new Error('Research document must be attached.');const normalized=instrumentId.trim();if(!normalized)throw new Error('Instrument ID mangler.');const decision=decideAppraisalLaunch(state.studyDesign,normalized);if(!decision.instrument||!decision.allowed)throw new Error(decision.reason);return{...state,research:{...state.research,selectedInstrumentId:decision.instrument.id,evidenceBundle:{...state.research.evidenceBundle,gating:{...state.research.evidenceBundle.gating,instrumentRecommendation:decision.instrument.id}}}};}
export function getVerifiedResearchEvidence(state:WorkflowState){return state.research?.evidenceBundle.evidence.filter(i=>i.source==='HUMAN_VERIFIED'&&i.verifiedByResearcher&&Boolean(i.verifiedBy)&&Boolean(i.verifiedAt))??[];}
export function recordScreeningDecision(state:WorkflowState,reviewerId:string,decision:ScreeningDecision,reason?:string):WorkflowState{const id=reviewerId.trim();if(!id)throw new Error('Reviewer ID is required.');const normalizedReason=reason?.trim()||`Screening decision recorded as ${decision}.`;return{...state,screening:[...state.screening.filter(i=>i.reviewerId!==id),{studyId:state.studyId,reviewerId:id,decision,reason:normalizedReason,updatedAt:new Date().toISOString()}]};}
export function assertReadyForAppraisal(state:WorkflowState):void{const hasExcludedScreening=state.screening.some(i=>i.studyId===state.studyId&&i.decision==='EXCLUDED');if(hasExcludedScreening)throw new Error('INCLUDED screening decision required before appraisal.');if(!state.research)throw new Error('Ingen research-workflow er knyttet til studien.');if(!state.research.classificationVerified)throw new Error('Human verification av dokumentklassifisering (classification) er påkrevd.');if(!state.research.selectedInstrumentId)throw new Error('Appraisal-instrument er ikke valgt.');if(getVerifiedResearchEvidence(state).length===0)throw new Error('Minst ett evidensfunn må være menneskelig verifisert før appraisal kan startes.');const recommendation=state.research.evidenceBundle.gating.instrumentRecommendation?.trim();if(!recommendation||recommendation!==state.research.selectedInstrumentId)throw new Error('Valgt appraisal-instrument mangler konsistent workflow-gating.');const decision=decideAppraisalLaunch(state.studyDesign,state.research.selectedInstrumentId);if(!decision.allowed||!decision.instrument)throw new Error(decision.reason);}
export function buildResearchAppraisalPayload(state:WorkflowState):ResearchAppraisalPayload{assertReadyForAppraisal(state);return{studyId:state.studyId,instrumentId:state.research!.selectedInstrumentId!,evidence:getVerifiedResearchEvidence(state),document:state.research!.document,classification:state.research!.evidenceBundle.classification};}
export async function handoffWorkflow(foundation:EvidenceFoundation,fromModule:EvidenceModule,toModule:EvidenceModule,fromRole:string,toRole:string,studyId:string,reason:string):Promise<void>{await foundation.handoff({fromModule,toModule,fromRole,toRole,context:{studyId},reason,correlationId:foundation.state.snapshot().correlationId});}
export function getResearchEvidenceSummary(state:WorkflowState){const evidence=state.research?.evidenceBundle.evidence??[];return{total:evidence.length,verified:evidence.filter(i=>i.source==='HUMAN_VERIFIED'&&i.verifiedByResearcher&&Boolean(i.verifiedBy)&&Boolean(i.verifiedAt)).length,candidates:evidence.filter(i=>i.source==='AI_CANDIDATE').length,rejected:evidence.filter(i=>i.source==='REJECTED').length};}
