import { useEffect, useMemo, useState } from 'react';
import { downloadImplementationExport, getCfirMetadata, getKtaMetadata, saveImplementation, validateImplementation } from '../api/researchApi';

const emptyCfirItem = (domain, construct) => ({ domain, construct, influence: '', evidenceSummary: '', rationale: '', evidenceLocation: '' });
const emptyAction = () => ({ title: '', description: '', ktaPhaseNumber: 3, ownerCode: '', dueDateUtc: '', status: 'Planned', linkedCfirConstructKeys: [] });
function buildAssessment(cfirMeta, ktaMeta, items, phases, actions) { return { cfir: { ...cfirMeta, cfirVersion: 'CFIR 2.0', assessmentDateUtc: new Date().toISOString(), items }, kta: { ...ktaMeta, ktaFrameworkVersion: 'Graham et al., 2006', assessmentDateUtc: new Date().toISOString(), phases, actions: actions.map((action) => ({ ...action, dueDateUtc: action.dueDateUtc ? new Date(`${action.dueDateUtc}T23:59:59Z`).toISOString() : null })) } }; }
function downloadJson(filename, data) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); }

export default function ImplementationModule() {
  const [cfir, setCfir] = useState(null);
  const [result, setResult] = useState(null);
  const [saveState, setSaveState] = useState('');
  const [cfirMeta, setCfirMeta] = useState({ innovationName: '', innerSetting: '', outerSetting: '', reviewerCode: '', secondReviewerCode: '', consensusReviewerCode: '', consensusStatus: '', consensusRationale: '' });
  const [ktaMeta, setKtaMeta] = useState({ projectName: '', reviewerCode: '' });
  const [items, setItems] = useState([]);
  const [phases, setPhases] = useState([]);
  const [actions, setActions] = useState([]);

  useEffect(() => { Promise.all([getCfirMetadata(), getKtaMetadata()]).then(([c, k]) => { setCfir(c); setPhases(k.phases); }).catch(() => setResult({ isValid: false, errors: ['Kunne ikke hente CFIR/KTA-metodeinformasjon.'], warnings: [] })); }, []);
  const constructsByDomain = useMemo(() => !cfir ? [] : cfir.domains.map((domain) => ({ domain, constructs: cfir.constructs.filter((item) => item.domain === domain) })), [cfir]);
  const selectedConstructKeys = useMemo(() => items.map((item) => `${item.domain}|${item.construct}`), [items]);
  function addConstruct(domain, construct) { setItems((current) => current.some((item) => item.domain === domain && item.construct === construct) ? current : [...current, emptyCfirItem(domain, construct)]); }
  function removeConstruct(key) { setItems((current) => current.filter((item) => `${item.domain}|${item.construct}` !== key)); setActions((current) => current.map((action) => ({ ...action, linkedCfirConstructKeys: action.linkedCfirConstructKeys.filter((item) => item !== key) }))); }
  function updateCfirItem(key, field, value) { setItems((current) => current.map((item) => `${item.domain}|${item.construct}` === key ? { ...item, [field]: value } : item)); }
  function updateAction(index, field, value) { setActions((current) => current.map((action, actionIndex) => actionIndex === index ? { ...action, [field]: value } : action)); }
  function toggleActionLink(index, key) { setActions((current) => current.map((action, actionIndex) => { if (actionIndex !== index) return action; const linked = action.linkedCfirConstructKeys.includes(key) ? action.linkedCfirConstructKeys.filter((item) => item !== key) : [...action.linkedCfirConstructKeys, key]; return { ...action, linkedCfirConstructKeys: linked }; })); }
  async function submit(event) { event.preventDefault(); try { setSaveState(''); setResult(await validateImplementation(buildAssessment(cfirMeta, ktaMeta, items, phases, actions))); } catch (error) { setResult({ isValid: false, errors: [error.message], warnings: [] }); } }
  async function persist() { try { setSaveState('Lagrer…'); const assessment = buildAssessment(cfirMeta, ktaMeta, items, phases, actions); const validation = await validateImplementation(assessment); setResult(validation); if (!validation.isValid) { setSaveState('Ikke lagret – korriger valideringsfeil.'); return; } await saveImplementation(assessment); setSaveState('Lagret i database.'); } catch (error) { setSaveState(`Lagring feilet: ${error.message}`); } }
  async function exportFile(format) { try { const assessment = buildAssessment(cfirMeta, ktaMeta, items, phases, actions); const validation = await validateImplementation(assessment); setResult(validation); if (!validation.isValid) return; await downloadImplementationExport(format, assessment); } catch (error) { setResult({ isValid: false, errors: [error.message], warnings: [] }); } }
  function exportCurrentJson() { const assessment = buildAssessment(cfirMeta, ktaMeta, items, phases, actions); downloadJson('evidence-appraisal-cfir-kta.json', { exportSchema: 'evidence-appraisal-tool/implementation/v1', exportedAtUtc: new Date().toISOString(), ...assessment, methodologicalNotice: 'Researcher-entered CFIR/KTA data. The file is not a validated scientific conclusion and must be interpreted using official framework guidance.' }); }

  return <section className="research-hub" aria-labelledby="implementation-heading">
    <p className="eyebrow">Implementeringsmodul</p><h2 id="implementation-heading">CFIR 2.0 + KTA</h2>
    <p>CFIR dokumenterer implementeringsdeterminanter. KTA dokumenterer den iterative handlingssyklusen. Verktøyet kobler dokumenterte barrierer/fasilitatorer til eksplisitte tiltak uten å lage en kunstig implementeringsscore.</p>
    {cfir && <form className="research-form" onSubmit={submit}>
      <h3>1. CFIR 2.0 – prosjekt og vurderere</h3>
      <div className="research-grid">{Object.entries({ innovationName: 'Innovasjon – hva implementeres?', innerSetting: 'Inner Setting – hvor?', outerSetting: 'Outer Setting – relevant kontekst', reviewerCode: 'Vurderer A – kode', secondReviewerCode: 'Vurderer B – kode (valgfritt)', consensusReviewerCode: 'Konsensusvurderer – kode (ved behov)' }).map(([field, label]) => <label key={field}>{label}<input value={cfirMeta[field]} onChange={(e) => setCfirMeta({ ...cfirMeta, [field]: e.target.value })} /></label>)}</div>
      <label>Konsensusstatus<select value={cfirMeta.consensusStatus} onChange={(e) => setCfirMeta({ ...cfirMeta, consensusStatus: e.target.value })}><option value="">Ikke dokumentert</option><option value="Agreement">Enighet</option><option value="Disagreement">Uenighet</option></select></label>
      {cfirMeta.consensusStatus && <label>Konsensusbegrunnelse<textarea rows="3" value={cfirMeta.consensusRationale} onChange={(e) => setCfirMeta({ ...cfirMeta, consensusRationale: e.target.value })} /></label>}
      <p className="module-warning">CFIR 2.0 må operasjonaliseres for det konkrete prosjektet. 48 konstrukt og 19 subkonstrukt finnes i rammeverket; denne katalogen viser de 48 konstruktne. Velg bare det som er metodisk relevant, og dokumenter prosjektspesifikke definisjoner og subkonstrukt ved behov.</p>
      {constructsByDomain.map(({ domain, constructs }) => <fieldset className="research-item" key={domain}><legend>{domain}</legend><div className="research-grid">{constructs.map((construct) => { const selected = selectedConstructKeys.includes(`${domain}|${construct.name}`); return <button type="button" key={construct.name} disabled={selected} onClick={() => addConstruct(domain, construct.name)}>{selected ? 'Valgt' : '+ Velg'} {construct.name}</button>; })}</div></fieldset>)}
      {items.map((item) => { const key = `${item.domain}|${item.construct}`; return <fieldset className="research-item" key={key}><legend>{item.construct}</legend><label>Forskerens vurdering <span>(ikke automatisk beregnet)</span><select required value={item.influence} onChange={(e) => updateCfirItem(key, 'influence', e.target.value)}><option value="">Velg vurdering</option><option value="StrongBarrier">Sterk barriere</option><option value="Barrier">Barriere</option><option value="NeutralOrUnclear">Nøytral/uklar eller blandet</option><option value="Facilitator">Fasilitator</option><option value="StrongFacilitator">Sterk fasilitator</option></select></label><label>Oppsummert evidens-/datagrunnlag<textarea rows="3" value={item.evidenceSummary} onChange={(e) => updateCfirItem(key, 'evidenceSummary', e.target.value)} /></label><label>Dokumentasjonssted<input required value={item.evidenceLocation} onChange={(e) => updateCfirItem(key, 'evidenceLocation', e.target.value)} /></label><label>Faglig begrunnelse<textarea required rows="3" value={item.rationale} onChange={(e) => updateCfirItem(key, 'rationale', e.target.value)} /></label><button type="button" className="secondary-button" onClick={() => removeConstruct(key)}>Fjern konstrukt</button></fieldset>; })}
      <h3>2. KTA – handlingssyklus</h3><div className="research-grid"><label>Prosjektnavn<input required value={ktaMeta.projectName} onChange={(e) => setKtaMeta({ ...ktaMeta, projectName: e.target.value })} /></label><label>KTA-vurderer – kode<input required value={ktaMeta.reviewerCode} onChange={(e) => setKtaMeta({ ...ktaMeta, reviewerCode: e.target.value })} /></label></div>
      <p className="module-warning">KTA er iterativ og bidireksjonell. Status betyr dokumentert prosjektstatus, ikke prosentvis implementeringseffekt.</p>
      {phases.map((phase) => <fieldset className="research-item" key={phase.number}><legend>{phase.number}. {phase.name}</legend><label>Status<select value={phase.status} onChange={(e) => setPhases((current) => current.map((p) => p.number === phase.number ? { ...p, status: e.target.value } : p))}><option value="NotStarted">Ikke startet</option><option value="InProgress">Pågår</option><option value="Completed">Fullført</option></select></label><label>Dokumentasjon<textarea rows="3" value={phase.documentation} onChange={(e) => setPhases((current) => current.map((p) => p.number === phase.number ? { ...p, documentation: e.target.value } : p))} /></label></fieldset>)}
      <h3>3. Tiltak koblet til CFIR-funn</h3><p>Et tiltak er ikke automatisk riktig fordi en barriere er registrert. Koblingen dokumenterer bare forskerens/prosjektteamets valgte respons.</p>
      {actions.map((action, index) => <fieldset className="research-item" key={`action-${index}`}><legend>Tiltak {index + 1}</legend><div className="research-grid"><label>Tittel<input required value={action.title} onChange={(e) => updateAction(index, 'title', e.target.value)} /></label><label>Ansvarlig – kode<input required value={action.ownerCode} onChange={(e) => updateAction(index, 'ownerCode', e.target.value)} /></label><label>KTA-fase<select value={action.ktaPhaseNumber} onChange={(e) => updateAction(index, 'ktaPhaseNumber', Number(e.target.value))}>{phases.map((phase) => <option key={phase.number} value={phase.number}>{phase.number}. {phase.name}</option>)}</select></label><label>Frist<input type="date" value={action.dueDateUtc} onChange={(e) => updateAction(index, 'dueDateUtc', e.target.value)} /></label><label>Status<select value={action.status} onChange={(e) => updateAction(index, 'status', e.target.value)}><option value="Planned">Planlagt</option><option value="InProgress">Pågår</option><option value="Completed">Fullført</option><option value="Deferred">Utsatt</option><option value="Cancelled">Kansellert</option></select></label></div><label>Beskrivelse<textarea required rows="3" value={action.description} onChange={(e) => updateAction(index, 'description', e.target.value)} /></label><fieldset><legend>Koble til valgte CFIR-konstrukt</legend>{items.length === 0 && <p>Velg CFIR-konstrukt først.</p>}{items.map((item) => { const key = `${item.domain}|${item.construct}`; return <label key={key}><input type="checkbox" checked={action.linkedCfirConstructKeys.includes(key)} onChange={() => toggleActionLink(index, key)} />{item.construct} ({item.influence || 'ikke vurdert'})</label>; })}</fieldset><button type="button" onClick={() => setActions((current) => current.filter((_, actionIndex) => actionIndex !== index))}>Fjern tiltak</button></fieldset>)}
      <button type="button" onClick={() => setActions((current) => [...current, emptyAction()])}>+ Legg til tiltak</button>
      <div className="research-grid"><button className="primary-button" type="submit" disabled={items.length === 0}>Valider samlet CFIR/KTA-datasett</button><button type="button" onClick={persist} disabled={items.length === 0}>Lagre i database</button><button type="button" onClick={exportCurrentJson}>JSON lokalt</button><button type="button" onClick={() => exportFile('json')} disabled={items.length === 0}>JSON</button><button type="button" onClick={() => exportFile('csv')} disabled={items.length === 0}>CSV</button><button type="button" onClick={() => exportFile('xlsx')} disabled={items.length === 0}>XLSX</button><button type="button" onClick={() => exportFile('docx')} disabled={items.length === 0}>DOCX</button><button type="button" onClick={() => exportFile('pdf')} disabled={items.length === 0}>PDF</button></div>
      {saveState && <p className="module-warning" role="status">{saveState}</p>}{result && <Result result={result} />}
    </form>}
  </section>;
}
function Result({ result }) { return <div className={result.isValid ? 'result-panel' : 'message message-error'} role="status"><strong>{result.isValid ? 'Datasettet er strukturelt validert.' : 'Må korrigeres før datasettet kan godkjennes.'}</strong>{result.errors?.length > 0 && <ul>{result.errors.map((error) => <li key={error}>{error}</li>)}</ul>}{result.warnings?.length > 0 && <ul>{result.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}{result.cfir?.warnings?.length > 0 && <ul>{result.cfir.warnings.map((warning) => <li key={`cfir-${warning}`}>{warning}</li>)}</ul>}{result.kta?.warnings?.length > 0 && <ul>{result.kta.warnings.map((warning) => <li key={`kta-${warning}`}>{warning}</li>)}</ul>}{result.cfir?.methodologicalNotice && <p><strong>CFIR:</strong> {result.cfir.methodologicalNotice}</p>}{result.kta?.methodologicalNotice && <p><strong>KTA:</strong> {result.kta.methodologicalNotice}</p>}</div>; }
