import { useEffect, useState } from 'react';
import ResearchWorkflowPanel from './ResearchWorkflowPanel';
import './ResearchMethods.css';

const API = import.meta.env.VITE_API_URL ?? (import.meta.env.PROD ? '' : 'http://localhost:5237');
const initialPrisma = { recordsIdentified:0, recordsRemovedBeforeScreening:0, recordsScreened:0, recordsExcluded:0, reportsSought:0, reportsNotRetrieved:0, reportsAssessed:0, reportsExcludedWithReasons:0, studiesIncluded:0, reportsIncluded:0 };
const initialRow = { outcome:'', relativeEffect:'', absoluteEffect:'', participantsAndStudies:'', certainty:'Undetermined', justification:'' };
async function post(path, body) { const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json(); if(!r.ok) throw new Error(d.error||`Request failed (${r.status})`); return d; }

export default function ResearchMethods(){
 const [methods,setMethods]=useState([]),[method,setMethod]=useState('SystematicReview'),[prisma,setPrisma]=useState(initialPrisma),[prismaResult,setPrismaResult]=useState(null),[r1,setR1]=useState(''),[r2,setR2]=useState(''),[kappa,setKappa]=useState(null),[rows,setRows]=useState([{...initialRow}]),[error,setError]=useState('');
 useEffect(()=>{fetch(`${API}/api/research/methodologies`).then(r=>r.json()).then(setMethods).catch(()=>setMethods([]));},[]);
 const selected=methods.find(x=>x.id===method);
 const setP=(k,v)=>{setPrisma(x=>({...x,[k]:Number(v)||0}));setPrismaResult(null)};
 const validate=async()=>{try{setError('');setPrismaResult(await post('/api/research/prisma/validate',prisma));}catch(e){setError(e.message)}};
 const calcKappa=async()=>{try{setError('');setKappa(await post('/api/research/kappa',{reviewer1:r1.split('\n').map(x=>x.trim()).filter(Boolean),reviewer2:r2.split('\n').map(x=>x.trim()).filter(Boolean)}));}catch(e){setError(e.message)}};
 const setRow=(i,k,v)=>setRows(a=>a.map((r,n)=>n===i?{...r,[k]:v}:r));
 const exportSoF=()=>{const b=new Blob([JSON.stringify({title:'GRADE Summary of Findings',rows},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='grade-summary-of-findings.json';a.click();URL.revokeObjectURL(u)};
 return <div className="research-methods">
  <section className="methods-hero"><p className="eyebrow">Research methodology</p><h2>Forskningsflyt og syntese</h2><p>Strukturer arbeidsprosessen uten å automatisere forskerens metodiske skjønn.</p></section>
  {error&&<div className="notice notice-warning" role="alert"><strong>Feil:</strong> {error}</div>}
  <section className="method-selector"><label htmlFor="research-method"><strong>Analyseform</strong></label><select id="research-method" value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{selected&&<p><strong>Anbefalte moduler:</strong> {selected.recommendedModules.join(' · ')}</p>}</section>

  <ResearchWorkflowPanel />

  <section className="method-card"><div className="method-card-heading"><div><p className="eyebrow">Search & screen</p><h3>PRISMA 2020 – flytdata</h3></div><span className="pill">Kontrollerbar</span></div>
   <div className="number-grid">{Object.entries({recordsIdentified:'Identifiserte poster',recordsRemovedBeforeScreening:'Fjernet før screening',recordsScreened:'Screenet',recordsExcluded:'Ekskludert ved screening',reportsSought:'Rapporter søkt hentet',reportsNotRetrieved:'Ikke hentet',reportsAssessed:'Fulltekst vurdert',reportsExcludedWithReasons:'Fulltekst ekskludert',studiesIncluded:'Studier inkludert',reportsIncluded:'Rapporter inkludert'}).map(([k,l])=><label key={k}>{l}<input type="number" min="0" value={prisma[k]} onChange={e=>setP(k,e.target.value)}/></label>)}</div>
   <button type="button" className="primary-button" onClick={validate}>Kontroller PRISMA-tall</button>{prismaResult&&<div className={prismaResult.internallyConsistent?'result-box success':'result-box warning'}><strong>{prismaResult.internallyConsistent?'Internt konsistent':'Må kontrolleres'}</strong>{prismaResult.warnings.map(x=><p key={x}>{x}</p>)}<p>Screening: {prismaResult.screeningDifference}; eligibility: {prismaResult.eligibilityDifference}; inkludert: {prismaResult.includedDifference}.</p></div>}
  </section>
  <section className="method-card"><div className="method-card-heading"><div><p className="eyebrow">Inter-rater reliability</p><h3>Cohen's kappa</h3></div><span className="pill">Før konsensus</span></div><p>Én vurdering per linje. Konsensus skal ikke blandes inn i reliabilitetsberegningen.</p><div className="reviewer-grid"><label>Reviewer 1<textarea value={r1} onChange={e=>setR1(e.target.value)} placeholder={'Yes\nNo\nUnclear'}/></label><label>Reviewer 2<textarea value={r2} onChange={e=>setR2(e.target.value)} placeholder={'Yes\nYes\nUnclear'}/></label></div><button type="button" className="primary-button" onClick={calcKappa}>Beregn Cohen's κ</button>{kappa&&<div className="result-box"><strong>κ = {kappa.kappa.toFixed(3)}</strong><p>n={kappa.n}; observert enighet={(kappa.observedAgreement*100).toFixed(1)}%; forventet enighet={(kappa.expectedAgreement*100).toFixed(1)}%.</p><p>{kappa.interpretation}</p></div>}</section>
  <section className="method-card"><div className="method-card-heading"><div><p className="eyebrow">Synthesis</p><h3>GRADE Summary of Findings</h3></div><span className="pill">Manuell forskervurdering</span></div><p>Strukturer sluttresultatet. Systemet skal ikke automatisk utlede certainty fra én enkelt RoB-vurdering.</p><div className="sof-table-wrap"><table><thead><tr><th>Utfall</th><th>Relativ effekt</th><th>Absolutt effekt</th><th>Deltakere/studier</th><th>Tillit</th><th>Begrunnelse</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{['outcome','relativeEffect','absoluteEffect','participantsAndStudies'].map(k=><td key={k}><input value={r[k]} onChange={e=>setRow(i,k,e.target.value)}/></td>)}<td><select value={r.certainty} onChange={e=>setRow(i,'certainty',e.target.value)}><option>High</option><option>Moderate</option><option>Low</option><option>Very Low</option><option>Undetermined</option></select></td><td><input value={r.justification} onChange={e=>setRow(i,'justification',e.target.value)}/></td></tr>)}</tbody></table></div><div className="button-row"><button type="button" onClick={()=>setRows(a=>[...a,{...initialRow}])}>+ Legg til utfall</button><button type="button" onClick={exportSoF}>Eksporter SoF-data</button></div><div className="notice notice-warning"><strong>Kontroller alltid mot kildene:</strong> GRADE certainty er en faglig vurdering av evidensgrunnlaget, ikke en automatisk kvalitetsscore.</div></section>
  <section className="method-card roadmap"><h3>Metodiske utvidelser</h3><p>Validerte instrumenttekster må håndteres etter gjeldende rettighets- og lisensvilkår. Programmet skal ikke late som en sjekkliste er tilgjengelig dersom den ikke er implementert eller lisensiert.</p><div className="roadmap-grid"><span>Risk of Bias</span><span>Extraction</span><span>Qualitative synthesis</span><span>Meta-analysis</span><span>Conflict resolution</span><span>Master Report</span></div></section>
 </div>;
}
