import test from 'node:test';
import assert from 'node:assert/strict';
import { MASTER_INSTRUMENTS_REGISTRY } from '../src/data/masterRegistry';
import { createResearchWorkflowFromText, updateResearchClassification, verifyResearchClassification, verifyResearchEvidence, buildResearchAppraisalPayload, selectResearchInstrument } from '../src/services/researchWorkflowService';
import { evidenceAppraisalOrchestrator } from '../src/services/evidenceAppraisalOrchestrator';
import { getAppraisalWorkflowRecord } from '../src/services/appraisalWorkflowBridge';
import { validateAppraisalSession } from '../src/services/universalAppraisalService';
import { researchWorkflowStore } from '../src/services/researchWorkflowStore';

function classification(instrumentId:string,studyDesign:string){return{documentType:'QUALITATIVE_STUDY' as const,documentTypeName:'Qualitative study',studyDesign,methodologicalApproach:'Kvalitativ' as const,methodologicalPurpose:'Levde erfaringer / Sosiale fenomener' as const,confidenceScore:95,confidenceStatus:'AI_CANDIDATE_REQUIRES_VERIFICATION' as const,statusBadgeText:'Requires verification',evidenceSignals:[],rationale:'Integration test classification',hasMetadataContentConflict:false,recommendedInstrumentId:instrumentId,recommendedInstrumentName:MASTER_INSTRUMENTS_REGISTRY.find(i=>i.id===instrumentId)?.name??'',recommendedInstrumentJustification:'Test',alternativeInstruments:[],methodologicalLimitations:'',instrumentSourceAndAuthority:'Test',instrumentRoleType:'CRITICAL_APPRAISAL' as const};}
function readyWorkflow(studyId:string){let w=createResearchWorkflowFromText('Methods: qualitative study. Participants described their experiences of person-centred dementia care.','study.txt',studyId);w=updateResearchClassification(w,classification('jbi-qualitative-2017','Kvalitativ'));w=verifyResearchClassification(w,'reviewer-1',true);w=selectResearchInstrument(w,'jbi-qualitative-2017');return w;}

test('research evidence must be human verified before appraisal payload',()=>{let w=createResearchWorkflowFromText('Methods: qualitative study. Participants described their experiences of person-centred dementia care.','study.txt','integration-study');w=updateResearchClassification(w,classification('jbi-qualitative-2017','Kvalitativ'));assert.throws(()=>buildResearchAppraisalPayload(w));w=verifyResearchClassification(w,'reviewer-1',true);w=selectResearchInstrument(w,'jbi-qualitative-2017');const e=w.research?.evidenceBundle.evidence[0];assert.ok(e);w=verifyResearchEvidence(w,e.id,true,'reviewer-1');const p=buildResearchAppraisalPayload(w);assert.equal(p.studyId,'integration-study');assert.equal(p.instrumentId,'jbi-qualitative-2017');assert.equal(p.evidence.length,1);assert.equal(p.evidence[0].source,'HUMAN_VERIFIED');});
test('rejected evidence is never included in verified evidence',()=>{let w=readyWorkflow('integration-study-reject');const e=w.research?.evidenceBundle.evidence[0];assert.ok(e);w=verifyResearchEvidence(w,e.id,false,'reviewer-1');assert.equal(w.research?.evidenceBundle.evidence[0].source,'REJECTED');assert.deepEqual(w.research?getVerifiedEvidence(w):[],[]);assert.throws(()=>buildResearchAppraisalPayload(w));});
function getVerifiedEvidence(state:ReturnType<typeof readyWorkflow>){return state.research?.evidenceBundle.evidence.filter(i=>i.source==='HUMAN_VERIFIED'&&i.verifiedByResearcher&&Boolean(i.verifiedBy)&&Boolean(i.verifiedAt))??[];}
test('orchestrator creates exactly one shared appraisal session',async()=>{let w=readyWorkflow('integration-orchestrator');const e=w.research?.evidenceBundle.evidence[0];assert.ok(e);w=verifyResearchEvidence(w,e.id,true,'reviewer-1');researchWorkflowStore.save(w);const context=await evidenceAppraisalOrchestrator.start(w,'reviewer-1');assert.equal(context.workflow.appraisalSessions.length,1);assert.equal(context.appraisal.session.id,context.workflow.appraisalSessions[0].id);assert.deepEqual(getAppraisalWorkflowRecord(context.appraisal.session.id),context.appraisal);});
test('all registered instrument sessions validate against their registry questions',()=>{for(const instrument of MASTER_INSTRUMENTS_REGISTRY.filter(i=>i.questions?.length)){const session={id:`test-session-${instrument.id}`,studyId:'study',instrumentId:instrument.id,instrumentVersion:instrument.version,reviewerId:'reviewer',responses:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),locked:false};const result=validateAppraisalSession(session);assert.equal(result.missingItemIds.length,instrument.questions?.length??0,instrument.id);assert.equal(result.valid,false,instrument.id);}});
