import React, { useEffect, useMemo, useState } from 'react';
import { MASTER_INSTRUMENTS_REGISTRY } from '../data/masterRegistry';
import { decideAppraisalLaunch, upsertAppraisalResponse, validateAppraisalSession, type AppraisalSession } from '../services/universalAppraisalService';
import { Amstar2AssessmentEngine, Agree2AssessmentEngine, JbiQualitativeAssessmentEngine, Rob2AssessmentEngine, RobinsIAssessmentEngine } from '../services/assessmentEngines';
import { QualityAssessmentPanel } from './QualityAssessmentPanel';
import { getLatestAppraisalSession } from '../services/appraisalSessionStore';

interface Props { studyId: string; studyDesign: string; initialInstrumentId?: string; reviewerId?: string; onSaved?: (session: AppraisalSession) => void; }
interface CanonicalEvidence { id: string; quote: string; location?: { page?: string; section?: string; table?: string; figure?: string }; source: string; verifiedByResearcher?: boolean; verifiedBy?: string; verifiedAt?: string; }
const answerOptions = (instrumentId: string, allowed: string[]) => { if (instrumentId === 'agree-ii' || instrumentId === 'agree-rex') return ['1','2','3','4','5','6','7']; if (instrumentId === 'rob-2') return ['Low risk','Some concerns','High risk']; if (instrumentId === 'robins-i') return ['Low','Moderate','Serious','Critical','No information']; return allowed?.length ? allowed : ['Yes','Partial Yes','No','Unclear','Not applicable']; };
const hasAnswer = (value: unknown) => value !== null && value !== undefined && String(value).trim() !== '';
type Rob2Risk = 'Low risk' | 'Some concerns' | 'High risk';
type RobinsIRisk = 'Low risk' | 'Moderate risk' | 'Serious risk' | 'Critical risk' | 'No information';
function isRob2Risk(value: unknown): value is Rob2Risk { return value === 'Low risk' || value === 'Some concerns' || value === 'High risk'; }
function isRobinsIRisk(value: unknown): value is RobinsIRisk { return value === 'Low risk' || value === 'Moderate risk' || value === 'Serious risk' || value === 'Critical risk' || value === 'No information'; }

async function createCanonicalSession(studyId: string, reviewerId: string, instrumentId: string): Promise<AppraisalSession> { const response = await fetch(`/api/research-workflows/${encodeURIComponent(studyId)}/appraisal/start`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reviewerId, instrumentId: instrumentId || undefined }) }); const payload = await response.json().catch(() => null) as { appraisal?: AppraisalSession; error?: string } | null; if (!response.ok || !payload?.appraisal) throw new Error(payload?.error || 'Kunne ikke opprette canonical appraisal-session.'); return payload.appraisal; }
async function saveCanonicalSession(session: AppraisalSession): Promise<AppraisalSession> { const response = await fetch(`/api/appraisal/${encodeURIComponent(session.id)}/sync`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reviewerId: session.reviewerId, session }) }); const payload = await response.json().catch(() => null) as { session?: AppraisalSession; error?: string } | null; if (!response.ok) throw new Error(payload?.error || 'Kunne ikke synkronisere appraisal-session.'); return payload?.session ?? session; }
async function loadCanonicalEvidence(sessionId: string): Promise<CanonicalEvidence[]> { const response = await fetch(`/api/appraisal/${encodeURIComponent(sessionId)}`); const payload = await response.json().catch(() => null) as { workflow?: { research?: { evidenceBundle?: { evidence?: CanonicalEvidence[] } } } } | null; if (!response.ok) return []; return payload?.workflow?.research?.evidenceBundle?.evidence?.filter(item => item.source === 'HUMAN_VERIFIED' && item.verifiedByResearcher === true && item.verifiedBy && item.verifiedAt) ?? []; }
async function changeCanonicalInstrument(session: AppraisalSession, studyDesign: string, instrumentId: string, reviewerId: string): Promise<AppraisalSession> { const decision = decideAppraisalLaunch(studyDesign, instrumentId, false); if (!decision.allowed || !decision.instrument) throw new Error(decision.reason); const response = await fetch(`/api/appraisal/${encodeURIComponent(session.id)}/instrument`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ instrumentId: decision.instrument.id, reviewerId }) }); const payload = await response.json().catch(() => null) as { session?: AppraisalSession; error?: string } | null; if (!response.ok || !payload?.session) throw new Error(payload?.error || 'Kunne ikke endre appraisal-instrument.'); return payload.session; }

export const UniversalAppraisalView: React.FC<Props> = ({ studyId, studyDesign, initialInstrumentId = '', reviewerId, onSaved }) => {
  const effectiveReviewerId = reviewerId?.trim() || '';
  const cached = getLatestAppraisalSession(studyId, initialInstrumentId, effectiveReviewerId);
  const [instrumentId, setInstrumentId] = useState(cached?.instrumentId ?? initialInstrumentId);
  const [session, setSession] = useState<AppraisalSession | null>(cached ?? null);
  const [canonicalEvidence, setCanonicalEvidence] = useState<CanonicalEvidence[]>([]);
  const [notice, setNotice] = useState(effectiveReviewerId ? '' : 'Reviewer-ID mÃ¥ oppgis fÃ¸r appraisal kan startes.');
  const [starting, setStarting] = useState(false);
  const [changingInstrument, setChangingInstrument] = useState(false);
  const instrument = MASTER_INSTRUMENTS_REGISTRY.find(item => item.id === instrumentId);
  const validation = session ? validateAppraisalSession(session) : null;

  useEffect(() => { if (!effectiveReviewerId || session || starting) return; let cancelled = false; setStarting(true); void createCanonicalSession(studyId, effectiveReviewerId, initialInstrumentId).then(next => { if (!cancelled) { setInstrumentId(next.instrumentId); setSession(next); } }).catch(error => { if (!cancelled) setNotice(error instanceof Error ? error.message : 'Appraisal-session kunne ikke opprettes.'); }).finally(() => { if (!cancelled) setStarting(false); }); return () => { cancelled = true; }; }, [effectiveReviewerId, session, starting, studyId, initialInstrumentId]);
  useEffect(() => { if (!session) { setCanonicalEvidence([]); return; } let cancelled = false; void loadCanonicalEvidence(session.id).then(items => { if (!cancelled) setCanonicalEvidence(items); }); return () => { cancelled = true; }; }, [session?.id]);

  const changeInstrument = async (id: string) => { if (!session || session.locked || changingInstrument) return; setChangingInstrument(true); try { const next = await changeCanonicalInstrument(session, studyDesign, id, effectiveReviewerId); setInstrumentId(next.instrumentId); setSession(next); setNotice(`Instrument endret til ${next.instrumentId} ${next.instrumentVersion}. Tidligere svar er nullstilt av canonical workflow.`); } catch (error) { setNotice(error instanceof Error ? error.message : 'Instrument kunne ikke endres.'); } finally { setChangingInstrument(false); } };
  const patch = (itemId: number | string, value: Partial<{ answer: string | null; rationale: string; evidence: { quote?: string; page?: string; section?: string; sourceId?: string } }>) => { if (!session || session.locked) { if (session?.locked) setNotice('Denne vurderingen er lÃ¥st og kan ikke endres.'); return; } try { setSession(prev => { if (!prev) return prev; const old = prev.responses.find(r => String(r.itemId) === String(itemId)); return upsertAppraisalResponse(prev, { itemId, answer: value.answer ?? old?.answer ?? null, rationale: value.rationale ?? old?.rationale ?? '', evidence: value.evidence ?? old?.evidence }); }); } catch (error) { setNotice(error instanceof Error ? error.message : 'Svar kunne ikke registreres.'); } };

  const result = useMemo(() => { if (!instrument || !session) return null; const map = new Map(session.responses.map(r => [String(r.itemId), r])); if (instrument.id === 'amstar-2') { const responses: Record<number, string> = {}; map.forEach((r,k) => { responses[Number(k)] = String(r.answer ?? ''); }); return Object.keys(responses).length === instrument.itemCount && Object.values(responses).every(hasAnswer) ? Amstar2AssessmentEngine.evaluate(responses) : null; } if (instrument.id === 'agree-ii') { const ratings: Record<number, number> = {}; map.forEach((r,k) => { if (hasAnswer(r.answer)) ratings[Number(k)] = Number(r.answer); }); return Object.keys(ratings).length === instrument.itemCount && Object.values(ratings).every(Number.isInteger) ? Agree2AssessmentEngine.evaluateDomainScores(ratings) : null; } if (instrument.id === 'rob-2') { const required = ['1','2','3','4','5']; if (!required.every(id => hasAnswer(map.get(id)?.answer))) return null; const d1 = map.get('1')?.answer, d2 = map.get('2')?.answer, d3 = map.get('3')?.answer, d4 = map.get('4')?.answer, d5 = map.get('5')?.answer; if (![d1,d2,d3,d4,d5].every(isRob2Risk)) return null; return Rob2AssessmentEngine.evaluate({ d1Randomisation: d1 as Rob2Risk, d2Deviations: d2 as Rob2Risk, d3MissingData: d3 as Rob2Risk, d4Measurement: d4 as Rob2Risk, d5Selection: d5 as Rob2Risk }); } if (instrument.id === 'robins-i') { const required = ['1','2','3','4','5','6','7']; if (!required.every(id => hasAnswer(map.get(id)?.answer))) return null; const domainResponses: Record<string, RobinsIRisk> = {}; for (const id of required) { const answer = map.get(id)?.answer; if (!isRobinsIRisk(answer)) return null; domainResponses[`D${id}`] = answer; } return RobinsIAssessmentEngine.evaluate(domainResponses); } if (instrument.id === 'jbi-qualitative-2017') return JbiQualitativeAssessmentEngine.evaluate(session.responses.map(r => ({ questionId: Number(r.itemId), status: String(r.answer ?? ''), justification: r.rationale }))); return null; }, [instrument, session]);
  const answeredCount = session?.responses.filter(r => hasAnswer(r.answer)).length ?? 0;
  const interpretation = result && 'overallConfidence' in result ? result.overallConfidence : result && 'overallRiskOfBias' in result ? result.overallRiskOfBias : result && 'verdict' in result ? result.verdict : `${answeredCount}/${instrument?.itemCount ?? 0} besvart â€” ingen instrumentspesifikk skÃ¥r fÃ¸r vurderingen er komplett`;

  const finalize = async () => { if (!session || session.locked) return; if (!effectiveReviewerId) { setNotice('Reviewer-ID mÃ¥ oppgis.'); return; } if (!validation?.valid) { setNotice(validation?.issues.join(' ') || 'Vurderingen er ikke komplett.'); return; } try { const canonical = await saveCanonicalSession(session); const response = await fetch(`/api/appraisal/${encodeURIComponent(canonical.id)}/finalize`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reviewerId: effectiveReviewerId }) }); const payload = await response.json().catch(() => null) as { session?: AppraisalSession; error?: string } | null; if (!response.ok || !payload?.session) throw new Error(payload?.error || 'Kunne ikke ferdigstille appraisal.'); setSession(payload.session); onSaved?.(payload.session); setNotice('Vurderingen er validert og lÃ¥st i canonical appraisal workflow.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Vurderingen kunne ikke lagres.'); } };

  if (!instrument) return <div className="bg-white border border-rose-200 rounded-2xl p-6 text-rose-900">Valgt instrument finnes ikke.</div>;
  const questions = instrument.questions ?? [];
  if (!effectiveReviewerId || !session) return <section className="bg-white border border-slate-200 rounded-2xl p-6 space-y-3"><h2 className="text-xl font-bold">{instrument.name}</h2><p className="text-sm text-slate-600">{notice || (starting ? 'Oppretter canonical appraisal-sessionâ€¦' : 'Appraisal-session er ikke tilgjengelig.')}</p></section>;

  return <section className="space-y-5 pb-16">
    <header className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div className="text-[10px] uppercase tracking-wide text-teal-700 font-bold">EVIDENCE APPRAISAL Â· AKTIV VURDERING</div><h2 className="text-2xl font-bold font-serif">{instrument.name}</h2><p className="text-sm text-slate-600 mt-1">Studiedesign: {studyDesign || 'ikke registrert'} Â· Studie-ID: {studyId} Â· Reviewer: {effectiveReviewerId}</p></div><select value={instrumentId} onChange={e => void changeInstrument(e.target.value)} disabled={session.locked || changingInstrument} className="rounded-xl border border-slate-300 px-3 py-2 text-sm max-w-full disabled:opacity-50">{MASTER_INSTRUMENTS_REGISTRY.map(i => <option key={i.id} value={i.id}>{i.shortName} Â· {i.version}</option>)}</select></div>{notice && <div role="status" className="mt-4 rounded-xl bg-amber-50 border border-amber-200 px-3 py-2 text-sm text-amber-900">{notice}</div>}</header>
    <div className="grid sm:grid-cols-3 gap-3"><Info label="Svar" value={`${answeredCount}/${questions.length}`} /><Info label="Instrument" value={`${instrument.shortName} ${instrument.version}`} /><Info label="Tolkningsresultat" value={String(interpretation)} /></div>
    {canonicalEvidence.length > 0 && <div className="bg-white border border-teal-200 rounded-2xl p-5"><div className="font-semibold text-slate-900">Human-verifisert evidens</div><p className="text-sm text-slate-600 mt-1">Kun kilder fra den kanoniske research-workflowen kan knyttes til appraisal-svar.</p><div className="mt-3 grid md:grid-cols-2 gap-3">{canonicalEvidence.map(item => <div key={item.id} className="rounded-xl border border-slate-200 p-3"><div className="text-xs font-bold text-slate-500">{item.id}</div><div className="text-sm mt-1">{item.quote}</div><div className="text-xs text-slate-500 mt-2">{item.location?.page ? `side ${item.location.page}` : ''}{item.location?.section ? ` · ${item.location.section}` : ''}</div></div>)}</div></div>}
    {questions.length === 0 ? <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 text-sm">Dette instrumentet mangler de faktiske vurderingspunktene i registryet. Det blir derfor ikke presentert som fullt implementert.</div> : <div className="space-y-3">{questions.map((q, index) => { const response = session.responses.find(r => String(r.itemId) === String(q.id)); const options = answerOptions(instrument.id, q.allowedAnswers ?? instrument.allowedAnswers); return <article key={String(q.id)} className="bg-white border border-slate-200 rounded-2xl p-5 space-y-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wide text-slate-400">Punkt {q.itemNumber ?? index + 1}</div><h3 className="font-bold text-slate-900 mt-1">{q.shortTitle}</h3><p className="text-sm text-slate-800 mt-2 leading-6">{q.officialQuestion || q.questionText}</p>{(q.officialQuestionEn || q.questionTextEn) && <p className="text-xs text-slate-500 italic mt-1">{q.officialQuestionEn || q.questionTextEn}</p>}</div>{q.isCritical && <span className="text-[10px] px-2 py-1 rounded-full bg-rose-50 text-rose-800 border border-rose-200 font-bold">KRITISK</span>}</div><div className="flex flex-wrap gap-2">{options.map(option => <button key={String(option)} type="button" disabled={session.locked} onClick={() => patch(q.id,{answer:String(option)})} className={`px-3 py-2 rounded-xl border text-xs font-semibold disabled:opacity-50 ${String(response?.answer ?? '')===String(option)?'bg-teal-800 text-white border-teal-800':'bg-white border-slate-300 text-slate-700'}`}>{String(option)}</button>)}</div><textarea disabled={session.locked} value={response?.rationale ?? ''} onChange={e => patch(q.id,{rationale:e.target.value})} className="w-full min-h-24 rounded-xl border border-slate-300 px-3 py-2 text-sm" placeholder="Dokumenter begrunnelsen." />{canonicalEvidence.length > 0 && <select disabled={session.locked} value={response?.evidence?.sourceId ?? ''} onChange={e => { const selected = canonicalEvidence.find(item => item.id === e.target.value); patch(q.id,{evidence:selected ? { sourceId:selected.id, quote:selected.quote, page:selected.location?.page, section:selected.location?.section } : undefined}); }} className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">Knytt kanonisk evidens (valgfritt)</option>{canonicalEvidence.map(item => <option key={item.id} value={item.id}>{item.id} · {item.quote.slice(0,100)}</option>)}</select>}</article>; })}</div>}
    <div className="flex items-center justify-between bg-white border border-slate-200 rounded-2xl p-5"><div><div className="font-semibold">Ferdigstill vurdering</div><p className="text-sm text-slate-600">{validation?.valid ? 'Alle vurderingspunkter er komplette og kan låses.' : validation?.issues.join(' ')}</p></div><button type="button" onClick={() => void finalize()} disabled={session.locked || !validation?.valid} className="rounded-xl bg-slate-900 text-white px-4 py-2 disabled:opacity-50">{session.locked ? 'Låst' : 'Ferdigstill'}</button></div>
    <QualityAssessmentPanel session={session} />
  </section>;
};
function Info({ label, value }: { label: string; value: string }) { return <div className="bg-white border border-slate-200 rounded-2xl p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className="font-semibold text-slate-900 mt-1">{value}</div></div>; }
