import React,{useEffect,useState} from 'react';
import {getHelpEntry} from '../../services/helpRegistryService';
export const HelpTooltipModal: React.FC<{ topic: string; onClose: () => void; onNavigate?: () => void }> = ({ topic, onClose, onNavigate }) => {
const entry=getHelpEntry(topic);const [step,setStep]=useState(0);useEffect(()=>setStep(0),[topic]);
return <div className='fixed inset-0 z-50 bg-slate-950/70 flex items-center justify-center p-4' role='dialog' aria-modal='true' aria-labelledby='help-title'><div className='w-full max-w-3xl max-h-[90vh] overflow-auto bg-white rounded-2xl shadow-2xl border border-slate-200'>
<div className='p-5 border-b flex items-center justify-between'><div><p className='text-xs uppercase tracking-wider text-teal-700 font-bold'>Research Copilot</p><h2 id='help-title' className='text-xl font-bold'>{entry.title}</h2></div><button type='button' onClick={onClose} className='px-3 py-2 rounded-lg border text-sm'>Lukk</button></div>
<div className='p-5 grid md:grid-cols-2 gap-5'><div className='space-y-4'><section><h3 className='font-bold'>Metodeforklaring</h3><p className='text-sm text-slate-600 mt-1'>{entry.definition}</p></section><section><h3 className='font-bold'>Tommelfingerregel</h3><p className='text-sm text-slate-600 mt-1'>{entry.ruleOfThumb}</p></section><section><h3 className='font-bold'>Standardreferanse</h3><p className='text-sm text-slate-600 mt-1'>{entry.reference}</p></section></div>
<div className='rounded-xl bg-slate-950 p-5 text-white'><div className='flex justify-between'><h3 className='font-bold'>Micro-Tutorial</h3><span className='text-xs text-teal-300'>{entry.steps.length?step+1:0}/{entry.steps.length}</span></div><svg viewBox='0 0 300 150' className='w-full h-40 mt-3' aria-label='Animert metodeveiledning'><rect x='10' y='10' width='280' height='130' rx='16' fill='#0f172a' stroke='#334155'/><circle cx={60+step*38} cy='75' r='12' fill='#2dd4bf'><animate attributeName='r' values='10;16;10' dur='1.4s' repeatCount='indefinite'/></circle>{entry.steps.map((_,i)=><line key={i} x1={60+i*38} y1='75' x2={98+i*38} y2='75' stroke='#475569' strokeWidth='3'/>)}</svg><p className='text-sm mt-2'>{entry.steps[step]||'Velg et metodeemne for å starte.'}</p>{entry.steps.length>1&&<div className='flex gap-2 mt-4'><button type='button' onClick={()=>setStep(s=>Math.max(0,s-1))} className='px-3 py-2 bg-slate-800 rounded-lg text-xs'>Forrige</button><button type='button' onClick={()=>setStep(s=>Math.min(entry.steps.length-1,s+1))} className='px-3 py-2 bg-teal-400 text-slate-950 rounded-lg text-xs font-bold'>Neste</button></div>}</div></div>
<div className='px-5 pb-5 flex gap-2'>{onNavigate&&<button type='button' onClick={onNavigate} className='px-4 py-2 rounded-lg bg-slate-900 text-white text-sm'>Åpne relevant arbeidssteg</button>}<button type='button' onClick={onClose} className='px-4 py-2 rounded-lg border text-sm'>Ferdig</button></div></div></div>};
export default HelpTooltipModal;