export type AssessmentStatus = 'Ja' | 'Nei' | 'Uklart' | 'Ikke relevant' | 'Ja, med forbehold' | 'Yes' | 'No' | 'Unclear' | 'Not applicable';
export type CerqualConcernLevel = 'No or very minor concerns' | 'Minor concerns' | 'Moderate concerns' | 'Serious concerns';
export type InstrumentCategory = 'critical_appraisal' | 'guideline_appraisal' | 'risk_of_bias' | 'implementation' | 'reporting_synthesis' | 'ethics_governance' | 'certainty_framework';
export type InstrumentType = 'critical-appraisal' | 'certainty-framework' | 'implementation-framework' | 'reporting-standard' | 'risk-of-bias' | 'ethics-framework' | 'guideline-framework';
export type StandardDocumentType = 'PRIMARY_RESEARCH_ARTICLE' | 'SYSTEMATIC_REVIEW' | 'META_ANALYSIS' | 'SCOPING_REVIEW' | 'RAPID_REVIEW' | 'INTEGRATIVE_REVIEW' | 'UMBRELLA_REVIEW' | 'QUALITATIVE_EVIDENCE_SYNTHESIS' | 'METHODOLOGY_STUDY' | 'DIAGNOSTIC_ACCURACY_STUDY' | 'RCT' | 'NON_RANDOMIZED_INTERVENTION_STUDY' | 'COHORT_STUDY' | 'CASE_CONTROL_STUDY' | 'CROSS_SECTIONAL_STUDY' | 'QUALITATIVE_STUDY' | 'MIXED_METHODS_STUDY' | 'CASE_REPORT' | 'CASE_SERIES' | 'PROTOCOL' | 'GUIDELINE' | 'NATIONAL_CLINICAL_GUIDELINE' | 'CLINICAL_PRACTICE_GUIDELINE' | 'PUBLIC_RECOMMENDATION_POLICY' | 'CONSENSUS_DOCUMENT' | 'IMPLEMENTATION_FRAMEWORK' | 'METHODOLOGICAL_FRAMEWORK' | 'REPORT' | 'HTA' | 'ECONOMIC_EVALUATION' | 'EDITORIAL_COMMENTARY' | 'LETTER_CORRESPONDENCE' | 'PROTOCOL_SYSTEMATIC_REVIEW' | 'OTHER' | 'UNKNOWN_UNCERTAIN';
export type MethodologicalApproach = 'Kvalitativ' | 'Kvantitativ (Eksperimentell / RCT)' | 'Kvantitativ (Observasjonell)' | 'Mixed Methods (Blandet metode)' | 'Kunnskapsoppsummering / Syntese' | 'Klinisk retningslinje / Normativ praksis' | 'Implementering & Tjenesteinnovasjon' | 'Diagnostikk & Testvalidering' | 'Metodologi & Verktøyutvikling' | 'Ikke-forskningsdokument / Policy' | 'Ukjent / Uavklart';
export type MethodologicalPurpose = 'Kausaleffekt / Behandlingseffekt' | 'Levde erfaringer / Sosiale fenomener' | 'Prognose / Forløp' | 'Etiologi / Risikofaktorer' | 'Prevalens / Kartlegging' | 'Diagnostisk nøyaktighet / Testvalidering' | 'Kunnskapssyntese / Meta-analyse' | 'Kvalitativ evidenssyntese' | 'Kliniske handlingsanbefalinger' | 'Implementeringsdeterminanter / Endringsprosess' | 'Metodisk rammeverk / Verktøy' | 'Studieprotokoll / Prosjektplan' | 'Kost-nytte / Helseøkonomi' | 'Uavklart / Krever manuell presisering';
export type ClassificationConfidenceStatus = 'DEFINITIVE' | 'AI_CANDIDATE_REQUIRES_VERIFICATION' | 'HUMAN_VERIFIED' | 'CONFLICTING_EVIDENCE' | 'INSUFFICIENT_INFORMATION' | 'UNCERTAIN' | 'MANUAL_VERIFICATION_REQUIRED';
export type InstrumentRoleType = 'CRITICAL_APPRAISAL_ROB' | 'CRITICAL_APPRAISAL' | 'GUIDELINE_APPRAISAL' | 'REPORTING_STANDARD' | 'EVIDENCE_CERTAINTY' | 'IMPLEMENTATION_FRAMEWORK';
export type ReferenceAssessmentType = 'CRITICAL_APPRAISAL' | 'GUIDELINE_APPRAISAL' | 'SYSTEMATIC_REVIEW' | 'RISK_OF_BIAS' | 'CERTAINTY_OF_EVIDENCE' | 'QUALITATIVE_EVIDENCE_SYNTHESIS' | 'MIXED_METHODS' | 'OTHER' | 'OFFICIAL_ALGORITHM_EXPECTED' | 'PUBLISHED_RESEARCHER_ASSESSMENT' | 'EXPERT_ADJUDICATED_REFERENCE' | 'LOCAL_TEST_EXPECTATION';
export interface HumanVerificationDecision { status: 'APPROVED' | 'MODIFIED' | 'REJECTED' | 'UNCERTAIN' | 'PENDING'; verifiedAt?: string; verifiedBy?: string; manualDocType?: StandardDocumentType; manualStudyDesign?: string; manualMethodology?: MethodologicalApproach; manualPurpose?: MethodologicalPurpose; manualInstrumentId?: string; rationale?: string; }
export interface LegalActReference { actName: string; officialName?: string; shortCode?: string; officialShortCode?: string; sectionReference?: string; relevantSections?: string[]; jurisdiction?: string; lovdataUrl?: string; legalCategory: string; legalCategoryName: string; normativeLevel: string; snippetText: string; isStatutoryDuty: boolean; description: string; relevanceForAppraisal: string; }
export interface LegalAnalysisResult { identifiedActs: LegalActReference[]; hasLegalActs?: boolean; hasStatutoryDuties: boolean; statutoryDutiesCount: number; statutoryDuties?: { rawText: string; legalBasis?: string }[]; professionalAdvice?: { rawText: string; context?: string }[]; ethicsAndPrivacyApprovals: { hasRekApproval: boolean; rekReference?: string; hasSiktNsdApproval: boolean; siktReference?: string; hasInformedConsent: boolean; hasDeclarationOfHelsinki: boolean; hasGdprCompliance: boolean }; summary: string; }
export type AuthorityLevel = 'original-source' | 'peer-reviewed-publication' | 'official-manual' | 'secondary-source' | 'gold-standard';
export type VerificationStatus = 'VERIFIED' | 'PARTIALLY_VERIFIED' | 'UNVERIFIED' | 'PROTOTYPE' | 'DEPRECATED';
export type ScoringModelType = 'official' | 'none' | 'qualitative-judgement' | 'domain-based' | 'researcher-defined' | 'critical-domain-weighting' | 'not-verified';
export type MethodologyAlignmentStatus = 'INTERNAL_SOURCE_CONTROLLED' | 'OFFICIAL_SOURCE_REFERENCED' | 'PEER_REVIEWED_SUPPORT' | 'GOLD_STANDARD_REFERENCE' | 'PENDING_VERIFICATION' | 'INTERNALLY_COMPLIANCE_CHECKED' | 'NEEDS_REVISION' | 'ACTIVE_INTERNATIONAL_STANDARD';
export interface ComparisonDimension { id: string; label?: string; dimension?: string; description?: string; [key: string]: unknown; }
export type MethodologicalFunctionType = 'CRITICAL_APPRAISAL' | 'SYSTEMATIC_REVIEW_CONFIDENCE' | 'GUIDELINE_RIGOUR_EVALUATION' | 'GUIDELINE_QUALITY_APPRAISAL' | 'CERTAINTY_OF_EVIDENCE_GRADING' | 'EVIDENCE_CERTAINTY_RATING' | 'RISK_OF_BIAS_ASSESSMENT' | 'EFFECT_ESTIMATE_RISK_OF_BIAS' | 'REPORTING_TRANSPARENCY_STANDARD' | 'IMPLEMENTATION_DETERMINANT_MAPPING' | 'IMPLEMENTATION_PROCESS_MODEL';
export interface InstrumentQuestionItem { id: number | string; itemNumber?: number; shortTitle: string; questionText?: string; questionTextEn?: string; officialQuestion?: string; officialQuestionEn?: string; descriptionGuide?: string; categoryTitle?: string; domain?: string; domainTitle?: string; isCritical?: boolean; allowedAnswers?: string[]; }
export interface AppraisalInstrument { id: string; name: string; shortName: string; version: string; edition: string; year: number; latestUpdateYear: number; instrumentType: InstrumentType; methodologicalFunction: MethodologicalFunctionType; methodologicalFunctionDescription: string; unitOfAnalysis: string; academicOutputFormat: string; prohibitedAcademicPractices: string[]; epistemologicalRole: string; purpose: string; category: InstrumentCategory; categoryName: string; status: 'Available' | 'Active' | 'Beta'; itemCount: number; targetStudyDesign: string[]; targetPopulationOrContext: string; publisher: string; governingBody: string; authorityLevel: AuthorityLevel; officialSource: string; sourceUrl?: string; primaryPublication: string; doi?: string; licenseStatus: string; usagePermission: string; sourceAttribution: string; allowedAnswers: string[]; scoringModel: ScoringModelType; scoringModelExplanation: string; interpretationModel: string; criticalDomains?: string[]; knownLimitations: string; methodologyControlStatus?: string; whoComplianceStatus?: string; whoHandbookRef?: string; methodologyAlignmentStatus?: MethodologyAlignmentStatus | string; sourceReference?: string; validationChecksum: string; applicableStudyTypes: string[]; qualityControlGuidelines: string; verificationStatus: VerificationStatus; verifiedAt: string; verifiedBy: string; questions?: InstrumentQuestionItem[]; }
export type AssessmentLifecycleStatus = 'DRAFT' | 'IN_REVIEW' | 'FINALIZED' | 'REOPENED' | 'AMENDED';
export type AiEvidenceStatus = 'AI_SUGGESTED' | 'HUMAN_VERIFIED' | 'REJECTED' | 'MANUAL_ENTRY';
export interface AssessmentSnapshot { assessmentId: string; studyId: string; instrumentId: string; instrumentName: string; instrumentVersion: string; instrumentEdition: string; instrumentVariant?: string; source: string; sourcePublication: string; doi?: string; studyDesign: string; createdAt: string; createdBy: string; finalizedAt?: string; finalizedBy?: string; documentHash?: string; immutableLockHash: string; lifecycleStatus: AssessmentLifecycleStatus; reopenHistory?: { reopenedAt: string; reopenedBy: string; reason: string; previousStatus: AssessmentLifecycleStatus }[]; }
export interface VersionLockMetadata { instrumentId: string; instrumentVersion: string; instrumentYear: number; source: string; sourcePublication: string; doi?: string; assessmentStartedAt: string; assessmentVersion: string; schemaVersion: string; immutableLockHash: string; }
export interface EvidenceLocation { page?: string; section?: string; table?: string; figure?: string; }
export interface JBIQuestion { id: number; shortTitle: string; officialQuestion: string; officialQuestionEn: string; descriptionGuide: string; category: 'metodisk_samsvar' | 'forskerrolle' | 'representasjon' | 'etikk' | 'konklusjon'; categoryTitle: string; whoControlPrinciple?: string; }
export interface JBIEvaluationItem { questionId: number; questionTitle?: string; status: AssessmentStatus; justification: string; evidenceText?: string; location?: EvidenceLocation; sourceQuoteOrRef?: string; reviewerNotes?: string; candidateEvidenceVerified?: boolean; aiEvidenceStatus?: AiEvidenceStatus; aiSuggestionReason?: string; aiSuggestedStatus?: AssessmentStatus; }
export interface AuditTrailEntry { id: string; studyId: string; reviewer: string; instrumentId: string; version: string; itemId: number; itemTitle?: string; previousAnswer: string; newAnswer: string; previousRationale: string; newRationale: string; changedBy: string; timestamp: string; comment?: string; action?: string; previousHash?: string; entryHash?: string; }
export interface DualReviewComparison { studyId: string; studyTitle: string; reviewer1: { name: string; date: string; items: JBIEvaluationItem[]; verdict: string }; reviewer2: { name: string; date: string; items: JBIEvaluationItem[]; verdict: string }; itemComparisons: { questionId: number; questionTitle: string; r1Status: AssessmentStatus; r2Status: AssessmentStatus; isAgreement: boolean; r1Rationale: string; r2Rationale: string; consensusStatus?: AssessmentStatus; consensusRationale?: string; }[]; overallAgreementPercentage: number; totalAgreements: number; totalDisagreements: number; consensusVerdict?: 'Inkluder' | 'Ekskluder' | 'Søk mer informasjon'; }
export interface CandidateEvidence { questionId: number; suggestedStatus?: AssessmentStatus; relevanceScore: number; suggestedLocation: EvidenceLocation; extractedSnippet: string; confidenceReason: string; verifiedByResearcher: boolean; }
export interface DocumentAnalysisResult { fileName: string; analyzedAt: string; totalPassagesFound: number; disclaimer: string; goldenRule: string; candidateEvidence: CandidateEvidence[]; imradAnalysis?: IMRaDAnalysisResult; }
export interface ScoreCalculationResult { ja: number; uklart: number; nei: number; ikkeRelevant: number; total: number; answered: number; unanswered: number; completenessPercent: number; jaScorePercent: number; applicableTotal: number; applicableJaPercent: number; }
export interface VerdictRecommendation { verdict: 'Inkluder' | 'Ekskluder' | 'Vurder videre' | 'Søk mer informasjon' | 'Ufullstendig'; riskOfBias: 'Lav' | 'Moderat' | 'Høy' | 'Uavklart'; rationale: string; criticalFlaws: string[]; suggestedAction: string; }
export interface InterRaterAgreementResult { totalItems: number; agreedCount: number; disagreedCount: number; percentAgreement: number; agreementPercentage?: number; cohensKappa: number; kappaInterpretation: 'Svært god (Almost perfect)' | 'Betydelig (Substantial)' | 'Moderat (Moderate)' | 'Middels (Fair)' | 'Dårlig (Poor)'; interpretation?: string; discrepancies: { questionId: number; questionTitle: string; r1Status: AssessmentStatus; r2Status: AssessmentStatus; r1Rationale?: string; r2Rationale?: string; }[]; }
export interface ValidationReport { isValid: boolean; instrumentId: string; instrumentName?: string; instrumentVersion?: string; timestamp: string; totalItems: number; answeredItems: number; completenessPercent: number; errors: string[]; warnings: string[]; counts: { yes: number; no: number; unclear: number; notApplicable: number; unanswered: number }; scoreCalculation: ScoreCalculationResult; verdictRecommendation: VerdictRecommendation; summaryVerdictSuggestion: 'Inkluder' | 'Ekskluder' | 'Vurder videre' | 'Søk mer informasjon' | 'Ufullstendig'; methodologyControl?: MethodologyControlReport; whoCompliance?: unknown; }
export interface MethodologyRuleEvaluation { id: string; name: string; standard: string; category: string; passed: boolean; severity: 'critical' | 'warning' | 'info'; details: string; recommendation: string; }
export interface MethodologyControlReport { overallPassed: boolean; complianceScore: number; whoHandbookStandard: string; appraisalModel: string; modelVersion: string; modelChecksum: string; timestamp: string; articleCitation: string; rules: MethodologyRuleEvaluation[]; passedRuleCount: number; totalRuleCount: number; summaryVerdict: 'INTERN_METODISK_KONTROLLERT' | 'KREVER_KOMPLETTERING' | 'IKKE_GODKJENT'; recommendations: string[]; }
export interface WhoEtdCriteriaInput { guidelineQuestion: string; targetPopulation: string; intervention: string; comparison: string; balanceOfEffects: string; certaintyOfEvidence: string; valuesUncertainty: string; resourcesRequired: string; costEffectiveness: string; equity: string; acceptability: string; feasibility: string; problemPriority?: string; desirableEffects?: string; undesirableEffects?: string; }
export interface WhoEtdEvaluationResult { guidelineQuestion: string; targetPopulation: string; intervention: string; comparison: string; recommendationType: string; strengthRationale: string; detailedCriteriaAudit: Array<Record<string, unknown>>; implementationConsiderations: string[]; monitoringAndEvaluation: string[]; methodologicalStandard: string; }
export interface DocumentClassificationResult { documentType: StandardDocumentType | string; documentTypeName?: string; documentTypeNameEn?: string; isResearchDocument?: boolean; studyDesign?: string; methodologicalApproach?: MethodologicalApproach; methodologicalPurpose?: MethodologicalPurpose; methodologyType?: string; epistemology?: string; recommendedInstrumentId: string; recommendedInstrumentName?: string; instrumentRoleType?: InstrumentRoleType; confidenceStatus: ClassificationConfidenceStatus; confidence?: number; confidenceScore?: number; rationale: string; detectedMethodology?: MethodologicalApproach; detectedPurpose?: MethodologicalPurpose; detectedKeywords?: string[]; alternativeInstrumentIds?: string[]; incompatibleInstrumentIds?: string[]; humanDecision?: HumanVerificationDecision; statusBadgeText?: string; evidenceSignals?: { signalType: string; value: string; foundIn: string }[]; hasMetadataContentConflict?: boolean; conflictDetails?: string; recommendedInstrumentJustification?: string; alternativeInstruments?: Array<{ id: string; name: string; role: string }>; methodologicalLimitations?: string; instrumentSourceAndAuthority?: string; legalAnalysis?: LegalAnalysisResult; }
export interface ResearchGroupWorkspace { id: string; name?: string; description?: string; ownerId?: string; memberIds?: string[]; members?: ReviewerProfile[]; projectName?: string; institutionOrCourse?: string; protocolPrismaTarget?: string; requireDualReview?: boolean; blindedMode?: boolean; activeReviewerId?: string; submissions?: Record<string, PeerReviewSubmission[]>; comments?: PeerReviewComment[]; consensusRecords?: Record<string, StudyConsensusRecord>; createdAt: string; updatedAt: string; }
export type ReviewerRole = string;
export type CommentCategory = string;
export interface ReviewerProfile { id: string; displayName?: string; name?: string; role: string; email?: string; institution?: string; expertise?: string[]; active?: boolean; avatarColor?: string; isCurrentUser?: boolean; }
export interface PeerReviewSubmission { id: string; workspaceId?: string; reviewerId: string; articleId?: string; content?: string; submittedAt?: string; status: 'DRAFT' | 'SUBMITTED' | 'REVIEWED' | 'COMPLETED'; items?: JBIEvaluationItem[]; reviewerName?: string; reviewerRole?: string; studyId?: string; startedAt?: string; completedAt?: string; overallVerdict?: 'Inkluder' | 'Ekskluder' | 'Vurder videre' | 'Søk mer informasjon' | 'Ufullstendig'; verdictRationale?: string; keyStrength?: string; mainLimitation?: string; }
export interface PeerReviewComment { id: string; questionId?: number; submissionId?: string; authorId: string; content?: string; text?: string; createdAt: string; resolved: boolean; studyId?: string; category?: string; resolvedAt?: string; resolvedBy?: string; authorName?: string; authorRole?: string; }
export interface StudyConsensusRecord { id: string; studyId: string; reviewerIds: string[]; consensusStatus: AssessmentStatus | null; rationale: string; resolvedAt?: string; resolvedBy?: string; meetingDate?: string; assignedReviewerIds?: string[]; arbiterId?: string; signedOffBy?: string[]; status?: string; itemConsensus?: Record<number, { status: AssessmentStatus; rationale: string; agreedBy: string[]; adoptedFromReviewerId?: string }>; overallVerdict?: string; verdictRationale?: string; consensusNotes?: string; lockedAt?: string; }
export interface MetaResearchReport { id: string; title: string; generatedAt: string; integrityScore: number; classifications: MetaResearchClassification[]; dimensions: MetaResearchIntegrityDimension[]; methodologyNotes: string[]; fileName?: string; extractedTitle?: string; extractedAuthors?: string; extractedDoi?: string; extractedYear?: number | string; extractedAbstract?: string; classification?: MetaResearchClassification; integrityDimensions?: MetaResearchIntegrityDimension[]; overallIntegrityLevel?: string; integritySummary?: string; keyStrengths?: string[]; potentialMethodologicalRisks?: string[]; candidateEvidence?: CandidateEvidence[]; engineUsed?: string; }
export interface MetaResearchClassification { documentType: string; documentTypeName?: string; documentTypeNameEn?: string; methodologyType?: string; epistemology?: string; confidenceScore?: number; detectedKeywords?: string[]; rationale?: string; unitOfAnalysis?: string; recommendedInstrumentId: string; alternativeInstrumentIds?: string[]; incompatibleInstrumentIds?: string[]; label?: string; confidence?: number; evidence?: string[]; }
export interface MetaResearchIntegrityDimension { id: string; name: string; category: string; score: 'HIGH' | 'MODERATE' | 'UNCLEAR' | 'LOW' | 'NOT_APPLICABLE'; assessment: string; recommendation: string; explanation?: string; foundSnippet?: string; }
export type DocumentTypeCategory = StandardDocumentType | string;
export type MethodologyFamily = 'qualitative' | 'quantitative' | 'mixed-methods' | 'synthesis' | 'guideline' | 'implementation' | 'diagnostic' | 'methodology' | 'policy' | 'unknown';
export interface ReferenceValidationArticle { id: string; title: string; journal: string; year: number; doi: string; instrumentId: string; instrumentName: string; instrumentVersion: string; referenceAssessmentType: string; expectedOverallScoreOrVerdict: string; authors?: string; pmid?: string; verificationStatus?: string; verificationDate?: string; publisher?: string; articleUrl?: string; database?: string; whySelected?: string; validationSource?: string; supplementaryMaterials?: any[]; itemData: Array<{ itemNumber: number; itemTitle: string; referenceResponse: string; referenceSource: string; evidenceSnippet?: string; referenceRationale: string; reviewerOrStudy?: string; agreementStatus?: string; }>; selectionCriteria?: Record<string, unknown>; verifiedBy?: string; expectedCriticalFlawsCount?: number; expectedNonCriticalFlawsCount?: number; methodologicalNotes?: string; fullTextUrl?: string; }
export interface GoldStandardDiffItem { itemNumber: number; itemTitle: string; referenceResponse: string; applicationResponse: string; difference: string; referenceSource: string; evidenceSnippet: string; severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'; isMatch: boolean; }
export type DiffSeverity = GoldStandardDiffItem['severity'];
export type GoldStandardMatchStatus = 'MATCH' | 'PARTIAL_MATCH' | 'MISMATCH' | 'UNABLE_TO_COMPARE';
export interface GoldStandardDiffResult { articleId: string; articleTitle: string; instrumentId: string; instrumentVersion: string; referenceAssessmentType: string; totalItemsCompared: number; matchingItemsCount: number; mismatchingItemsCount: number; matchPercentage: number; matchStatus: GoldStandardMatchStatus; criticalMismatchesCount: number; highMismatchesCount: number; mediumMismatchesCount: number; lowMismatchesCount: number; itemDiffs: GoldStandardDiffItem[]; summaryMessage: string; scientificValidityNotice: string; }
export interface GradeCerqualSummaryItem { id: string; finding: string; confidence: 'High confidence' | 'Moderate confidence' | 'Low confidence' | 'Very low confidence'; rationale: string; reviewFinding?: string; methodologicalLimitations?: CerqualConcernLevel; coherence?: CerqualConcernLevel; adequacyOfData?: CerqualConcernLevel; relevance?: CerqualConcernLevel; contributingStudies?: number | string; overallConfidence?: 'High confidence' | 'Moderate confidence' | 'Low confidence' | 'Very low confidence'; }
export interface ReferenceValidationArticleSummary { id: string; title: string; instrumentId: string; status: 'PASS' | 'FAIL' | 'UNABLE_TO_COMPARE'; }
export interface Actor { id: string; role: string; name?: string; }
export interface ValidationDashboardInstrumentCard { id?: string; name?: string; instrumentName?: string; status?: string; version?: string; instrumentId?: string; [key: string]: any; }
export interface ReleaseGateCheck { id: string; label?: string; title?: string; passed: boolean; details?: string; [key: string]: any; }
export interface GradeSummaryOfFindingsItem {
  id: string;
  reviewFinding: string;
  methodologicalLimitations: string;
  coherence: string;
  adequacyOfData: string;
  relevance: string;
  contributingStudies: number | string;
  overallConfidence: GradeCerqualSummaryItem['confidence'];
  outcomeName?: string;
  importance?: string;
  studyDesign?: string;
  participantsCount?: number;
  studiesCount?: number;
  relativeEffect?: string;
  correspondingRisk?: string;
  riskOfBias?: string | 0 | -1 | -2;
  inconsistency?: string | 0 | -1 | -2;
  indirectness?: string | 0 | -1 | -2;
  imprecision?: string | 0 | -1 | -2;
  publicationBias?: string | 0 | -1 | -2;
  certainty?: string;
  [key: string]: unknown;
}
export interface ArticleAppraisal { id: string; projectId?: string; isDemoData?: boolean; instrumentId?: string; instrumentVersion?: string; lifecycleStatus?: AssessmentLifecycleStatus; snapshot?: AssessmentSnapshot; documentHash?: string; parsingStatus?: 'PARSED_COMPLETE' | 'PARSED_INCOMPLETE' | 'PARSED_WITH_WARNINGS' | 'NOT_PARSED'; methodologyAlignmentStatus?: MethodologyAlignmentStatus | string; whoValidationStatus?: string; authors: string; shortCitation: string; year: number; publicationYear?: number; title: string; journal: string; volumeIssue?: string; pages?: string; abstract?: string; doi: string; doiUrl: string; sourceUrl: string; sourceName: string; studyContext: string; design: string; studyDesign?: string; methodology?: string; dataCollection?: string; participants?: string; analyticMethod?: string; epistemology?: string; reviewerName?: string; reviewerRole?: string; assessmentDate?: string; projectName?: string; summaryScore?: Partial<ScoreCalculationResult> & Pick<ScoreCalculationResult, 'ja' | 'uklart' | 'nei' | 'ikkeRelevant' | 'total'>; overallVerdict?: string; verdictNote?: string; keyStrength?: string; mainLimitation?: string; apaReference?: string; items?: JBIEvaluationItem[]; auditTrail?: AuditTrailEntry[]; }

export type IMRaDSectionKey = 'introduction' | 'methods' | 'results' | 'discussion';
export type IMRaDSectionStatus = 'DETECTED' | 'INFERRED' | 'MISSING';
export interface IMRaDSectionAnalysis {
  key: IMRaDSectionKey;
  label: string;
  detected: boolean;
  explicitHeading: boolean;
  confidence: number;
  characterCount: number;
  wordCount: number;
  evidencePreview: string;
  status: IMRaDSectionStatus;
}
export interface IMRaDAnalysisResult {
  fileName: string;
  standard: 'IMRaD';
  standardDescription: string;
  analyzedAt: string;
  complete: boolean;
  explicitComplete: boolean;
  detectedSectionCount: number;
  explicitHeadingCount: number;
  confidence: number;
  sections: IMRaDSectionAnalysis[];
  missingSections: string[];
  limitations: string[];
  methodologicalNotice: string;
}
