import React, { useEffect, useMemo, useState } from 'react';
export type YggdrasilNode={id:string;label:string;zone:'roots'|'trunk'|'crown'|'well';x:number;y:number;description:string;checklist:string[];target?:string};
const NODES:YggdrasilNode[]=[
{id:'pico',label:'PICO',zone:'roots',x:20,y:74,description:'Avgrens Population, Intervention, Comparison og Outcome fÃ¸r sÃ¸k og inklusjon.',checklist:['Definer populasjon og setting','Definer intervensjon og sammenligning','Operasjonaliser primÃ¦re utfall'],target:'source_workflow'},
{id:'extraction',label:'RÃ¥dataekstraksjon',zone:'roots',x:34,y:83,description:'Skill mellom AI-forslag og menneskelig verifiserte data.',checklist:['Kontroller N og studiedesign','Dokumenter kilde og sidetall','Marker HUMAN_VERIFIED fÃ¸rst etter kontroll'],target:'source_workflow'},
{id:'screening',label:'Screening',zone:'roots',x:49,y:76,description:'Screening mÃ¥ vÃ¦re eksplisitt og sporbar fÃ¸r appraisal.',checklist:['INCLUDED eller EXCLUDED','Reviewer og tidspunkt','Begrunn beslutningen'],target:'source_workflow'},
{id:'synthesis',label:'Syntese',zone:'trunk',x:50,y:54,description:'Sammenstill kompatible effektmÃ¥l og vurder klinisk og metodisk heterogenitet.',checklist:['Velg effektmÃ¥l','Velg modell','Kontroller heterogenitet'],target:'meta_research'},
{id:'forest',label:'Forest Plot',zone:'trunk',x:66,y:48,description:'Visualiser studieestimater, konfidensintervaller og pooled estimate.',checklist:['Kontroller CI','Kontroller studievekter','Dokumenter modell'],target:'meta_research'},
{id:'heterogeneity',label:'IÂ² / Q / Ï„Â²',zone:'trunk',x:78,y:57,description:'Heterogenitet skal tolkes sammen med klinisk og metodisk variasjon.',checklist:['Beregn Q og df','Beregn IÂ²','Vurder Ï„Â² ved random effects'],target:'meta_research'},
{id:'grade',label:'GRADE',zone:'crown',x:50,y:18,description:'Vurder certainty per utfall og dokumenter hvert nedgraderings- og eventuelt oppgraderingsgrunnlag.',checklist:['Risk of bias','Inconsistency','Indirectness','Imprecision','Publication bias'],target:'synthesis'},
{id:'rob',label:'Risk of Bias',zone:'crown',x:28,y:28,description:'Knytt appraisal til korrekt instrument og studiedesign.',checklist:['Velg instrument','Dokumenter signalling questions','Begrunn samlet vurdering'],target:'appraisal'},
{id:'well',label:'Urds brÃ¸nn',zone:'well',x:78,y:82,description:'Metodisk integritet, konsensus og revisjonsspor gjÃ¸r beslutningene reproduserbare.',checklist:['Sammenlign uavhengige vurderinger','LÃ¸s konflikter med begrunnelse','Bevar audit trail'],target:'peer_review'}
];
const EDGES=[['pico','extraction'],['extraction','screening'],['screening','synthesis'],['synthesis','forest'],['forest','heterogeneity'],['synthesis','grade'],['rob','grade'],['heterogeneity','grade'],['screening','well']];
export const YggdrasilVisualizer:React.FC<{onNavigate?:(target:string)=>void}>=({onNavigate})=>{
const [selected,setSelected]=useState<YggdrasilNode>(NODES[0]); const [autopilot,setAutopilot]=useState(false); const [step,setStep]=useState(0); const [mode,setMode]=useState<'tree'|'globe'|'mosaic'>('tree');
useEffect(()=>{if(!autopilot)return;const timer=window.setInterval(()=>{setStep(current=>{const next=(current+1)%NODES.length;setSelected(NODES[next]);return next;});},1800);return()=>window.clearInterval(timer);},[autopilot]);
const particles=useMemo(()=>Array.from({length:72},(_,i)=>({x:(i*37)%100,y:(i*61)%100,delay:(i%12)*0.18})),[]);
const edgePoints=(a:string,b:string)=>{const from=NODES.find(n=>n.id===a)!;const to=NODES.find(n=>n.id===b)!;return from.x+','+from.y+' '+to.x+','+to.y;};
return <section className='bg-slate-950 text-white rounded-3xl border border-slate-800 overflow-hidden shadow-xl' aria-label='Interaktivt Yggdrasil kunnskapstre'>
<div className='px-5 py-4 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3'><div><p className='text-xs uppercase tracking-[0.18em] text-teal-300 font-bold'>Evidence Knowledge Engine</p><h2 className='text-xl sm:text-2xl font-bold'>Yggdrasil â€” fra rÃ¥data til evidens</h2><p className='text-sm text-slate-300 mt-1'>Klikk pÃ¥ en node eller start Â«Demonstrer selvÂ».</p></div><div className='flex flex-wrap gap-2'>
 {(['tree','globe','mosaic'] as const).map(m=><button key={m} type='button' onClick={()=>setMode(m)} className={'px-3 py-2 rounded-lg text-xs font-semibold '+(mode===m?'bg-teal-500 text-slate-950':'bg-slate-800 text-slate-200')}>{m==='tree'?'Kunnskapstre':m==='globe'?'Evidensklode':'Partikkelmosaikk'}</button>)}
<button type='button' onClick={()=>{setAutopilot(v=>!v);setStep(0);}} className='px-3 py-2 rounded-lg bg-amber-300 text-slate-950 text-xs font-bold'>{autopilot?'Stopp demonstrasjon':'Demonstrer selv'}</button></div></div>
<div className='grid lg:grid-cols-[1fr_330px] min-h-[560px]'><div className='relative min-h-[560px] p-3'>
<svg viewBox='0 0 100 100' className='w-full h-full min-h-[540px]' role='img' aria-label='Yggdrasil med metode- og evidensnoder'><defs><radialGradient id='yg-glow'><stop offset='0%' stopColor='#5eead4' stopOpacity='0.55'/><stop offset='100%' stopColor='#0f172a' stopOpacity='0'/></radialGradient></defs><rect width='100' height='100' fill='#020617'/>
{particles.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r='0.45' fill='#5eead4' opacity='0.45'><animate attributeName='cy' values={p.y+';'+((p.y+8)%100)+';'+p.y} dur={(3.2+p.delay)+'s'} repeatCount='indefinite'/></circle>)}
{mode==='globe'&&<circle cx='50' cy='48' r='27' fill='url(#yg-glow)' stroke='#2dd4bf' strokeOpacity='0.35' strokeWidth='0.5'/>}
{EDGES.map(([a,b])=><polyline key={a+b} points={edgePoints(a,b)} fill='none' stroke='#334155' strokeWidth='1.2'/>)}
<path d='M50 92 C47 82 49 70 50 54 C50 43 47 31 50 22' fill='none' stroke='#a16207' strokeWidth='3.2'/><path d='M50 70 C38 58 28 50 20 43 M50 63 C63 53 72 43 82 34 M50 47 C42 37 34 30 27 25 M50 44 C58 35 67 27 75 22' fill='none' stroke='#92400e' strokeWidth='2'/>
{NODES.map(node=>{const selectedNode=node.id===selected.id;return <g key={node.id} tabIndex={0} role='button' aria-label={node.label} onClick={()=>setSelected(node)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setSelected(node);}}><circle cx={node.x} cy={node.y} r={selectedNode?4.5:3.2} fill={selectedNode?'#fbbf24':'#14b8a6'} stroke='#ecfeff' strokeWidth='0.7'/>{selectedNode&&<circle cx={node.x} cy={node.y} r='7' fill='none' stroke='#fbbf24' strokeOpacity='0.6'><animate attributeName='r' values='5;9;5' dur='1.6s' repeatCount='indefinite'/></circle>}<foreignObject x={node.x-11} y={node.y+4} width='22' height='8'><div xmlns='http://www.w3.org/1999/xhtml' style={{fontSize:'14px',fontWeight:700,color:'#f8fafc',textAlign:'center',textShadow:'0 1px 3px #000',whiteSpace:'nowrap'}}>{node.label}</div></foreignObject></g>;})}
<text x='4' y='96' fill='#94a3b8' fontSize='3.2'>RÃ˜TTER Â· datagrunnlag og screening</text><text x='4' y='52' fill='#94a3b8' fontSize='3.2'>STAMME Â· syntese og metaanalyse</text><text x='4' y='8' fill='#94a3b8' fontSize='3.2'>KRONE Â· GRADE og certainty</text></svg></div>
<aside className='border-t lg:border-t-0 lg:border-l border-slate-800 bg-slate-900 p-5'><p className='text-[11px] uppercase tracking-widest text-teal-300 font-bold'>{selected.zone}</p><h3 className='text-lg font-bold mt-1'>{selected.label}</h3><p className='text-sm text-slate-300 leading-relaxed mt-3'>{selected.description}</p><h4 className='text-sm font-bold mt-5'>Metodesjekkliste</h4><ul className='mt-2 space-y-2'>{selected.checklist.map(item=><li key={item} className='text-sm text-slate-200'>â€¢ {item}</li>)}</ul>{selected.target&&<button type='button' onClick={()=>onNavigate?.(selected.target!)} className='mt-6 w-full px-4 py-3 rounded-xl bg-teal-400 text-slate-950 font-bold text-sm'>Ã…pne modul</button>}{autopilot&&<p className='mt-4 text-xs text-amber-200'>Demonstrerer steg {step+1} av {NODES.length}: {selected.label}</p>}</aside></div></section>;};
export default YggdrasilVisualizer;
